// Code generated by "pipeline"; DO NOT EDIT.

package venti

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Venti, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
		action.ActionSkill:  {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Venti, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{
			{ // attack: DivineMarksmanship - 1-Hit DMG: {0}+{0}
				0.20382,
				0.22041,
				0.237,
				0.2607,
				0.27729,
				0.29625,
				0.32232,
				0.34839,
				0.37446,
				0.4029,
				0.43549,
				0.47381,
				0.51213,
				0.55046,
				0.59226,
			},
			{ // attack: DivineMarksmanship - 1-Hit DMG: {0}+{0}
				0.20382,
				0.22041,
				0.237,
				0.2607,
				0.27729,
				0.29625,
				0.32232,
				0.34839,
				0.37446,
				0.4029,
				0.43549,
				0.47381,
				0.51213,
				0.55046,
				0.59226,
			},
		},
		{{ // attack: DivineMarksmanship - 2-Hit DMG: {1}
			0.44376,
			0.47988,
			0.516,
			0.5676,
			0.60372,
			0.645,
			0.70176,
			0.75852,
			0.81528,
			0.8772,
			0.94815,
			1.03159,
			1.11502,
			1.19846,
			1.28948,
		}},
		{{ // attack: DivineMarksmanship - 3-Hit DMG: {2}
			0.52374,
			0.56637,
			0.609,
			0.6699,
			0.71253,
			0.76125,
			0.82824,
			0.89523,
			0.96222,
			1.0353,
			1.11904,
			1.21751,
			1.31599,
			1.41446,
			1.52189,
		}},
		{
			{ // attack: DivineMarksmanship - 4-Hit DMG: {3}+{3}
				0.26058,
				0.28179,
				0.303,
				0.3333,
				0.35451,
				0.37875,
				0.41208,
				0.44541,
				0.47874,
				0.5151,
				0.55676,
				0.60576,
				0.65475,
				0.70375,
				0.7572,
			},
			{ // attack: DivineMarksmanship - 4-Hit DMG: {3}+{3}
				0.26058,
				0.28179,
				0.303,
				0.3333,
				0.35451,
				0.37875,
				0.41208,
				0.44541,
				0.47874,
				0.5151,
				0.55676,
				0.60576,
				0.65475,
				0.70375,
				0.7572,
			},
		},
		{{ // attack: DivineMarksmanship - 5-Hit DMG: {4}
			0.50654,
			0.54777,
			0.589,
			0.6479,
			0.68913,
			0.73625,
			0.80104,
			0.86583,
			0.93062,
			1.0013,
			1.08229,
			1.17753,
			1.27277,
			1.36801,
			1.47191,
		}},
		{{ // attack: DivineMarksmanship - 6-Hit DMG: {5}
			0.7095,
			0.76725,
			0.825,
			0.9075,
			0.96525,
			1.03125,
			1.122,
			1.21275,
			1.3035,
			1.4025,
			1.51594,
			1.64934,
			1.78274,
			1.91614,
			2.06168,
		}},
	}
	// attack: DivineMarksmanship - Aimed Shot: {6}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.93713,
		1.01959,
		1.10206,
		1.18453,
		1.27449,
	}
	// attack: DivineMarksmanship - Fully-Charged Aimed Shot: {7}
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.36096,
		2.5296,
		2.69824,
		2.86688,
		3.03552,
	}
	// attack: DivineMarksmanship - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// attack: DivineMarksmanship - Windsunder Arrow DMG: {11} Normal Attack DMG
	hurricaneBonus = []float64{
		1.6,
		1.7,
		1.8,
		1.9,
		2.0,
		2.1,
		2.2,
		2.3,
		2.4,
		2.5,
		2.6,
		2.7,
		2.8,
		2.9,
		3.0,
	}
	// skill: SkywardSonnet - Press DMG: {0}
	skillPress = []float64{
		2.76,
		2.967,
		3.174,
		3.45,
		3.657,
		3.864,
		4.14,
		4.416,
		4.692,
		4.968,
		5.244,
		5.52,
		5.865,
		6.21,
		6.555,
	}
	// skill: SkywardSonnet - Hold DMG: {2}
	skillHold = []float64{
		3.8,
		4.085,
		4.37,
		4.75,
		5.035,
		5.32,
		5.7,
		6.08,
		6.46,
		6.84,
		7.22,
		7.6,
		8.075,
		8.55,
		9.025,
	}
	// burst: WindsGrandOde - DoT: {0}
	burstDot = []float64{
		0.376,
		0.4042,
		0.4324,
		0.47,
		0.4982,
		0.5264,
		0.564,
		0.6016,
		0.6392,
		0.6768,
		0.7144,
		0.752,
		0.799,
		0.846,
		0.893,
	}
	// burst: WindsGrandOde - Additional Elemental DMG: {1}
	burstAbsorbDot = []float64{
		0.188,
		0.2021,
		0.2162,
		0.235,
		0.2491,
		0.2632,
		0.282,
		0.3008,
		0.3196,
		0.3384,
		0.3572,
		0.376,
		0.3995,
		0.423,
		0.4465,
	}
)
