// Code generated by "pipeline"; DO NOT EDIT.

package xilonen

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Xilonen, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Xilonen, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: EhecatlsRoar - 1-Hit DMG: {0}
			0.51792,
			0.56007,
			0.60223,
			0.66245,
			0.70461,
			0.75279,
			0.81903,
			0.88528,
			0.95152,
			1.02379,
			1.09606,
			1.16833,
			1.24059,
			1.31286,
			1.38513,
		}},
		{
			{ // attack: EhecatlsRoar - 2-Hit DMG: {1}+{2}
				0.27374,
				0.29602,
				0.3183,
				0.35013,
				0.37241,
				0.39788,
				0.43289,
				0.4679,
				0.50291,
				0.54111,
				0.57931,
				0.6175,
				0.6557,
				0.69389,
				0.73209,
			},
			{ // attack: EhecatlsRoar - 2-Hit DMG: {1}+{2}
				0.27374,
				0.29602,
				0.3183,
				0.35013,
				0.37241,
				0.39788,
				0.43289,
				0.4679,
				0.50291,
				0.54111,
				0.57931,
				0.6175,
				0.6557,
				0.69389,
				0.73209,
			},
		},
		{{ // attack: EhecatlsRoar - 3-Hit DMG: {3}
			0.72949,
			0.78887,
			0.84825,
			0.93308,
			0.99245,
			1.06031,
			1.15362,
			1.24693,
			1.34023,
			1.44202,
			1.54382,
			1.6456,
			1.7474,
			1.84918,
			1.95097,
		}},
	}
	// attack: EhecatlsRoar - Charged Attack DMG: {4}
	ca = []float64{
		0.91332,
		0.98766,
		1.062,
		1.1682,
		1.24254,
		1.3275,
		1.44432,
		1.56114,
		1.67796,
		1.8054,
		1.93284,
		2.06028,
		2.18772,
		2.31516,
		2.4426,
	}
	// attack: EhecatlsRoar - Plunge DMG: {6} DEF
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: EhecatlsRoar - Low/High Plunge DMG: {7} DEF/{8} DEF
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: EhecatlsRoar - Low/High Plunge DMG: {7} DEF/{8} DEF
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	attackE = [][]float64{
		{ // attack: EhecatlsRoar - Blade Roller 1-Hit DMG: {9} DEF
			0.56022,
			0.60582,
			0.65142,
			0.71656,
			0.76216,
			0.81428,
			0.88593,
			0.95759,
			1.02924,
			1.10741,
			1.18558,
			1.26375,
			1.34193,
			1.4201,
			1.49827,
		},
		{ // attack: EhecatlsRoar - Blade Roller 2-Hit DMG: {10} DEF
			0.55048,
			0.59528,
			0.64009,
			0.7041,
			0.74891,
			0.80011,
			0.87052,
			0.94093,
			1.01134,
			1.08815,
			1.16496,
			1.24178,
			1.31859,
			1.3954,
			1.47221,
		},
		{ // attack: EhecatlsRoar - Blade Roller 3-Hit DMG: {11} DEF
			0.65816,
			0.71173,
			0.7653,
			0.84183,
			0.8954,
			0.95662,
			1.04081,
			1.12499,
			1.20917,
			1.30101,
			1.39285,
			1.48468,
			1.57652,
			1.66835,
			1.76019,
		},
		{ // attack: EhecatlsRoar - Blade Roller 4-Hit DMG: {12} DEF
			0.86027,
			0.9303,
			1.00032,
			1.10035,
			1.17037,
			1.2504,
			1.36044,
			1.47047,
			1.58051,
			1.70054,
			1.82058,
			1.94062,
			2.06066,
			2.1807,
			2.30074,
		},
	}
	// skill: YohualsScratch - Rush DMG: {0} DEF
	skillDMG = []float64{
		1.792,
		1.9264,
		2.0608,
		2.24,
		2.3744,
		2.5088,
		2.688,
		2.8672,
		3.0464,
		3.2256,
		3.4048,
		3.584,
		3.808,
		4.032,
		4.256,
	}
	// skill: YohualsScratch - Elemental RES Decrease: {1}
	skillShred = []float64{
		0.09,
		0.12,
		0.15,
		0.18,
		0.21,
		0.24,
		0.27,
		0.3,
		0.33,
		0.36,
		0.39,
		0.42,
		0.45,
		0.48,
		0.51,
	}
	// burst: OcelotlicuePoint - Skill DMG: {0} DEF
	burstDMG = []float64{
		2.8128,
		3.02376,
		3.23472,
		3.516,
		3.72696,
		3.93792,
		4.2192,
		4.50048,
		4.78176,
		5.06304,
		5.34432,
		5.6256,
		5.9772,
		6.3288,
		6.6804,
	}
	// burst: OcelotlicuePoint - Continuous Healing: {1} DEF+{2}
	burstHealPer = []float64{
		1.04,
		1.118,
		1.196,
		1.3,
		1.378,
		1.456,
		1.56,
		1.664,
		1.768,
		1.872,
		1.976,
		2.08,
		2.21,
		2.34,
		2.47,
	}
	// burst: OcelotlicuePoint - Continuous Healing: {1} DEF+{2}
	burstHealBase = []float64{
		500.7376,
		550.8184,
		605.0725,
		663.5,
		726.1009,
		792.8752,
		863.8229,
		938.944,
		1018.238,
		1101.706,
		1189.348,
		1281.162,
		1377.15,
		1477.312,
		1581.647,
	}
	// burst: OcelotlicuePoint - Follow-Up Beat DMG: {4} DEF
	burstFollowDMG = []float64{
		2.8128,
		3.02376,
		3.23472,
		3.516,
		3.72696,
		3.93792,
		4.2192,
		4.50048,
		4.78176,
		5.06304,
		5.34432,
		5.6256,
		5.9772,
		6.3288,
		6.6804,
	}
)
