// Code generated by "pipeline"; DO NOT EDIT.

package chiori

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Chiori, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Chiori, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	turretDuration = 17   // skill: FlutteringHasode - Tamoto Duration: {2}s
	turretInterval = 3.6  // skill: FlutteringHasode - Tamoto Attack Interval: {3}s
	burstCD        = 13.5 // burst: HiyokuTwinBlades - CD: {2}s
)

var (
	attack = [][][]float64{
		{{ // attack: WeavingBlade - 1-Hit DMG: {0}
			0.4941,
			0.53432,
			0.57454,
			0.63199,
			0.67221,
			0.71817,
			0.78137,
			0.84457,
			0.90777,
			0.97672,
			1.04566,
			1.11461,
			1.18355,
			1.2525,
			1.32144,
		}},
		{{ // attack: WeavingBlade - 2-Hit DMG: {1}
			0.46834,
			0.50646,
			0.54458,
			0.59904,
			0.63716,
			0.68072,
			0.74063,
			0.80053,
			0.86044,
			0.92579,
			0.99114,
			1.05649,
			1.12183,
			1.18718,
			1.25253,
		}},
		{
			{ // attack: WeavingBlade - 3-Hit DMG: {2}+{3}
				0.30417,
				0.32892,
				0.35368,
				0.38905,
				0.41381,
				0.4421,
				0.48101,
				0.51991,
				0.55881,
				0.60126,
				0.6437,
				0.68614,
				0.72858,
				0.77102,
				0.81346,
			},
			{ // attack: WeavingBlade - 3-Hit DMG: {2}+{3}
				0.30417,
				0.32892,
				0.35368,
				0.38905,
				0.41381,
				0.4421,
				0.48101,
				0.51991,
				0.55881,
				0.60126,
				0.6437,
				0.68614,
				0.72858,
				0.77102,
				0.81346,
			},
		},
		{{ // attack: WeavingBlade - 4-Hit DMG: {4}
			0.75123,
			0.81237,
			0.87352,
			0.96087,
			1.02202,
			1.0919,
			1.18799,
			1.28407,
			1.38016,
			1.48498,
			1.58981,
			1.69463,
			1.79945,
			1.90427,
			2.0091,
		}},
	}
	charge = [][]float64{
		{ // attack: WeavingBlade - Charged Attack DMG: {5}+{6}
			0.54309,
			0.58729,
			0.6315,
			0.69465,
			0.73886,
			0.78938,
			0.85884,
			0.9283,
			0.99777,
			1.07355,
			1.14933,
			1.22511,
			1.30089,
			1.37667,
			1.45245,
		},
		{ // attack: WeavingBlade - Charged Attack DMG: {5}+{6}
			0.54309,
			0.58729,
			0.6315,
			0.69465,
			0.73886,
			0.78938,
			0.85884,
			0.9283,
			0.99777,
			1.07355,
			1.14933,
			1.22511,
			1.30089,
			1.37667,
			1.45245,
		},
	}
	// attack: WeavingBlade - Plunge DMG: {8}
	plunge = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: WeavingBlade - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: WeavingBlade - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: FlutteringHasode - Tamoto DMG: {0} ATK+{1} DEF
	turretAtkScaling = []float64{
		0.8208,
		0.88236,
		0.94392,
		1.026,
		1.08756,
		1.14912,
		1.2312,
		1.31328,
		1.39536,
		1.47744,
		1.55952,
		1.6416,
		1.7442,
		1.8468,
		1.9494,
	}
	// skill: FlutteringHasode - Tamoto DMG: {0} ATK+{1} DEF
	turretDefScaling = []float64{
		1.026,
		1.10295,
		1.1799,
		1.2825,
		1.35945,
		1.4364,
		1.539,
		1.6416,
		1.7442,
		1.8468,
		1.9494,
		2.052,
		2.18025,
		2.3085,
		2.43675,
	}
	// skill: FlutteringHasode - Upward Sweep Attack DMG: {4} ATK+{5} DEF
	thrustAtkScaling = []float64{
		1.4928,
		1.60476,
		1.71672,
		1.866,
		1.97796,
		2.08992,
		2.2392,
		2.38848,
		2.53776,
		2.68704,
		2.83632,
		2.9856,
		3.1722,
		3.3588,
		3.5454,
	}
	// skill: FlutteringHasode - Upward Sweep Attack DMG: {4} ATK+{5} DEF
	thrustDefScaling = []float64{
		1.866,
		2.00595,
		2.1459,
		2.3325,
		2.47245,
		2.6124,
		2.799,
		2.9856,
		3.1722,
		3.3588,
		3.5454,
		3.732,
		3.96525,
		4.1985,
		4.43175,
	}
	// burst: HiyokuTwinBlades - Skill DMG: {0} ATK+{1} DEF
	burstAtkScaling = []float64{
		2.5632,
		2.75544,
		2.94768,
		3.204,
		3.39624,
		3.58848,
		3.8448,
		4.10112,
		4.35744,
		4.61376,
		4.87008,
		5.1264,
		5.4468,
		5.7672,
		6.0876,
	}
	// burst: HiyokuTwinBlades - Skill DMG: {0} ATK+{1} DEF
	burstDefScaling = []float64{
		3.204,
		3.4443,
		3.6846,
		4.005,
		4.2453,
		4.4856,
		4.806,
		5.1264,
		5.4468,
		5.7672,
		6.0876,
		6.408,
		6.8085,
		7.209,
		7.6095,
	}
)
