// Code generated by "pipeline"; DO NOT EDIT.

package furina

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Furina, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Furina, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SoloistsSolicitation - 1-Hit DMG: {0}
			0.48386,
			0.52325,
			0.56263,
			0.61889,
			0.65828,
			0.70329,
			0.76518,
			0.82707,
			0.88895,
			0.95647,
			1.02399,
			1.0915,
			1.15902,
			1.22653,
			1.29405,
		},
		{ // attack: SoloistsSolicitation - 2-Hit DMG: {1}
			0.43729,
			0.47289,
			0.50848,
			0.55933,
			0.59492,
			0.6356,
			0.69153,
			0.74747,
			0.8034,
			0.86442,
			0.92543,
			0.98645,
			1.04747,
			1.10849,
			1.1695,
		},
		{ // attack: SoloistsSolicitation - 3-Hit DMG: {2}
			0.5512,
			0.59606,
			0.64093,
			0.70502,
			0.74989,
			0.80116,
			0.87167,
			0.94217,
			1.01267,
			1.08958,
			1.16649,
			1.2434,
			1.32032,
			1.39723,
			1.47414,
		},
		{ // attack: SoloistsSolicitation - 4-Hit DMG: {3}
			0.73298,
			0.79264,
			0.8523,
			0.93753,
			0.99719,
			1.06537,
			1.15913,
			1.25288,
			1.34663,
			1.44891,
			1.55119,
			1.65346,
			1.75574,
			1.85801,
			1.96029,
		},
	}
	// attack: SoloistsSolicitation - Charged Attack DMG: {4}
	charge = []float64{
		0.74218,
		0.80259,
		0.863,
		0.9493,
		1.00971,
		1.07875,
		1.17368,
		1.26861,
		1.36354,
		1.4671,
		1.57066,
		1.67422,
		1.77778,
		1.88134,
		1.9849,
	}
	// attack: SoloistsSolicitation - Plunge DMG: {6}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: SoloistsSolicitation - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: SoloistsSolicitation - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// attack: SoloistsSolicitation - Spiritbreath Thorn/Surging Blade DMG: {9}
	arkhe = []float64{
		0.0946,
		0.1023,
		0.11,
		0.121,
		0.1287,
		0.1375,
		0.1496,
		0.1617,
		0.1738,
		0.187,
		0.2002,
		0.2134,
		0.2266,
		0.2398,
		0.253,
	}
	// skill: SalonSolitaire - Ousia Bubble DMG: {0} Max HP
	skillOusiaBubble = []float64{
		0.07864,
		0.08454,
		0.09044,
		0.0983,
		0.1042,
		0.1101,
		0.11796,
		0.12582,
		0.13369,
		0.14155,
		0.14942,
		0.15728,
		0.16711,
		0.17694,
		0.18677,
	}
	// skill: SalonSolitaire - Gentilhomme Usher DMG: {2} Max HP
	skillUsher = []float64{
		0.0596,
		0.06407,
		0.06854,
		0.0745,
		0.07897,
		0.08344,
		0.0894,
		0.09536,
		0.10132,
		0.10728,
		0.11324,
		0.1192,
		0.12665,
		0.1341,
		0.14155,
	}
	// skill: SalonSolitaire - Surintendante Chevalmarin DMG: {3} Max HP
	skillChevalmarin = []float64{
		0.03232,
		0.03474,
		0.03717,
		0.0404,
		0.04282,
		0.04525,
		0.04848,
		0.05171,
		0.05494,
		0.05818,
		0.06141,
		0.06464,
		0.06868,
		0.07272,
		0.07676,
	}
	// skill: SalonSolitaire - Mademoiselle Crabaletta DMG: {4} Max HP
	skillCrabaletta = []float64{
		0.08288,
		0.0891,
		0.09531,
		0.1036,
		0.10982,
		0.11603,
		0.12432,
		0.13261,
		0.1409,
		0.14918,
		0.15747,
		0.16576,
		0.17612,
		0.18648,
		0.19684,
	}
	// skill: SalonSolitaire - Singer of Many Waters Healing: {8} Max HP+{9}
	skillSingerHealScale = []float64{
		0.048,
		0.0516,
		0.0552,
		0.06,
		0.0636,
		0.0672,
		0.072,
		0.0768,
		0.0816,
		0.0864,
		0.0912,
		0.096,
		0.102,
		0.108,
		0.114,
	}
	// skill: SalonSolitaire - Singer of Many Waters Healing: {8} Max HP+{9}
	skillSingerHealFlat = []float64{
		462.2253,
		508.4543,
		558.5356,
		612.4694,
		670.2556,
		731.8942,
		797.3852,
		866.7286,
		939.9245,
		1016.973,
		1097.873,
		1182.626,
		1271.232,
		1363.69,
		1460.0,
	}
	// burst: LetThePeopleRejoice - Skill DMG: {0} Max HP
	burstDMG = []float64{
		0.11406,
		0.12262,
		0.13117,
		0.14258,
		0.15113,
		0.15969,
		0.1711,
		0.1825,
		0.19391,
		0.20531,
		0.21672,
		0.22813,
		0.24239,
		0.25664,
		0.2709,
	}
	// burst: LetThePeopleRejoice - Fanfare to DMG Increase Conversion Ratio: {4}
	burstFanfareDMGRatio = []float64{
		0.0007,
		0.0009,
		0.0011,
		0.0013,
		0.0015,
		0.0017,
		0.0019,
		0.0021,
		0.0023,
		0.0025,
		0.0027,
		0.0029,
		0.0031,
		0.0033,
		0.0035,
	}
	// burst: LetThePeopleRejoice - Fanfare to Incoming Healing Bonus Conversion Ratio: {5}
	burstFanfareHBRatio = []float64{
		0.0001,
		0.0002,
		0.0003,
		0.0004,
		0.0005,
		0.0006,
		0.0007,
		0.0008,
		0.0009,
		0.001,
		0.0011,
		0.0012,
		0.0013,
		0.0014,
		0.0015,
	}
)
