// Code generated by "pipeline"; DO NOT EDIT.

package vesna

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Vesna, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Vesna, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: VilaBladeDance - 1-Hit DMG: {0}
			0.4042,
			0.4371,
			0.47,
			0.517,
			0.5499,
			0.5875,
			0.6392,
			0.6909,
			0.7426,
			0.799,
			0.8554,
			0.9118,
			0.9682,
			1.0246,
			1.081,
		},
		{ // attack: VilaBladeDance - 2-Hit DMG: {1}
			0.48676,
			0.52638,
			0.566,
			0.6226,
			0.66222,
			0.7075,
			0.76976,
			0.83202,
			0.89428,
			0.9622,
			1.03012,
			1.09804,
			1.16596,
			1.23388,
			1.3018,
		},
		{ // attack: VilaBladeDance - 3-Hit DMG: {2}×2
			0.28079,
			0.30365,
			0.3265,
			0.35915,
			0.38201,
			0.40813,
			0.44404,
			0.47995,
			0.51587,
			0.55505,
			0.59423,
			0.63341,
			0.67259,
			0.71177,
			0.75095,
		},
		{ // attack: VilaBladeDance - 4-Hit DMG: {3}
			0.59168,
			0.63984,
			0.688,
			0.7568,
			0.80496,
			0.86,
			0.93568,
			1.01136,
			1.08704,
			1.1696,
			1.25216,
			1.33472,
			1.41728,
			1.49984,
			1.5824,
		},
		{ // attack: VilaBladeDance - 5-Hit DMG: {4}
			0.62436,
			0.67518,
			0.726,
			0.7986,
			0.84942,
			0.9075,
			0.98736,
			1.06722,
			1.14708,
			1.2342,
			1.32132,
			1.40844,
			1.49556,
			1.58268,
			1.6698,
		},
		{ // attack: VilaBladeDance - 6-Hit DMG: {5}
			0.7224,
			0.7812,
			0.84,
			0.924,
			0.9828,
			1.05,
			1.1424,
			1.2348,
			1.3272,
			1.428,
			1.5288,
			1.6296,
			1.7304,
			1.8312,
			1.932,
		},
	}
	// attack: VilaBladeDance - Charged Attack DMG: {6}
	charge = []float64{
		1.33042,
		1.43871,
		1.547,
		1.7017,
		1.80999,
		1.93375,
		2.10392,
		2.27409,
		2.44426,
		2.6299,
		2.81554,
		3.00118,
		3.18682,
		3.37246,
		3.5581,
	}
	// skill: TheArtOfVictory - Skill DMG: {0}
	skill = []float64{
		0.4,
		0.43,
		0.46,
		0.5,
		0.53,
		0.56,
		0.6,
		0.64,
		0.68,
		0.72,
		0.76,
		0.8,
		0.85,
		0.9,
		0.95,
	}
	skillSpecial = [][]float64{
		{ // skill: TheArtOfVictory - Windborne Sword Lv. 1 DMG: {1}
			0.4,
			0.43,
			0.46,
			0.5,
			0.53,
			0.56,
			0.6,
			0.64,
			0.68,
			0.72,
			0.76,
			0.8,
			0.85,
			0.9,
			0.95,
		},
		{ // skill: TheArtOfVictory - Windborne Sword Lv. 1 DMG: {1}
			0.4,
			0.43,
			0.46,
			0.5,
			0.53,
			0.56,
			0.6,
			0.64,
			0.68,
			0.72,
			0.76,
			0.8,
			0.85,
			0.9,
			0.95,
		},
		{ // skill: TheArtOfVictory - Windborne Sword Lv. 2 DMG: {2}
			0.6,
			0.645,
			0.69,
			0.75,
			0.795,
			0.84,
			0.9,
			0.96,
			1.02,
			1.08,
			1.14,
			1.2,
			1.275,
			1.35,
			1.425,
		},
		{ // skill: TheArtOfVictory - Windborne Sword Lv. 2 DMG: {2}
			0.6,
			0.645,
			0.69,
			0.75,
			0.795,
			0.84,
			0.9,
			0.96,
			1.02,
			1.08,
			1.14,
			1.2,
			1.275,
			1.35,
			1.425,
		},
	}
	// skill: TheArtOfVictory - Windborne Sword Lv. 2 Spirit Blade DMG: {3}
	skillSpirit2 = []float64{
		1.12,
		1.204,
		1.288,
		1.4,
		1.484,
		1.568,
		1.68,
		1.792,
		1.904,
		2.016,
		2.128,
		2.24,
		2.38,
		2.52,
		2.66,
	}
	// skill: TheArtOfVictory - Windborne Sword Lv. 3 Spirit Blade DMG: {5} ×4
	skillSpirit3DoT = []float64{
		0.448,
		0.4816,
		0.5152,
		0.56,
		0.5936,
		0.6272,
		0.672,
		0.7168,
		0.7616,
		0.8064,
		0.8512,
		0.896,
		0.952,
		1.008,
		1.064,
	}
	// skill: TheArtOfVictory - Windborne Sword Lv. 3 Spirit Blade Final Hit DMG: {7}
	skillSpirit3Final = []float64{
		1.568,
		1.6856,
		1.8032,
		1.96,
		2.0776,
		2.1952,
		2.352,
		2.5088,
		2.6656,
		2.8224,
		2.9792,
		3.136,
		3.332,
		3.528,
		3.724,
	}
	// skill: TheArtOfVictory - Wind Pinion DMG: {9}
	skillPinion = []float64{
		0.104,
		0.1118,
		0.1196,
		0.13,
		0.1378,
		0.1456,
		0.156,
		0.1664,
		0.1768,
		0.1872,
		0.1976,
		0.208,
		0.221,
		0.234,
		0.247,
	}
	// burst: ForTheTsaritsa - Spirit Blade DMG: {0}
	burst = []float64{
		2.632,
		2.8294,
		3.0268,
		3.29,
		3.4874,
		3.6848,
		3.948,
		4.2112,
		4.4744,
		4.7376,
		5.0008,
		5.264,
		5.593,
		5.922,
		6.251,
	}
)
