// Code generated by "pipeline"; DO NOT EDIT.

package clorinde

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Clorinde, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Clorinde, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	skillBOLGain          = 0.35 // skill: HuntersVigil - Swift Hunt Bond of Life Gain: {2} Max HP
	skillLungeLowBOLHeal  = 1.04 // skill: HuntersVigil - Impale the Night Healing: 0%/{5}/{7} Bond of Life
	skillLungeFullBOLHeal = 1.1  // skill: HuntersVigil - Impale the Night Healing: 0%/{5}/{7} Bond of Life
	healingBOL            = 0.8  // skill: HuntersVigil - Bond of Life Conversion: {8} Healing
	arkheCD               = 10   // skill: HuntersVigil - Surging Blade Interval: {10}s
	skillStateDuration    = 7.5  // skill: HuntersVigil - Night Vigil Duration: {11}s
	a1Duration            = 15   // a1: DarkShatteringFlame
	a1FlatDmg             = 1800 // a1: DarkShatteringFlame
	a1PercentBuff         = 0.2  // a1: DarkShatteringFlame
	a4CritBuff            = 0.1  // a4: LawfulRemuneration
	a4Duration            = 15   // a4: LawfulRemuneration
)

var (
	attack = [][][]float64{
		{{ // attack: OathOfHuntingShadows - 1-Hit DMG: {0}
			0.5406,
			0.5846,
			0.6286,
			0.69146,
			0.73546,
			0.78575,
			0.8549,
			0.92404,
			0.99319,
			1.06862,
			1.14405,
			1.21948,
			1.29492,
			1.37035,
			1.44578,
		}},
		{{ // attack: OathOfHuntingShadows - 2-Hit DMG: {1}
			0.51628,
			0.55831,
			0.60033,
			0.66036,
			0.70239,
			0.75041,
			0.81645,
			0.88248,
			0.94852,
			1.02056,
			1.0926,
			1.16464,
			1.23668,
			1.30872,
			1.38076,
		}},
		{
			{ // attack: OathOfHuntingShadows - 3-Hit DMG: {2}+{3}
				0.34185,
				0.36968,
				0.3975,
				0.43725,
				0.46507,
				0.49687,
				0.5406,
				0.58433,
				0.62805,
				0.67575,
				0.72345,
				0.77115,
				0.81885,
				0.86655,
				0.91425,
			},
			{ // attack: OathOfHuntingShadows - 3-Hit DMG: {2}+{3}
				0.34185,
				0.36968,
				0.3975,
				0.43725,
				0.46507,
				0.49687,
				0.5406,
				0.58433,
				0.62805,
				0.67575,
				0.72345,
				0.77115,
				0.81885,
				0.86655,
				0.91425,
			},
		},
		{
			{ // attack: OathOfHuntingShadows - 4-Hit DMG: {4}+{5}+{6}
				0.23134,
				0.25017,
				0.269,
				0.2959,
				0.31473,
				0.33625,
				0.36584,
				0.39543,
				0.42502,
				0.4573,
				0.48958,
				0.52186,
				0.55414,
				0.58642,
				0.6187,
			},
			{ // attack: OathOfHuntingShadows - 4-Hit DMG: {4}+{5}+{6}
				0.23134,
				0.25017,
				0.269,
				0.2959,
				0.31473,
				0.33625,
				0.36584,
				0.39543,
				0.42502,
				0.4573,
				0.48958,
				0.52186,
				0.55414,
				0.58642,
				0.6187,
			},
			{ // attack: OathOfHuntingShadows - 4-Hit DMG: {4}+{5}+{6}
				0.23134,
				0.25017,
				0.269,
				0.2959,
				0.31473,
				0.33625,
				0.36584,
				0.39543,
				0.42502,
				0.4573,
				0.48958,
				0.52186,
				0.55414,
				0.58642,
				0.6187,
			},
		},
		{{ // attack: OathOfHuntingShadows - 5-Hit DMG: {9}
			0.9001,
			0.97337,
			1.04663,
			1.15129,
			1.22456,
			1.30829,
			1.42342,
			1.53855,
			1.65367,
			1.77927,
			1.90487,
			2.03046,
			2.15606,
			2.28165,
			2.40725,
		}},
	}
	// attack: OathOfHuntingShadows - Charged Attack DMG: {10}
	charge = []float64{
		1.2814,
		1.3857,
		1.49,
		1.639,
		1.7433,
		1.8625,
		2.0264,
		2.1903,
		2.3542,
		2.533,
		2.7118,
		2.8906,
		3.0694,
		3.2482,
		3.427,
	}
	// attack: OathOfHuntingShadows - Plunge DMG: {12}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: OathOfHuntingShadows - Low/High Plunge DMG: {13}/{14}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: OathOfHuntingShadows - Low/High Plunge DMG: {13}/{14}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: HuntersVigil - Swift Hunt DMG: {0}/{1}
	skillNA = []float64{
		0.26763,
		0.28942,
		0.3112,
		0.34232,
		0.3641,
		0.389,
		0.42323,
		0.45746,
		0.4917,
		0.52904,
		0.56638,
		0.60373,
		0.64107,
		0.67842,
		0.71576,
	}
	// skill: HuntersVigil - Swift Hunt DMG: {0}/{1}
	skillEnhancedNA = []float64{
		0.38786,
		0.41943,
		0.451,
		0.4961,
		0.52767,
		0.56375,
		0.61336,
		0.66297,
		0.71258,
		0.7667,
		0.82082,
		0.87494,
		0.92906,
		0.98318,
		1.0373,
	}
	// skill: HuntersVigil - Impale the Night DMG: {3}/{4}/{6}×3
	skillLungeNoBOL = []float64{
		0.32972,
		0.35656,
		0.3834,
		0.42174,
		0.44858,
		0.47925,
		0.52142,
		0.5636,
		0.60577,
		0.65178,
		0.69779,
		0.7438,
		0.7898,
		0.83581,
		0.88182,
	}
	// skill: HuntersVigil - Impale the Night DMG: {3}/{4}/{6}×3
	skillLungeLowBOL = []float64{
		0.43963,
		0.47542,
		0.5112,
		0.56232,
		0.5981,
		0.639,
		0.69523,
		0.75146,
		0.8077,
		0.86904,
		0.93038,
		0.99173,
		1.05307,
		1.11442,
		1.17576,
	}
	// skill: HuntersVigil - Impale the Night DMG: {3}/{4}/{6}×3
	skillLungeFullBOL = []float64{
		0.25112,
		0.27156,
		0.292,
		0.3212,
		0.34164,
		0.365,
		0.39712,
		0.42924,
		0.46136,
		0.4964,
		0.53144,
		0.56648,
		0.60152,
		0.63656,
		0.6716,
	}
	// skill: HuntersVigil - Surging Blade DMG: {9}
	arkheDamage = []float64{
		0.432,
		0.4644,
		0.4968,
		0.54,
		0.5724,
		0.6048,
		0.648,
		0.6912,
		0.7344,
		0.7776,
		0.8208,
		0.864,
		0.918,
		0.972,
		1.026,
	}
	// burst: LastLightfall - Skill DMG: {0}×5
	burstDamage = []float64{
		1.2688,
		1.36396,
		1.45912,
		1.586,
		1.68116,
		1.77632,
		1.9032,
		2.03008,
		2.15696,
		2.28384,
		2.41072,
		2.5376,
		2.6962,
		2.8548,
		3.0134,
	}
	// burst: LastLightfall - Bond of Life Gain: {1} Max HP
	burstBOL = []float64{
		0.66,
		0.72,
		0.78,
		0.84,
		0.9,
		0.96,
		1.02,
		1.08,
		1.14,
		1.2,
		1.26,
		1.32,
		1.38,
		1.44,
		1.5,
	}
)
