// Code generated by "pipeline"; DO NOT EDIT.

package yaoyao

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Yaoyao, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Yaoyao, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: TossNTurnSpear - 1-Hit DMG: {0}
			0.51001,
			0.55153,
			0.59304,
			0.65234,
			0.69386,
			0.7413,
			0.80653,
			0.87177,
			0.937,
			1.00817,
			1.07933,
			1.1505,
			1.22166,
			1.29283,
			1.36399,
		}},
		{{ // attack: TossNTurnSpear - 2-Hit DMG: {1}
			0.47443,
			0.51304,
			0.55166,
			0.60683,
			0.64544,
			0.68958,
			0.75026,
			0.81094,
			0.87162,
			0.93782,
			1.00402,
			1.07022,
			1.13642,
			1.20262,
			1.26882,
		}},
		{
			{ // attack: TossNTurnSpear - 3-Hit DMG: {2}+{3}
				0.31377,
				0.33931,
				0.36485,
				0.40134,
				0.42687,
				0.45606,
				0.4962,
				0.53633,
				0.57646,
				0.62024,
				0.66403,
				0.70781,
				0.75159,
				0.79537,
				0.83916,
			},
			{ // attack: TossNTurnSpear - 3-Hit DMG: {2}+{3}
				0.32946,
				0.35627,
				0.38309,
				0.4214,
				0.44822,
				0.47886,
				0.521,
				0.56314,
				0.60528,
				0.65125,
				0.69722,
				0.74319,
				0.78917,
				0.83514,
				0.88111,
			},
		},
		{{ // attack: TossNTurnSpear - 4-Hit DMG: {4}
			0.77931,
			0.84275,
			0.90618,
			0.9968,
			1.06023,
			1.13273,
			1.2324,
			1.33209,
			1.43176,
			1.54051,
			1.64925,
			1.75799,
			1.86673,
			1.97547,
			2.08421,
		}},
	}
	// attack: TossNTurnSpear - Charged Attack DMG: {5}
	nc = []float64{
		1.1266,
		1.2183,
		1.31,
		1.441,
		1.5327,
		1.6375,
		1.7816,
		1.9257,
		2.0698,
		2.227,
		2.3842,
		2.5414,
		2.6986,
		2.8558,
		3.013,
	}
	// skill: RaphanusSkyCluster - White Jade Radish DMG: {0}
	skillRadishDMG = []float64{
		0.2992,
		0.32164,
		0.34408,
		0.374,
		0.39644,
		0.41888,
		0.4488,
		0.47872,
		0.50864,
		0.53856,
		0.56848,
		0.5984,
		0.6358,
		0.6732,
		0.7106,
	}
	skillRadishHealing = [][]float64{
		{ // skill: RaphanusSkyCluster - White Jade Radish Healing: {1} Max HP+{2}
			0.01714,
			0.01843,
			0.01971,
			0.02143,
			0.02271,
			0.024,
			0.02571,
			0.02743,
			0.02914,
			0.03086,
			0.03257,
			0.03429,
			0.03643,
			0.03857,
			0.04071,
		},
		{ // skill: RaphanusSkyCluster - White Jade Radish Healing: {1} Max HP+{2}
			165.0799,
			181.5902,
			199.4764,
			218.7383,
			239.3762,
			261.3899,
			284.7795,
			309.5449,
			335.6862,
			363.2033,
			392.0963,
			422.3652,
			454.0099,
			487.0305,
			521.4269,
		},
	}
	// burst: MoonjadeDescent - Adeptal Legacy White Jade Radish DMG: {0}
	burstRadishDMG = []float64{
		0.7216,
		0.77572,
		0.82984,
		0.902,
		0.95612,
		1.01024,
		1.0824,
		1.15456,
		1.22672,
		1.29888,
		1.37104,
		1.4432,
		1.5334,
		1.6236,
		1.7138,
	}
	burstRadishHealing = [][]float64{
		{ // burst: MoonjadeDescent - Adeptal Legacy White Jade Radish Healing: {1} Max HP+{2}
			0.02017,
			0.02168,
			0.02319,
			0.02521,
			0.02672,
			0.02823,
			0.03025,
			0.03227,
			0.03429,
			0.0363,
			0.03832,
			0.04034,
			0.04286,
			0.04538,
			0.0479,
		},
		{ // burst: MoonjadeDescent - Adeptal Legacy White Jade Radish Healing: {1} Max HP+{2}
			194.2123,
			213.6363,
			234.6788,
			257.3401,
			281.62,
			307.5186,
			335.0358,
			364.1717,
			394.9263,
			427.2995,
			461.2914,
			496.9019,
			534.1311,
			572.9789,
			613.4455,
		},
	}
	// burst: MoonjadeDescent - Skill DMG: {3}
	burstDMG = []float64{
		1.1456,
		1.23152,
		1.31744,
		1.432,
		1.51792,
		1.60384,
		1.7184,
		1.83296,
		1.94752,
		2.06208,
		2.17664,
		2.2912,
		2.4344,
		2.5776,
		2.7208,
	}
)
