// Code generated by "pipeline"; DO NOT EDIT.

package lanyan

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.LanYan, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.LanYan, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: BlackPheasantStridesOnWater - 1-Hit DMG: {0}
			0.4144,
			0.44548,
			0.47656,
			0.518,
			0.54908,
			0.58016,
			0.6216,
			0.66304,
			0.70448,
			0.74592,
			0.78736,
			0.8288,
			0.8806,
			0.9324,
			0.9842,
		}},
		{
			{ // attack: BlackPheasantStridesOnWater - 2-Hit DMG: {1}+{2}
				0.20412,
				0.21943,
				0.23474,
				0.25515,
				0.27046,
				0.28577,
				0.30618,
				0.32659,
				0.347,
				0.36742,
				0.38783,
				0.40824,
				0.43376,
				0.45927,
				0.48478,
			},
			{ // attack: BlackPheasantStridesOnWater - 2-Hit DMG: {1}+{2}
				0.24948,
				0.26819,
				0.2869,
				0.31185,
				0.33056,
				0.34927,
				0.37422,
				0.39917,
				0.42412,
				0.44906,
				0.47401,
				0.49896,
				0.53014,
				0.56133,
				0.59251,
			},
		},
		{
			{ // attack: BlackPheasantStridesOnWater - 3-Hit DMG: {3}+{4}
				0.2692,
				0.28939,
				0.30958,
				0.3365,
				0.35669,
				0.37688,
				0.4038,
				0.43072,
				0.45764,
				0.48456,
				0.51148,
				0.5384,
				0.57205,
				0.6057,
				0.63935,
			},
			{ // attack: BlackPheasantStridesOnWater - 3-Hit DMG: {3}+{4}
				0.2692,
				0.28939,
				0.30958,
				0.3365,
				0.35669,
				0.37688,
				0.4038,
				0.43072,
				0.45764,
				0.48456,
				0.51148,
				0.5384,
				0.57205,
				0.6057,
				0.63935,
			},
		},
		{{ // attack: BlackPheasantStridesOnWater - 4-Hit DMG: {5}
			0.6456,
			0.69402,
			0.74244,
			0.807,
			0.85542,
			0.90384,
			0.9684,
			1.03296,
			1.09752,
			1.16208,
			1.22664,
			1.2912,
			1.3719,
			1.4526,
			1.5333,
		}},
	}
	// attack: BlackPheasantStridesOnWater - Charged Attack DMG: {6}×3
	charge = []float64{
		0.3784,
		0.40678,
		0.43516,
		0.473,
		0.50138,
		0.52976,
		0.5676,
		0.60544,
		0.64328,
		0.68112,
		0.71896,
		0.7568,
		0.8041,
		0.8514,
		0.8987,
	}
	// attack: BlackPheasantStridesOnWater - Plunge DMG: {8}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: BlackPheasantStridesOnWater - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: BlackPheasantStridesOnWater - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: SwallowWispPinionDance - Feathermoon Ring DMG: {0}
	ring = []float64{
		0.96256,
		1.03475,
		1.10694,
		1.2032,
		1.27539,
		1.34758,
		1.44384,
		1.5401,
		1.63635,
		1.73261,
		1.82886,
		1.92512,
		2.04544,
		2.16576,
		2.28608,
	}
	// skill: SwallowWispPinionDance - Shield DMG Absorption: {1} ATK+{2}
	shieldAmt = []float64{
		2.7648,
		2.97216,
		3.17952,
		3.456,
		3.66336,
		3.87072,
		4.1472,
		4.42368,
		4.70016,
		4.97664,
		5.25312,
		5.5296,
		5.8752,
		6.2208,
		6.5664,
	}
	// skill: SwallowWispPinionDance - Shield DMG Absorption: {1} ATK+{2}
	shieldFlat = []float64{
		1155.563,
		1271.135,
		1396.339,
		1531.173,
		1675.638,
		1829.735,
		1993.462,
		2166.821,
		2349.811,
		2542.431,
		2744.683,
		2956.565,
		3178.079,
		3409.224,
		3650.0,
	}
	// burst: LustrousMoonrise - Skill DMG: {0}×3
	burst = []float64{
		2.41064,
		2.59144,
		2.77224,
		3.0133,
		3.1941,
		3.3749,
		3.61596,
		3.85702,
		4.09809,
		4.33915,
		4.58022,
		4.82128,
		5.12261,
		5.42394,
		5.72527,
	}
)
