// Code generated by "pipeline"; DO NOT EDIT.

package varesa

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Varesa, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Varesa, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: ByTheHorns - 1-Hit DMG: {0}
			0.46778,
			0.50287,
			0.53795,
			0.58473,
			0.61981,
			0.6549,
			0.70168,
			0.74845,
			0.79523,
			0.84201,
			0.88879,
			0.93557,
			0.99404,
			1.05251,
			1.11099,
		},
		{ // attack: ByTheHorns - 2-Hit DMG: {1}
			0.40028,
			0.4303,
			0.46032,
			0.50035,
			0.53037,
			0.56039,
			0.60042,
			0.64045,
			0.68048,
			0.7205,
			0.76053,
			0.80056,
			0.85059,
			0.90063,
			0.95066,
		},
		{ // attack: ByTheHorns - 3-Hit DMG: {2}
			0.56313,
			0.60536,
			0.6476,
			0.70391,
			0.74615,
			0.78838,
			0.84469,
			0.90101,
			0.95732,
			1.01363,
			1.06994,
			1.12626,
			1.19665,
			1.26704,
			1.33743,
		},
	}
	// attack: ByTheHorns - Charged Attack DMG: {3}
	charged = []float64{
		0.8928,
		0.95976,
		1.02672,
		1.116,
		1.18296,
		1.24992,
		1.3392,
		1.42848,
		1.51776,
		1.60704,
		1.69632,
		1.7856,
		1.8972,
		2.0088,
		2.1204,
	}
	// attack: ByTheHorns - Plunge DMG: {5}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: ByTheHorns - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: ByTheHorns - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	fieryAttack = [][]float64{
		{ // attack: ByTheHorns - Fiery Passion 1-Hit DMG: {8}
			0.54407,
			0.58488,
			0.62568,
			0.68009,
			0.72089,
			0.7617,
			0.81611,
			0.87051,
			0.92492,
			0.97933,
			1.03374,
			1.08814,
			1.15615,
			1.22416,
			1.29217,
		},
		{ // attack: ByTheHorns - Fiery Passion 2-Hit DMG: {9}
			0.52029,
			0.55931,
			0.59833,
			0.65036,
			0.68938,
			0.7284,
			0.78043,
			0.83246,
			0.88449,
			0.93652,
			0.98855,
			1.04058,
			1.10561,
			1.17065,
			1.23568,
		},
		{ // attack: ByTheHorns - Fiery Passion 3-Hit DMG: {10}
			0.73586,
			0.79105,
			0.84624,
			0.91983,
			0.97502,
			1.03021,
			1.1038,
			1.17738,
			1.25097,
			1.32456,
			1.39814,
			1.47173,
			1.56371,
			1.65569,
			1.74768,
		},
	}
	// attack: ByTheHorns - Fiery Passion Charged Attack DMG: {11}
	fieryCharged = []float64{
		0.9264,
		0.99588,
		1.06536,
		1.158,
		1.22748,
		1.29696,
		1.3896,
		1.48224,
		1.57488,
		1.66752,
		1.76016,
		1.8528,
		1.9686,
		2.0844,
		2.2002,
	}
	// attack: ByTheHorns - Fiery Passion Plunge DMG: {13}
	fieryCollision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: ByTheHorns - Fiery Passion Low/High Plunge DMG: {14}/{15}
	fieryLowPlunge = []float64{
		2.23716,
		2.41925,
		2.60135,
		2.86148,
		3.04358,
		3.25169,
		3.53783,
		3.82398,
		4.11013,
		4.42229,
		4.73446,
		5.04662,
		5.35878,
		5.67094,
		5.9831,
	}
	// attack: ByTheHorns - Fiery Passion Low/High Plunge DMG: {14}/{15}
	fieryHighPlunge = []float64{
		2.79433,
		3.02178,
		3.24922,
		3.57415,
		3.80159,
		4.06153,
		4.41895,
		4.77636,
		5.13378,
		5.52368,
		5.91359,
		6.3035,
		6.6934,
		7.08331,
		7.47322,
	}
	// skill: RidingTheNightRainbow - Rush DMG: {0}
	rush = []float64{
		0.7448,
		0.80066,
		0.85652,
		0.931,
		0.98686,
		1.04272,
		1.1172,
		1.19168,
		1.26616,
		1.34064,
		1.41512,
		1.4896,
		1.5827,
		1.6758,
		1.7689,
	}
	// skill: RidingTheNightRainbow - Fiery Passion Rush DMG: {1}
	fieryRush = []float64{
		1.064,
		1.1438,
		1.2236,
		1.33,
		1.4098,
		1.4896,
		1.596,
		1.7024,
		1.8088,
		1.9152,
		2.0216,
		2.128,
		2.261,
		2.394,
		2.527,
	}
	// burst: GuardianVent - Flying Kick DMG: {0}
	kick = []float64{
		3.4512,
		3.71004,
		3.96888,
		4.314,
		4.57284,
		4.83168,
		5.1768,
		5.52192,
		5.86704,
		6.21216,
		6.55728,
		6.9024,
		7.3338,
		7.7652,
		8.1966,
	}
	// burst: GuardianVent - Fiery Passion Flying Kick DMG: {1}
	fieryKick = []float64{
		5.752,
		6.1834,
		6.6148,
		7.19,
		7.6214,
		8.0528,
		8.628,
		9.2032,
		9.7784,
		10.3536,
		10.9288,
		11.504,
		12.223,
		12.942,
		13.661,
	}
	// burst: GuardianVent - Volcano Kablam DMG: {4}
	kablam = []float64{
		4.0264,
		4.32838,
		4.63036,
		5.033,
		5.33498,
		5.63696,
		6.0396,
		6.44224,
		6.84488,
		7.24752,
		7.65016,
		8.0528,
		8.5561,
		9.0594,
		9.5627,
	}
)
