// Code generated by "pipeline"; DO NOT EDIT.

package jahoda

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Jahoda, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
		action.ActionSkill:  {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Jahoda, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: StrikeWhileTheArrowsHot - 1-Hit DMG: {0}
			0.41674,
			0.45066,
			0.48458,
			0.53304,
			0.56696,
			0.60572,
			0.65903,
			0.71233,
			0.76564,
			0.82379,
			0.88194,
			0.94008,
			0.99823,
			1.05638,
			1.11453,
		}},
		{
			{ // attack: StrikeWhileTheArrowsHot - 2-Hit DMG: {1}×2
				0.19231,
				0.20797,
				0.22362,
				0.24598,
				0.26164,
				0.27953,
				0.30412,
				0.32872,
				0.35332,
				0.38015,
				0.40699,
				0.43382,
				0.46066,
				0.48749,
				0.51433,
			},
			{ // attack: StrikeWhileTheArrowsHot - 2-Hit DMG: {1}×2
				0.19231,
				0.20797,
				0.22362,
				0.24598,
				0.26164,
				0.27953,
				0.30412,
				0.32872,
				0.35332,
				0.38015,
				0.40699,
				0.43382,
				0.46066,
				0.48749,
				0.51433,
			},
		},
		{{ // attack: StrikeWhileTheArrowsHot - 3-Hit DMG: {2}
			0.51197,
			0.55365,
			0.59532,
			0.65485,
			0.69652,
			0.74415,
			0.80963,
			0.87512,
			0.94061,
			1.01204,
			1.08348,
			1.15492,
			1.22636,
			1.2978,
			1.36924,
		}},
	}
	// attack: StrikeWhileTheArrowsHot - Aimed Shot: {3}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: StrikeWhileTheArrowsHot - Fully-Charged Aimed Shot: {4}
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// skill: SavvyStrategySplittingTheSpoils - Unfilled Treasure Flask DMG: {1}
	unfilledFlask = []float64{
		1.908,
		2.0511,
		2.1942,
		2.385,
		2.5281,
		2.6712,
		2.862,
		3.0528,
		3.2436,
		3.4344,
		3.6252,
		3.816,
		4.0545,
		4.293,
		4.5315,
	}
	// skill: SavvyStrategySplittingTheSpoils - Filled Treasure Flask DMG: {2}
	filledFlask = []float64{
		2.12,
		2.279,
		2.438,
		2.65,
		2.809,
		2.968,
		3.18,
		3.392,
		3.604,
		3.816,
		4.028,
		4.24,
		4.505,
		4.77,
		5.035,
	}
	// skill: SavvyStrategySplittingTheSpoils - Meowball DMG: {4}
	meowball = []float64{
		1.28,
		1.376,
		1.472,
		1.6,
		1.696,
		1.792,
		1.92,
		2.048,
		2.176,
		2.304,
		2.432,
		2.56,
		2.72,
		2.88,
		3.04,
	}
	// burst: HiddenAcesSevenToolsOfTheHunter - Skill DMG: {0}
	burst = []float64{
		2.072,
		2.2274,
		2.3828,
		2.59,
		2.7454,
		2.9008,
		3.108,
		3.3152,
		3.5224,
		3.7296,
		3.9368,
		4.144,
		4.403,
		4.662,
		4.921,
	}
	// burst: HiddenAcesSevenToolsOfTheHunter - Purrsonal Coordinated Assistance Robot DMG: {1}
	burstSkill = []float64{
		0.17266,
		0.18561,
		0.19856,
		0.21583,
		0.22878,
		0.24173,
		0.259,
		0.27626,
		0.29353,
		0.3108,
		0.32806,
		0.34533,
		0.36691,
		0.38849,
		0.41008,
	}
	// burst: HiddenAcesSevenToolsOfTheHunter - Purrsonal Coordinated Assistance Robot Healing: {3} ATK+{4}
	burstHealPP = []float64{
		0.79872,
		0.85862,
		0.91853,
		0.9984,
		1.0583,
		1.11821,
		1.19808,
		1.27795,
		1.35782,
		1.4377,
		1.51757,
		1.59744,
		1.69728,
		1.79712,
		1.89696,
	}
	// burst: HiddenAcesSevenToolsOfTheHunter - Purrsonal Coordinated Assistance Robot Healing: {3} ATK+{4}
	burstHealFlat = []float64{
		500.7376,
		550.8184,
		605.0725,
		663.5,
		726.1009,
		792.8752,
		863.8229,
		938.944,
		1018.238,
		1101.706,
		1189.348,
		1281.162,
		1377.15,
		1477.312,
		1581.647,
	}
	// burst: HiddenAcesSevenToolsOfTheHunter - Lowest HP Character Additional Healing: {5} ATK+{6}
	burstAdditionalHealPP = []float64{
		0.3072,
		0.33024,
		0.35328,
		0.384,
		0.40704,
		0.43008,
		0.4608,
		0.49152,
		0.52224,
		0.55296,
		0.58368,
		0.6144,
		0.6528,
		0.6912,
		0.7296,
	}
	// burst: HiddenAcesSevenToolsOfTheHunter - Lowest HP Character Additional Healing: {5} ATK+{6}
	burstAdditionalHealFlat = []float64{
		192.5972,
		211.8596,
		232.7272,
		255.2,
		279.278,
		304.9612,
		332.2496,
		361.1432,
		391.642,
		423.746,
		457.4552,
		492.7696,
		529.6892,
		568.214,
		608.3439,
	}
)
