// Code generated by "pipeline"; DO NOT EDIT.

package kuki

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.KukiShinobu, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.KukiShinobu, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][]float64{
		{ // attack: ShinobusShadowsword - 1-Hit DMG: {0}
			0.48762,
			0.52731,
			0.567,
			0.6237,
			0.66339,
			0.70875,
			0.77112,
			0.83349,
			0.89586,
			0.9639,
			1.03194,
			1.09998,
			1.16802,
			1.23606,
			1.3041,
		},
		{ // attack: ShinobusShadowsword - 2-Hit DMG: {1}
			0.44548,
			0.48174,
			0.518,
			0.5698,
			0.60606,
			0.6475,
			0.70448,
			0.76146,
			0.81844,
			0.8806,
			0.94276,
			1.00492,
			1.06708,
			1.12924,
			1.1914,
		},
		{ // attack: ShinobusShadowsword - 3-Hit DMG: {2}
			0.5934,
			0.6417,
			0.69,
			0.759,
			0.8073,
			0.8625,
			0.9384,
			1.0143,
			1.0902,
			1.173,
			1.2558,
			1.3386,
			1.4214,
			1.5042,
			1.587,
		},
		{ // attack: ShinobusShadowsword - 4-Hit DMG: {3}
			0.7611,
			0.82305,
			0.885,
			0.9735,
			1.03545,
			1.10625,
			1.2036,
			1.30095,
			1.3983,
			1.5045,
			1.6107,
			1.7169,
			1.8231,
			1.9293,
			2.0355,
		},
	}
	charge = [][]float64{
		{ // attack: ShinobusShadowsword - Charged Attack DMG: {4}+{5}
			0.55633,
			0.60162,
			0.6469,
			0.71159,
			0.75687,
			0.80862,
			0.87978,
			0.95094,
			1.0221,
			1.09973,
			1.17736,
			1.25499,
			1.33261,
			1.41024,
			1.48787,
		},
		{ // attack: ShinobusShadowsword - Charged Attack DMG: {4}+{5}
			0.66765,
			0.722,
			0.77634,
			0.85397,
			0.90832,
			0.97043,
			1.05582,
			1.14122,
			1.22662,
			1.31978,
			1.41294,
			1.5061,
			1.59926,
			1.69242,
			1.78558,
		},
	}
	// skill: SanctifyingRing - Skill DMG: {0}
	skill = []float64{
		0.75712,
		0.8139,
		0.87069,
		0.9464,
		1.00318,
		1.05997,
		1.13568,
		1.21139,
		1.2871,
		1.36282,
		1.43853,
		1.51424,
		1.60888,
		1.70352,
		1.79816,
	}
	// skill: SanctifyingRing - Grass Ring of Sanctification Healing: {1} Max HP+{2}
	skillhealpp = []float64{
		0.03,
		0.03225,
		0.0345,
		0.0375,
		0.03975,
		0.042,
		0.045,
		0.048,
		0.051,
		0.054,
		0.057,
		0.06,
		0.06375,
		0.0675,
		0.07125,
	}
	// skill: SanctifyingRing - Grass Ring of Sanctification Healing: {1} Max HP+{2}
	skillhealflat = []float64{
		288.8908,
		317.7839,
		349.0848,
		382.7934,
		418.9098,
		457.4339,
		498.3658,
		541.7054,
		587.4528,
		635.608,
		686.1709,
		739.1415,
		794.52,
		852.3062,
		912.5001,
	}
	// skill: SanctifyingRing - Grass Ring of Sanctification DMG: {3}
	skilldot = []float64{
		0.2524,
		0.27133,
		0.29026,
		0.3155,
		0.33443,
		0.35336,
		0.3786,
		0.40384,
		0.42908,
		0.45432,
		0.47956,
		0.5048,
		0.53635,
		0.5679,
		0.59945,
	}
	// burst: GyoeiNarukamiKariyamaRite - Single Instance DMG: {0} Max HP
	burst = []float64{
		0.03605,
		0.03875,
		0.04146,
		0.04506,
		0.04776,
		0.05047,
		0.05407,
		0.05768,
		0.06128,
		0.06489,
		0.06849,
		0.0721,
		0.0766,
		0.08111,
		0.08561,
	}
)
