// Code generated by "pipeline"; DO NOT EDIT.

package columbina

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Columbina, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Columbina, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: MoondewCascade - 1-Hit DMG: {0}
			0.46792,
			0.50301,
			0.53811,
			0.5849,
			0.61999,
			0.65509,
			0.70188,
			0.74867,
			0.79546,
			0.84226,
			0.88905,
			0.93584,
			0.99433,
			1.05282,
			1.11131,
		},
		{ // attack: MoondewCascade - 2-Hit DMG: {1}
			0.36626,
			0.39373,
			0.42119,
			0.45782,
			0.48529,
			0.51276,
			0.54938,
			0.58601,
			0.62264,
			0.65926,
			0.69589,
			0.73251,
			0.77829,
			0.82408,
			0.86986,
		},
		{ // attack: MoondewCascade - 3-Hit DMG: {2}
			0.58484,
			0.6287,
			0.67257,
			0.73105,
			0.77491,
			0.81878,
			0.87726,
			0.93574,
			0.99423,
			1.05271,
			1.1112,
			1.16968,
			1.24278,
			1.31589,
			1.389,
		},
	}
	// attack: MoondewCascade - Charged Attack DMG: {3}
	charge = []float64{
		1.1608,
		1.24786,
		1.33492,
		1.451,
		1.53806,
		1.62512,
		1.7412,
		1.85728,
		1.97336,
		2.08944,
		2.20552,
		2.3216,
		2.4667,
		2.6118,
		2.7569,
	}
	// attack: MoondewCascade - Moondew Cleanse DMG: {5} Max HP ×3
	chargeLB = []float64{
		0.01511,
		0.01625,
		0.01738,
		0.01889,
		0.02002,
		0.02116,
		0.02267,
		0.02418,
		0.02569,
		0.0272,
		0.02871,
		0.03022,
		0.03211,
		0.034,
		0.03589,
	}
	// skill: EternalTides - Skill DMG: {0} Max HP
	skill = []float64{
		0.1672,
		0.17974,
		0.19228,
		0.209,
		0.22154,
		0.23408,
		0.2508,
		0.26752,
		0.28424,
		0.30096,
		0.31768,
		0.3344,
		0.3553,
		0.3762,
		0.3971,
	}
	// skill: EternalTides - Gravity Ripple: Continuous DMG: {1} Max HP
	skillDoT = []float64{
		0.0936,
		0.10062,
		0.10764,
		0.117,
		0.12402,
		0.13104,
		0.1404,
		0.14976,
		0.15912,
		0.16848,
		0.17784,
		0.1872,
		0.1989,
		0.2106,
		0.2223,
	}
	// skill: EternalTides - Gravity Interference: Lunar-Charged DMG: {2} Max HP
	skillLC = []float64{
		0.04704,
		0.05057,
		0.0541,
		0.0588,
		0.06233,
		0.06586,
		0.07056,
		0.07526,
		0.07997,
		0.08467,
		0.08938,
		0.09408,
		0.09996,
		0.10584,
		0.11172,
	}
	// skill: EternalTides - Gravity Interference: Lunar-Bloom DMG: {3} Max HP ×5
	skillLB = []float64{
		0.01408,
		0.01514,
		0.01619,
		0.0176,
		0.01866,
		0.01971,
		0.02112,
		0.02253,
		0.02394,
		0.02534,
		0.02675,
		0.02816,
		0.02992,
		0.03168,
		0.03344,
	}
	// skill: EternalTides - Gravity Interference: Lunar-Crystallize DMG: {4} Max HP
	skillLCr = []float64{
		0.08824,
		0.09486,
		0.10148,
		0.1103,
		0.11692,
		0.12354,
		0.13236,
		0.14118,
		0.15001,
		0.15883,
		0.16766,
		0.17648,
		0.18751,
		0.19854,
		0.20957,
	}
	// burst: MoonlitMelancholy - Skill DMG: {0} Max HP
	burst = []float64{
		0.3224,
		0.34658,
		0.37076,
		0.403,
		0.42718,
		0.45136,
		0.4836,
		0.51584,
		0.54808,
		0.58032,
		0.61256,
		0.6448,
		0.6851,
		0.7254,
		0.7657,
	}
	// burst: MoonlitMelancholy - Lunar Reaction DMG Bonus: {1}
	burstBuff = []float64{
		0.13,
		0.16,
		0.19,
		0.22,
		0.25,
		0.28,
		0.31,
		0.34,
		0.37,
		0.4,
		0.43,
		0.46,
		0.49,
		0.52,
		0.55,
	}
)
