// Code generated by "pipeline"; DO NOT EDIT.

package nilou

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Nilou, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Nilou, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][]float64{
		{ // attack: DanceOfSamser - 1-Hit DMG: {0}
			0.50307,
			0.54402,
			0.58497,
			0.64347,
			0.68441,
			0.73121,
			0.79556,
			0.85991,
			0.92425,
			0.99445,
			1.06465,
			1.13484,
			1.20504,
			1.27524,
			1.34543,
		},
		{ // attack: DanceOfSamser - 2-Hit DMG: {1}
			0.45439,
			0.49137,
			0.52836,
			0.5812,
			0.61818,
			0.66045,
			0.71857,
			0.77669,
			0.83481,
			0.89821,
			0.96162,
			1.02502,
			1.08842,
			1.15182,
			1.21523,
		},
		{ // attack: DanceOfSamser - 3-Hit DMG: {2}
			0.70354,
			0.76081,
			0.81807,
			0.89988,
			0.95714,
			1.02259,
			1.11258,
			1.20256,
			1.29255,
			1.39072,
			1.48889,
			1.58706,
			1.68522,
			1.78339,
			1.88156,
		},
	}
	charge = [][]float64{
		{ // attack: DanceOfSamser - Charged Attack DMG: {3}+{4}
			0.50224,
			0.54312,
			0.584,
			0.6424,
			0.68328,
			0.73,
			0.79424,
			0.85848,
			0.92272,
			0.9928,
			1.06288,
			1.13296,
			1.20304,
			1.27312,
			1.3432,
		},
		{ // attack: DanceOfSamser - Charged Attack DMG: {3}+{4}
			0.54438,
			0.58869,
			0.633,
			0.6963,
			0.74061,
			0.79125,
			0.86088,
			0.93051,
			1.00014,
			1.0761,
			1.15206,
			1.22802,
			1.30398,
			1.37994,
			1.4559,
		},
	}
	// skill: DanceOfHaftkarsvar - Skill DMG: {0} Max HP
	skill = []float64{
		0.03339,
		0.03589,
		0.0384,
		0.04174,
		0.04424,
		0.04674,
		0.05008,
		0.05342,
		0.05676,
		0.0601,
		0.06344,
		0.06678,
		0.07095,
		0.07513,
		0.0793,
	}
	whirlingSteps = [][]float64{
		{ // skill: DanceOfHaftkarsvar - Sword Dance/Whirling Steps 1-Hit DMG: {5}/{1} Max HP
			0.03262,
			0.03507,
			0.03751,
			0.04077,
			0.04322,
			0.04567,
			0.04893,
			0.05219,
			0.05545,
			0.05872,
			0.06198,
			0.06524,
			0.06932,
			0.07339,
			0.07747,
		},
		{ // skill: DanceOfHaftkarsvar - Sword Dance/Whirling Steps 2-Hit DMG: {6}/{2} Max HP
			0.0396,
			0.04258,
			0.04555,
			0.04951,
			0.05248,
			0.05545,
			0.05941,
			0.06337,
			0.06733,
			0.07129,
			0.07525,
			0.07921,
			0.08416,
			0.08911,
			0.09406,
		},
		{ // skill: DanceOfHaftkarsvar - Luminous Illusion/Water Wheel DMG: {3}/{4} Max HP
			0.05062,
			0.05441,
			0.05821,
			0.06327,
			0.06707,
			0.07086,
			0.07592,
			0.08099,
			0.08605,
			0.09111,
			0.09617,
			0.10123,
			0.10756,
			0.11389,
			0.12021,
		},
	}
	swordDance = [][]float64{
		{ // skill: DanceOfHaftkarsvar - Sword Dance/Whirling Steps 1-Hit DMG: {5}/{1} Max HP
			0.04552,
			0.04894,
			0.05235,
			0.05691,
			0.06032,
			0.06374,
			0.06829,
			0.07284,
			0.07739,
			0.08195,
			0.0865,
			0.09105,
			0.09674,
			0.10243,
			0.10812,
		},
		{ // skill: DanceOfHaftkarsvar - Sword Dance/Whirling Steps 2-Hit DMG: {6}/{2} Max HP
			0.05144,
			0.0553,
			0.05916,
			0.06431,
			0.06816,
			0.07202,
			0.07717,
			0.08231,
			0.08746,
			0.0926,
			0.09775,
			0.10289,
			0.10932,
			0.11575,
			0.12218,
		},
		{ // skill: DanceOfHaftkarsvar - Luminous Illusion/Water Wheel DMG: {3}/{4} Max HP
			0.07169,
			0.07706,
			0.08244,
			0.08961,
			0.09499,
			0.10036,
			0.10753,
			0.1147,
			0.12187,
			0.12904,
			0.13621,
			0.14338,
			0.15234,
			0.1613,
			0.17026,
		},
	}
	// burst: DanceOfAbzendegiDistantDreamsListeningSpring - Skill DMG: {0} Max HP
	burst = []float64{
		0.18432,
		0.19814,
		0.21197,
		0.2304,
		0.24422,
		0.25805,
		0.27648,
		0.29491,
		0.31334,
		0.33178,
		0.35021,
		0.36864,
		0.39168,
		0.41472,
		0.43776,
	}
	// burst: DanceOfAbzendegiDistantDreamsListeningSpring - Lingering Aeon DMG: {1} Max HP
	burstAeon = []float64{
		0.22528,
		0.24218,
		0.25907,
		0.2816,
		0.2985,
		0.31539,
		0.33792,
		0.36045,
		0.38298,
		0.4055,
		0.42803,
		0.45056,
		0.47872,
		0.50688,
		0.53504,
	}
)
