// Code generated by "pipeline"; DO NOT EDIT.

package zhongli

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Zhongli, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold", "hold_nostele"},
	}
	validation.RegisterCharParamValidationFunc(keys.Zhongli, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: RainOfStone - 1-Hit DMG: {0}
			0.30769,
			0.33274,
			0.35778,
			0.39356,
			0.4186,
			0.44723,
			0.48658,
			0.52594,
			0.56529,
			0.60823,
			0.65742,
			0.71527,
			0.77313,
			0.83098,
			0.89409,
		},
		{ // attack: RainOfStone - 2-Hit DMG: {1}
			0.31152,
			0.33687,
			0.36223,
			0.39845,
			0.42381,
			0.45279,
			0.49263,
			0.53248,
			0.57232,
			0.61579,
			0.6656,
			0.72417,
			0.78274,
			0.84131,
			0.90521,
		},
		{ // attack: RainOfStone - 3-Hit DMG: {2}
			0.38576,
			0.41716,
			0.44856,
			0.49342,
			0.52482,
			0.5607,
			0.61004,
			0.65938,
			0.70872,
			0.76255,
			0.82423,
			0.89676,
			0.96929,
			1.04183,
			1.12095,
		},
		{ // attack: RainOfStone - 4-Hit DMG: {3}
			0.42939,
			0.46434,
			0.49929,
			0.54922,
			0.58417,
			0.62411,
			0.67903,
			0.73396,
			0.78888,
			0.84879,
			0.91745,
			0.99818,
			1.07892,
			1.15965,
			1.24773,
		},
		{ // attack: RainOfStone - 5-Hit DMG: {4}×4
			0.1075,
			0.11625,
			0.125,
			0.1375,
			0.14625,
			0.15625,
			0.17,
			0.18375,
			0.1975,
			0.2125,
			0.22969,
			0.2499,
			0.27011,
			0.29032,
			0.31238,
		},
		{ // attack: RainOfStone - 6-Hit DMG: {5}
			0.54497,
			0.58932,
			0.63368,
			0.69705,
			0.74141,
			0.7921,
			0.86181,
			0.93151,
			1.00121,
			1.07726,
			1.16439,
			1.26685,
			1.36932,
			1.47178,
			1.58357,
		},
	}
	// attack: RainOfStone - Charged Attack DMG: {6}
	charge = []float64{
		1.11026,
		1.20063,
		1.291,
		1.4201,
		1.51047,
		1.61375,
		1.75576,
		1.89777,
		2.03978,
		2.1947,
		2.37221,
		2.58097,
		2.78972,
		2.99848,
		3.22621,
	}
	// skill: DominusLapidis - Stone Stele/Resonance DMG: {0}/{1}
	skill = []float64{
		0.16,
		0.172,
		0.184,
		0.2,
		0.212,
		0.224,
		0.24,
		0.256,
		0.272,
		0.288,
		0.304,
		0.32,
		0.34,
		0.36,
		0.38,
	}
	// skill: DominusLapidis - Stone Stele/Resonance DMG: {0}/{1}
	skillTick = []float64{
		0.32,
		0.344,
		0.368,
		0.4,
		0.424,
		0.448,
		0.48,
		0.512,
		0.544,
		0.576,
		0.608,
		0.64,
		0.68,
		0.72,
		0.76,
	}
	// skill: DominusLapidis - Hold DMG: {3}
	skillHold = []float64{
		0.8,
		0.86,
		0.92,
		1.0,
		1.06,
		1.12,
		1.2,
		1.28,
		1.36,
		1.44,
		1.52,
		1.6,
		1.7,
		1.8,
		1.9,
	}
	// skill: DominusLapidis - Shield Base Absorption: {4}
	shieldBase = []float64{
		1232.411,
		1355.669,
		1489.199,
		1633.0,
		1787.073,
		1951.417,
		2126.033,
		2310.92,
		2506.079,
		2711.509,
		2927.211,
		3153.185,
		3389.429,
		3635.946,
		3892.734,
	}
	// skill: DominusLapidis - Additional Shield Absorption: {5} Max HP
	shieldPer = []float64{
		0.128,
		0.1376,
		0.1472,
		0.16,
		0.1696,
		0.1792,
		0.192,
		0.2048,
		0.2176,
		0.2304,
		0.2432,
		0.256,
		0.272,
		0.288,
		0.304,
	}
	// burst: PlanetBefall - Skill DMG: {0}
	burst = []float64{
		4.0108,
		4.4444,
		4.878,
		5.42,
		5.9078,
		6.3956,
		7.046,
		7.6964,
		8.3468,
		8.9972,
		9.6476,
		10.298,
		10.84,
		11.382,
		11.924,
	}
)
