// Code generated by "pipeline"; DO NOT EDIT.

package lisa

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Lisa, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Lisa, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: LightningTouch - 1-Hit DMG: {0}
			0.396,
			0.4257,
			0.4554,
			0.495,
			0.5247,
			0.5544,
			0.594,
			0.6336,
			0.6732,
			0.7128,
			0.75398,
			0.80784,
			0.8617,
			0.91555,
			0.96941,
		},
		{ // attack: LightningTouch - 2-Hit DMG: {1}
			0.3592,
			0.38614,
			0.41308,
			0.449,
			0.47594,
			0.50288,
			0.5388,
			0.57472,
			0.61064,
			0.64656,
			0.68392,
			0.73277,
			0.78162,
			0.83047,
			0.87932,
		},
		{ // attack: LightningTouch - 3-Hit DMG: {2}
			0.428,
			0.4601,
			0.4922,
			0.535,
			0.5671,
			0.5992,
			0.642,
			0.6848,
			0.7276,
			0.7704,
			0.81491,
			0.87312,
			0.93133,
			0.98954,
			1.04774,
		},
		{ // attack: LightningTouch - 4-Hit DMG: {3}
			0.5496,
			0.59082,
			0.63204,
			0.687,
			0.72822,
			0.76944,
			0.8244,
			0.87936,
			0.93432,
			0.98928,
			1.04644,
			1.12118,
			1.19593,
			1.27067,
			1.34542,
		},
	}
	// attack: LightningTouch - Charged Attack DMG: {4}
	charge = []float64{
		1.7712,
		1.90404,
		2.03688,
		2.214,
		2.34684,
		2.47968,
		2.6568,
		2.83392,
		3.01104,
		3.18816,
		3.37236,
		3.61325,
		3.85413,
		4.09501,
		4.3359,
	}
	// attack: LightningTouch - Plunge DMG: {6}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: LightningTouch - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: LightningTouch - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	skillHold = [][]float64{
		{ // skill: VioletArc - Non-Conductive Hold DMG: {0}
			3.2,
			3.44,
			3.68,
			4.0,
			4.24,
			4.48,
			4.8,
			5.12,
			5.44,
			5.76,
			6.08,
			6.4,
			6.8,
			7.2,
			7.6,
		},
		{ // skill: VioletArc - Stack 1 Conductive Hold DMG: {1}
			3.68,
			3.956,
			4.232,
			4.6,
			4.876,
			5.152,
			5.52,
			5.888,
			6.256,
			6.624,
			6.992,
			7.36,
			7.82,
			8.28,
			8.74,
		},
		{ // skill: VioletArc - Stack 2 Conductive Hold DMG: {2}
			4.24,
			4.558,
			4.876,
			5.3,
			5.618,
			5.936,
			6.36,
			6.784,
			7.208,
			7.632,
			8.056,
			8.48,
			9.01,
			9.54,
			10.07,
		},
		{ // skill: VioletArc - Stack 3 Conductive Hold DMG: {3}
			4.872,
			5.2374,
			5.6028,
			6.09,
			6.4554,
			6.8208,
			7.308,
			7.7952,
			8.2824,
			8.7696,
			9.2568,
			9.744,
			10.353,
			10.962,
			11.571,
		},
	}
	// skill: VioletArc - Press DMG: {5}
	skillPress = []float64{
		0.8,
		0.86,
		0.92,
		1.0,
		1.06,
		1.12,
		1.2,
		1.28,
		1.36,
		1.44,
		1.52,
		1.6,
		1.7,
		1.8,
		1.9,
	}
	// burst: LightningRose - Discharge DMG: {0}
	burst = []float64{
		0.3656,
		0.39302,
		0.42044,
		0.457,
		0.48442,
		0.51184,
		0.5484,
		0.58496,
		0.62152,
		0.65808,
		0.69464,
		0.7312,
		0.7769,
		0.8226,
		0.8683,
	}
)
