// Code generated by "pipeline"; DO NOT EDIT.

package candace

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Candace, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold", "perfect"},
	}
	validation.RegisterCharParamValidationFunc(keys.Candace, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: GleamingSpearGuardianStance - 1-Hit DMG: {0}
			0.60802,
			0.65751,
			0.707,
			0.7777,
			0.82719,
			0.88375,
			0.96152,
			1.03929,
			1.11706,
			1.2019,
			1.28674,
			1.37158,
			1.45642,
			1.54126,
			1.6261,
		}},
		{{ // attack: GleamingSpearGuardianStance - 2-Hit DMG: {1}
			0.61146,
			0.66123,
			0.711,
			0.7821,
			0.83187,
			0.88875,
			0.96696,
			1.04517,
			1.12338,
			1.2087,
			1.29402,
			1.37934,
			1.46466,
			1.54998,
			1.6353,
		}},
		{
			{ // attack: GleamingSpearGuardianStance - 3-Hit DMG: {2}+{3}
				0.35488,
				0.38377,
				0.41265,
				0.45391,
				0.4828,
				0.51581,
				0.5612,
				0.6066,
				0.65199,
				0.70151,
				0.75102,
				0.80054,
				0.85006,
				0.89958,
				0.9491,
			},
			{ // attack: GleamingSpearGuardianStance - 3-Hit DMG: {2}+{3}
				0.43374,
				0.46905,
				0.50435,
				0.55479,
				0.59009,
				0.63044,
				0.68592,
				0.74139,
				0.79687,
				0.85739,
				0.91792,
				0.97844,
				1.03896,
				1.09948,
				1.16,
			},
		},
		{{ // attack: GleamingSpearGuardianStance - 4-Hit DMG: {4}
			0.94944,
			1.02672,
			1.104,
			1.2144,
			1.29168,
			1.38,
			1.50144,
			1.62288,
			1.74432,
			1.8768,
			2.00928,
			2.14176,
			2.27424,
			2.40672,
			2.5392,
		}},
	}
	// attack: GleamingSpearGuardianStance - Charged Attack DMG: {5}
	charge = []float64{
		1.24184,
		1.34292,
		1.444,
		1.5884,
		1.68948,
		1.805,
		1.96384,
		2.12268,
		2.28152,
		2.4548,
		2.62808,
		2.80136,
		2.97464,
		3.14792,
		3.3212,
	}
	// attack: GleamingSpearGuardianStance - Plunge DMG: {7}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: GleamingSpearGuardianStance - Low/High Plunge DMG: {8}/{9}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: GleamingSpearGuardianStance - Low/High Plunge DMG: {8}/{9}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	skillDmg = [][]float64{
		{ // skill: SacredRiteHeronsSanctum - Shield DMG Absorption: {0} Max HP+{1}
			0.12,
			0.129,
			0.138,
			0.15,
			0.159,
			0.168,
			0.18,
			0.192,
			0.204,
			0.216,
			0.228,
			0.24,
			0.255,
			0.27,
			0.285,
		},
		{ // skill: SacredRiteHeronsSanctum - Charged Up DMG: {3} Max HP
			0.1904,
			0.20468,
			0.21896,
			0.238,
			0.25228,
			0.26656,
			0.2856,
			0.30464,
			0.32368,
			0.34272,
			0.36176,
			0.3808,
			0.4046,
			0.4284,
			0.4522,
		},
	}
	// skill: SacredRiteHeronsSanctum - Shield DMG Absorption: {0} Max HP+{1}
	skillShieldPct = []float64{
		0.12,
		0.129,
		0.138,
		0.15,
		0.159,
		0.168,
		0.18,
		0.192,
		0.204,
		0.216,
		0.228,
		0.24,
		0.255,
		0.27,
		0.285,
	}
	// skill: SacredRiteHeronsSanctum - Shield DMG Absorption: {0} Max HP+{1}
	skillShieldFlat = []float64{
		1155.563,
		1271.135,
		1396.339,
		1531.173,
		1675.638,
		1829.735,
		1993.462,
		2166.821,
		2349.811,
		2542.431,
		2744.683,
		2956.565,
		3178.079,
		3409.224,
		3650.0,
	}
	// burst: SacredRiteWagtailsTide - Skill DMG: {0} Max HP
	burstDmg = []float64{
		0.0661,
		0.07106,
		0.07602,
		0.08263,
		0.08759,
		0.09255,
		0.09916,
		0.10577,
		0.11238,
		0.11899,
		0.1256,
		0.13221,
		0.14047,
		0.14873,
		0.157,
	}
	// burst: SacredRiteWagtailsTide - Skill DMG: {0} Max HP
	burstWaveDmg = []float64{
		0.0661,
		0.07106,
		0.07602,
		0.08263,
		0.08759,
		0.09255,
		0.09916,
		0.10577,
		0.11238,
		0.11899,
		0.1256,
		0.13221,
		0.14047,
		0.14873,
		0.157,
	}
)
