// Code generated by "pipeline"; DO NOT EDIT.

package citlali

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Citlali, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionCharge: {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Citlali, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: ShadowStealingSpiritVessel - 1-Hit DMG: {0}
			0.43407,
			0.46663,
			0.49918,
			0.54259,
			0.57515,
			0.6077,
			0.65111,
			0.69451,
			0.73792,
			0.78133,
			0.82474,
			0.86814,
			0.9224,
			0.97666,
			1.03092,
		},
		{ // attack: ShadowStealingSpiritVessel - 2-Hit DMG: {1}
			0.38814,
			0.41725,
			0.44636,
			0.48517,
			0.51428,
			0.54339,
			0.5822,
			0.62102,
			0.65983,
			0.69864,
			0.73746,
			0.77627,
			0.82479,
			0.87331,
			0.92182,
		},
		{ // attack: ShadowStealingSpiritVessel - 3-Hit DMG: {2}
			0.53771,
			0.57804,
			0.61837,
			0.67214,
			0.71247,
			0.7528,
			0.80657,
			0.86034,
			0.91411,
			0.96788,
			1.02165,
			1.07542,
			1.14264,
			1.20985,
			1.27707,
		},
	}
	// attack: ShadowStealingSpiritVessel - Charged Attack DMG: {3}
	charge = []float64{
		0.992,
		1.0664,
		1.1408,
		1.24,
		1.3144,
		1.3888,
		1.488,
		1.5872,
		1.6864,
		1.7856,
		1.8848,
		1.984,
		2.108,
		2.232,
		2.356,
	}
	// attack: ShadowStealingSpiritVessel - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: ShadowStealingSpiritVessel - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: ShadowStealingSpiritVessel - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: DawnfrostDarkstar - Obsidian Tzitzimitl DMG: {0}
	skill = []float64{
		0.7296,
		0.78432,
		0.83904,
		0.912,
		0.96672,
		1.02144,
		1.0944,
		1.16736,
		1.24032,
		1.31328,
		1.38624,
		1.4592,
		1.5504,
		1.6416,
		1.7328,
	}
	// skill: DawnfrostDarkstar - Shield DMG Absorption: {1} Elemental Mastery+{2}
	shieldEM = []float64{
		5.76,
		6.192,
		6.624,
		7.2,
		7.632,
		8.064,
		8.64,
		9.216,
		9.792,
		10.368,
		10.944,
		11.52,
		12.24,
		12.96,
		13.68,
	}
	// skill: DawnfrostDarkstar - Shield DMG Absorption: {1} Elemental Mastery+{2}
	shieldFlat = []float64{
		1386.676,
		1525.363,
		1675.607,
		1837.408,
		2010.767,
		2195.683,
		2392.156,
		2600.186,
		2819.773,
		3050.918,
		3293.62,
		3547.88,
		3813.696,
		4091.07,
		4380.0,
	}
	// skill: DawnfrostDarkstar - Frostfall Storm DMG: {4}
	frostfall = []float64{
		0.17024,
		0.18301,
		0.19578,
		0.2128,
		0.22557,
		0.23834,
		0.25536,
		0.27238,
		0.28941,
		0.30643,
		0.32346,
		0.34048,
		0.36176,
		0.38304,
		0.40432,
	}
	// burst: EdictOfEntwinedSplendor - Ice Storm DMG: {0}
	iceStorm = []float64{
		5.376,
		5.7792,
		6.1824,
		6.72,
		7.1232,
		7.5264,
		8.064,
		8.6016,
		9.1392,
		9.6768,
		10.2144,
		10.752,
		11.424,
		12.096,
		12.768,
	}
	// burst: EdictOfEntwinedSplendor - Spiritvessel Skull DMG: {1}
	spiritVessel = []float64{
		1.344,
		1.4448,
		1.5456,
		1.68,
		1.7808,
		1.8816,
		2.016,
		2.1504,
		2.2848,
		2.4192,
		2.5536,
		2.688,
		2.856,
		3.024,
		3.192,
	}
)
