// Code generated by "pipeline"; DO NOT EDIT.

package yaemiko

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.YaeMiko, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack:     {"travel"},
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.YaeMiko, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SpiritfoxSinEater - 1-Hit DMG: {0}
			0.39658,
			0.42633,
			0.45607,
			0.49573,
			0.52547,
			0.55522,
			0.59488,
			0.63453,
			0.67419,
			0.71385,
			0.75351,
			0.79317,
			0.84274,
			0.89231,
			0.94189,
		},
		{ // attack: SpiritfoxSinEater - 2-Hit DMG: {1}
			0.38519,
			0.41408,
			0.44297,
			0.48149,
			0.51038,
			0.53927,
			0.57779,
			0.61631,
			0.65483,
			0.69335,
			0.73186,
			0.77038,
			0.81853,
			0.86668,
			0.91483,
		},
		{ // attack: SpiritfoxSinEater - 3-Hit DMG: {2}
			0.56889,
			0.61155,
			0.65422,
			0.71111,
			0.75378,
			0.79644,
			0.85333,
			0.91022,
			0.96711,
			1.024,
			1.08089,
			1.13778,
			1.20889,
			1.28,
			1.35111,
		},
	}
	// attack: SpiritfoxSinEater - Charged Attack DMG: {3}
	charge = []float64{
		1.42895,
		1.53612,
		1.64329,
		1.78619,
		1.89336,
		2.00053,
		2.14342,
		2.28632,
		2.42921,
		2.57211,
		2.715,
		2.8579,
		3.03651,
		3.21513,
		3.39375,
	}
	// attack: SpiritfoxSinEater - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: SpiritfoxSinEater - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: SpiritfoxSinEater - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	skill = [][]float64{
		{ // skill: YakanEvocationSesshouSakura - Sesshou Sakura DMG: Level 1: {0}
			0.60672,
			0.65222,
			0.69773,
			0.7584,
			0.8039,
			0.84941,
			0.91008,
			0.97075,
			1.03142,
			1.0921,
			1.15277,
			1.21344,
			1.28928,
			1.36512,
			1.44096,
		},
		{ // skill: YakanEvocationSesshouSakura - Sesshou Sakura DMG: Level 2: {1}
			0.7584,
			0.81528,
			0.87216,
			0.948,
			1.00488,
			1.06176,
			1.1376,
			1.21344,
			1.28928,
			1.36512,
			1.44096,
			1.5168,
			1.6116,
			1.7064,
			1.8012,
		},
		{ // skill: YakanEvocationSesshouSakura - Sesshou Sakura DMG: Level 3: {2}
			0.948,
			1.0191,
			1.0902,
			1.185,
			1.2561,
			1.3272,
			1.422,
			1.5168,
			1.6116,
			1.7064,
			1.8012,
			1.896,
			2.0145,
			2.133,
			2.2515,
		},
		{ // skill: YakanEvocationSesshouSakura - Sesshou Sakura DMG: Level 4: {3}
			1.185,
			1.27387,
			1.36275,
			1.48125,
			1.57012,
			1.659,
			1.7775,
			1.896,
			2.0145,
			2.133,
			2.2515,
			2.37,
			2.51813,
			2.66625,
			2.81437,
		},
	}
	burst = [][]float64{
		{ // burst: GreatSecretArtTenkoKenshin - Skill DMG: {0}
			2.6,
			2.795,
			2.99,
			3.25,
			3.445,
			3.64,
			3.9,
			4.16,
			4.42,
			4.68,
			4.94,
			5.2,
			5.525,
			5.85,
			6.175,
		},
		{ // burst: GreatSecretArtTenkoKenshin - Tenko Thunderbolt DMG: {1}
			3.33816,
			3.58852,
			3.83888,
			4.1727,
			4.42306,
			4.67342,
			5.00724,
			5.34106,
			5.67487,
			6.00869,
			6.3425,
			6.67632,
			7.09359,
			7.51086,
			7.92813,
		},
	}
)
