// Code generated by "pipeline"; DO NOT EDIT.

package beidou

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Beidou, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"counter"},
	}
	validation.RegisterCharParamValidationFunc(keys.Beidou, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: Oceanborne - 1-Hit DMG: {0}
			0.71122,
			0.76911,
			0.827,
			0.9097,
			0.96759,
			1.03375,
			1.12472,
			1.21569,
			1.30666,
			1.4059,
			1.51961,
			1.65334,
			1.78706,
			1.92079,
			2.06667,
		},
		{ // attack: Oceanborne - 2-Hit DMG: {1}
			0.70864,
			0.76632,
			0.824,
			0.9064,
			0.96408,
			1.03,
			1.12064,
			1.21128,
			1.30192,
			1.4008,
			1.5141,
			1.64734,
			1.78058,
			1.91382,
			2.05918,
		},
		{ // attack: Oceanborne - 3-Hit DMG: {2}
			0.88322,
			0.95511,
			1.027,
			1.1297,
			1.20159,
			1.28375,
			1.39672,
			1.50969,
			1.62266,
			1.7459,
			1.88711,
			2.05318,
			2.21924,
			2.38531,
			2.56647,
		},
		{ // attack: Oceanborne - 4-Hit DMG: {3}
			0.86516,
			0.93558,
			1.006,
			1.1066,
			1.17702,
			1.2575,
			1.36816,
			1.47882,
			1.58948,
			1.7102,
			1.84853,
			2.01119,
			2.17387,
			2.33654,
			2.51399,
		},
		{ // attack: Oceanborne - 5-Hit DMG: {4}
			1.12144,
			1.21272,
			1.304,
			1.4344,
			1.52568,
			1.63,
			1.77344,
			1.91688,
			2.06032,
			2.2168,
			2.3961,
			2.60696,
			2.81781,
			3.02867,
			3.2587,
		},
	}
	// skill: Tidecaller - Shield DMG Absorption: {0} Max HP+{1}
	shieldPer = []float64{
		0.144,
		0.1548,
		0.1656,
		0.18,
		0.1908,
		0.2016,
		0.216,
		0.2304,
		0.2448,
		0.2592,
		0.2736,
		0.288,
		0.306,
		0.324,
		0.342,
	}
	// skill: Tidecaller - Shield DMG Absorption: {0} Max HP+{1}
	shieldBase = []float64{
		1386.368,
		1525.024,
		1675.235,
		1837.0,
		2010.32,
		2195.195,
		2391.624,
		2599.608,
		2819.147,
		3050.24,
		3292.889,
		3547.091,
		3812.849,
		4090.161,
		4379.028,
	}
	// skill: Tidecaller - DMG Bonus on Hit Taken: {3}
	skillbonus = []float64{
		1.6,
		1.72,
		1.84,
		2.0,
		2.12,
		2.24,
		2.4,
		2.56,
		2.72,
		2.88,
		3.04,
		3.2,
		3.4,
		3.6,
		3.8,
	}
	// burst: Stormbreaker - Skill DMG: {0}
	skillbase = []float64{
		1.216,
		1.3072,
		1.3984,
		1.52,
		1.6112,
		1.7024,
		1.824,
		1.9456,
		2.0672,
		2.1888,
		2.3104,
		2.432,
		2.584,
		2.736,
		2.888,
	}
	// burst: Stormbreaker - Skill DMG: {0}
	burstonhit = []float64{
		1.216,
		1.3072,
		1.3984,
		1.52,
		1.6112,
		1.7024,
		1.824,
		1.9456,
		2.0672,
		2.1888,
		2.3104,
		2.432,
		2.584,
		2.736,
		2.888,
	}
	// burst: Stormbreaker - Lightning DMG: {1}
	burstproc = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
)
