// Code generated by "pipeline"; DO NOT EDIT.

package kaeya

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Kaeya, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Kaeya, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][]float64{
		{ // attack: CeremonialBladework - 1-Hit DMG: {0}
			0.5375,
			0.58125,
			0.625,
			0.6875,
			0.73125,
			0.78125,
			0.85,
			0.91875,
			0.9875,
			1.0625,
			1.14844,
			1.2495,
			1.35056,
			1.45162,
			1.56187,
		},
		{ // attack: CeremonialBladework - 2-Hit DMG: {1}
			0.51686,
			0.55893,
			0.601,
			0.6611,
			0.70317,
			0.75125,
			0.81736,
			0.88347,
			0.94958,
			1.0217,
			1.10434,
			1.20152,
			1.2987,
			1.39588,
			1.5019,
		},
		{ // attack: CeremonialBladework - 3-Hit DMG: {2}
			0.65274,
			0.70587,
			0.759,
			0.8349,
			0.88803,
			0.94875,
			1.03224,
			1.11573,
			1.19922,
			1.2903,
			1.39466,
			1.51739,
			1.64012,
			1.76285,
			1.89674,
		},
		{ // attack: CeremonialBladework - 4-Hit DMG: {3}
			0.70864,
			0.76632,
			0.824,
			0.9064,
			0.96408,
			1.03,
			1.12064,
			1.21128,
			1.30192,
			1.4008,
			1.5141,
			1.64734,
			1.78058,
			1.91382,
			2.05918,
		},
		{ // attack: CeremonialBladework - 5-Hit DMG: {4}
			0.88236,
			0.95418,
			1.026,
			1.1286,
			1.20042,
			1.2825,
			1.39536,
			1.50822,
			1.62108,
			1.7442,
			1.88528,
			2.05118,
			2.21708,
			2.38299,
			2.56397,
		},
	}
	charge = [][]float64{
		{ // attack: CeremonialBladework - Charged Attack DMG: {5}+{6}
			0.5504,
			0.5952,
			0.64,
			0.704,
			0.7488,
			0.8,
			0.8704,
			0.9408,
			1.0112,
			1.088,
			1.176,
			1.27949,
			1.38298,
			1.48646,
			1.59936,
		},
		{ // attack: CeremonialBladework - Charged Attack DMG: {5}+{6}
			0.731,
			0.7905,
			0.85,
			0.935,
			0.9945,
			1.0625,
			1.156,
			1.2495,
			1.343,
			1.445,
			1.56187,
			1.69932,
			1.83677,
			1.97421,
			2.12415,
		},
	}
	// attack: CeremonialBladework - Plunge DMG: {8}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: CeremonialBladework - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: CeremonialBladework - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: Frostgnaw - Skill DMG: {0}
	skill = []float64{
		1.912,
		2.0554,
		2.1988,
		2.39,
		2.5334,
		2.6768,
		2.868,
		3.0592,
		3.2504,
		3.4416,
		3.6328,
		3.824,
		4.063,
		4.302,
		4.541,
	}
	// burst: GlacialWaltz - Skill DMG: {0}
	burst = []float64{
		0.776,
		0.8342,
		0.8924,
		0.97,
		1.0282,
		1.0864,
		1.164,
		1.2416,
		1.3192,
		1.3968,
		1.4744,
		1.552,
		1.649,
		1.746,
		1.843,
	}
)
