// Code generated by "pipeline"; DO NOT EDIT.

package albedo

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Albedo, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Albedo, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: FavoniusBladeworkWeiss - 1-Hit DMG: {0}
			0.36739,
			0.3973,
			0.4272,
			0.46992,
			0.49982,
			0.534,
			0.58099,
			0.62798,
			0.67498,
			0.72624,
			0.78498,
			0.85406,
			0.92314,
			0.99221,
			1.06757,
		},
		{ // attack: FavoniusBladeworkWeiss - 2-Hit DMG: {1}
			0.36739,
			0.3973,
			0.4272,
			0.46992,
			0.49982,
			0.534,
			0.58099,
			0.62798,
			0.67498,
			0.72624,
			0.78498,
			0.85406,
			0.92314,
			0.99221,
			1.06757,
		},
		{ // attack: FavoniusBladeworkWeiss - 3-Hit DMG: {2}
			0.47455,
			0.51317,
			0.5518,
			0.60698,
			0.64561,
			0.68975,
			0.75045,
			0.81115,
			0.87184,
			0.93806,
			1.01393,
			1.10316,
			1.19238,
			1.28161,
			1.37895,
		},
		{ // attack: FavoniusBladeworkWeiss - 4-Hit DMG: {3}
			0.49751,
			0.538,
			0.5785,
			0.63635,
			0.67685,
			0.72312,
			0.78676,
			0.8504,
			0.91403,
			0.98345,
			1.06299,
			1.15654,
			1.25008,
			1.34362,
			1.44567,
		},
		{ // attack: FavoniusBladeworkWeiss - 5-Hit DMG: {4}
			0.62074,
			0.67127,
			0.72179,
			0.79397,
			0.84449,
			0.90224,
			0.98163,
			1.06103,
			1.14043,
			1.22704,
			1.32629,
			1.443,
			1.55972,
			1.67643,
			1.80375,
		},
	}
	charge = [][]float64{
		{ // attack: FavoniusBladeworkWeiss - Charged Attack DMG: {5}+{6}
			0.473,
			0.5115,
			0.55,
			0.605,
			0.6435,
			0.6875,
			0.748,
			0.8085,
			0.869,
			0.935,
			1.01063,
			1.09956,
			1.1885,
			1.27743,
			1.37445,
		},
		{ // attack: FavoniusBladeworkWeiss - Charged Attack DMG: {5}+{6}
			0.602,
			0.651,
			0.7,
			0.77,
			0.819,
			0.875,
			0.952,
			1.029,
			1.106,
			1.19,
			1.28625,
			1.39944,
			1.51263,
			1.62582,
			1.7493,
		},
	}
	// attack: FavoniusBladeworkWeiss - Plunge DMG: {8}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: FavoniusBladeworkWeiss - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: FavoniusBladeworkWeiss - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: AbiogenesisSolarIsotoma - Skill DMG: {0}
	skill = []float64{
		1.304,
		1.4018,
		1.4996,
		1.63,
		1.7278,
		1.8256,
		1.956,
		2.0864,
		2.2168,
		2.3472,
		2.4776,
		2.608,
		2.771,
		2.934,
		3.097,
	}
	// skill: AbiogenesisSolarIsotoma - Transient Blossom DMG: {1} DEF
	skillTick = []float64{
		1.336,
		1.4362,
		1.5364,
		1.67,
		1.7702,
		1.8704,
		2.004,
		2.1376,
		2.2712,
		2.4048,
		2.5384,
		2.672,
		2.839,
		3.006,
		3.173,
	}
	// burst: RiteOfProgenitureTectonicTide - Burst DMG: {0}
	burst = []float64{
		3.672,
		3.9474,
		4.2228,
		4.59,
		4.8654,
		5.1408,
		5.508,
		5.8752,
		6.2424,
		6.6096,
		6.9768,
		7.344,
		7.803,
		8.262,
		8.721,
	}
	// burst: RiteOfProgenitureTectonicTide - Fatal Blossom DMG: {1} each
	burstPerBloom = []float64{
		0.72,
		0.774,
		0.828,
		0.9,
		0.954,
		1.008,
		1.08,
		1.152,
		1.224,
		1.296,
		1.368,
		1.44,
		1.53,
		1.62,
		1.71,
	}
)
