// Code generated by "pipeline"; DO NOT EDIT.

package heizou

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.ShikanoinHeizou, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.ShikanoinHeizou, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: FudouStyleMartialArts - 1-Hit DMG: {0}
			0.37474,
			0.40284,
			0.43095,
			0.46842,
			0.49652,
			0.52463,
			0.5621,
			0.59958,
			0.63705,
			0.67453,
			0.712,
			0.74947,
			0.79631,
			0.84316,
			0.89,
		}},
		{{ // attack: FudouStyleMartialArts - 2-Hit DMG: {1}
			0.36852,
			0.39616,
			0.4238,
			0.46065,
			0.48829,
			0.51593,
			0.55278,
			0.58963,
			0.62648,
			0.66334,
			0.70019,
			0.73704,
			0.78311,
			0.82917,
			0.87524,
		}},
		{{ // attack: FudouStyleMartialArts - 3-Hit DMG: {2}
			0.5106,
			0.5489,
			0.58719,
			0.63825,
			0.67655,
			0.71484,
			0.7659,
			0.81696,
			0.86802,
			0.91908,
			0.97014,
			1.0212,
			1.08502,
			1.14885,
			1.21267,
		}},
		{
			{ // attack: FudouStyleMartialArts - 4-Hit DMG: {3}+{4}+{5}
				0.14782,
				0.15891,
				0.17,
				0.18478,
				0.19587,
				0.20695,
				0.22174,
				0.23652,
				0.2513,
				0.26608,
				0.28087,
				0.29565,
				0.31413,
				0.3326,
				0.35108,
			},
			{ // attack: FudouStyleMartialArts - 4-Hit DMG: {3}+{4}+{5}
				0.16261,
				0.1748,
				0.187,
				0.20326,
				0.21546,
				0.22765,
				0.24391,
				0.26017,
				0.27643,
				0.29269,
				0.30896,
				0.32522,
				0.34554,
				0.36587,
				0.38619,
			},
			{ // attack: FudouStyleMartialArts - 4-Hit DMG: {3}+{4}+{5}
				0.19218,
				0.20659,
				0.221,
				0.24022,
				0.25463,
				0.26905,
				0.28826,
				0.30748,
				0.3267,
				0.34592,
				0.36513,
				0.38435,
				0.40837,
				0.4324,
				0.45642,
			},
		},
		{{ // attack: FudouStyleMartialArts - 5-Hit DMG: {6}
			0.6145,
			0.66058,
			0.70667,
			0.76812,
			0.81421,
			0.86029,
			0.92174,
			0.98319,
			1.04464,
			1.10609,
			1.16754,
			1.22899,
			1.3058,
			1.38262,
			1.45943,
		}},
	}
	// attack: FudouStyleMartialArts - Charged Attack: {7}
	charge = []float64{
		0.73,
		0.78475,
		0.8395,
		0.9125,
		0.96725,
		1.022,
		1.095,
		1.168,
		1.241,
		1.314,
		1.387,
		1.46,
		1.55125,
		1.6425,
		1.73375,
	}
	// attack: FudouStyleMartialArts - Plunge DMG: {9}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: FudouStyleMartialArts - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: FudouStyleMartialArts - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: HeartstopperStrike - Skill DMG: {0}
	skill = []float64{
		2.2752,
		2.44584,
		2.61648,
		2.844,
		3.01464,
		3.18528,
		3.4128,
		3.64032,
		3.86784,
		4.09536,
		4.32288,
		4.5504,
		4.8348,
		5.1192,
		5.4036,
	}
	// skill: HeartstopperStrike - Declension DMG Bonus: {1}/stack
	decBonus = []float64{
		0.5688,
		0.61146,
		0.65412,
		0.711,
		0.75366,
		0.79632,
		0.8532,
		0.91008,
		0.96696,
		1.02384,
		1.08072,
		1.1376,
		1.2087,
		1.2798,
		1.3509,
	}
	// skill: HeartstopperStrike - Conviction DMG Bonus: {2}
	convicBonus = []float64{
		1.1376,
		1.22292,
		1.30824,
		1.422,
		1.50732,
		1.59264,
		1.7064,
		1.82016,
		1.93392,
		2.04768,
		2.16144,
		2.2752,
		2.4174,
		2.5596,
		2.7018,
	}
	// burst: WindmusterKick - Fudou Style Vacuum Slugger DMG: {0}
	burst = []float64{
		3.14688,
		3.3829,
		3.61891,
		3.9336,
		4.16962,
		4.40563,
		4.72032,
		5.03501,
		5.3497,
		5.66438,
		5.97907,
		6.29376,
		6.68712,
		7.08048,
		7.47384,
	}
	// burst: WindmusterKick - Windmuster Iris DMG: {1}
	burstIris = []float64{
		0.21456,
		0.23065,
		0.24674,
		0.2682,
		0.28429,
		0.30038,
		0.32184,
		0.3433,
		0.36475,
		0.38621,
		0.40766,
		0.42912,
		0.45594,
		0.48276,
		0.50958,
	}
)
