// Code generated by "pipeline"; DO NOT EDIT.

package aino

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Aino, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Aino, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: BishBashBoshRepair - 1-Hit DMG: {0}
			0.66499,
			0.71911,
			0.77324,
			0.85056,
			0.90469,
			0.96655,
			1.05161,
			1.13666,
			1.22172,
			1.31451,
			1.4073,
			1.50009,
			1.59287,
			1.68566,
			1.77845,
		}},
		{{ // attack: BishBashBoshRepair - 2-Hit DMG: {1}
			0.66192,
			0.71579,
			0.76967,
			0.84664,
			0.90051,
			0.96209,
			1.04675,
			1.13142,
			1.21608,
			1.30844,
			1.4008,
			1.49316,
			1.58552,
			1.67788,
			1.77024,
		}},
		{
			{ // attack: BishBashBoshRepair - 3-Hit DMG: {2}×2
				0.49216,
				0.53223,
				0.57228,
				0.62951,
				0.66957,
				0.71536,
				0.77831,
				0.84126,
				0.90421,
				0.97289,
				1.04156,
				1.11023,
				1.17891,
				1.24758,
				1.31626,
			},
			{ // attack: BishBashBoshRepair - 3-Hit DMG: {2}×2
				0.49216,
				0.53223,
				0.57228,
				0.62951,
				0.66957,
				0.71536,
				0.77831,
				0.84126,
				0.90421,
				0.97289,
				1.04156,
				1.11023,
				1.17891,
				1.24758,
				1.31626,
			},
		},
	}
	skill = [][]float64{
		{ // skill: Musecatcher - Stage 1 DMG: {0}
			0.656,
			0.7052,
			0.7544,
			0.82,
			0.8692,
			0.9184,
			0.984,
			1.0496,
			1.1152,
			1.1808,
			1.2464,
			1.312,
			1.394,
			1.476,
			1.558,
		},
		{ // skill: Musecatcher - Stage 2 DMG: {1}
			1.888,
			2.0296,
			2.1712,
			2.36,
			2.5016,
			2.6432,
			2.832,
			3.0208,
			3.2096,
			3.3984,
			3.5872,
			3.776,
			4.012,
			4.248,
			4.484,
		},
	}
	// burst: PrecisionHydronicCooler - Water Ball DMG: {0}
	burst = []float64{
		0.20112,
		0.2162,
		0.23129,
		0.2514,
		0.26648,
		0.28157,
		0.30168,
		0.32179,
		0.3419,
		0.36202,
		0.38213,
		0.40224,
		0.42738,
		0.45252,
		0.47766,
	}
)
