// Code generated by "pipeline"; DO NOT EDIT.

package ifa

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Ifa, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Ifa, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: RiteOfDispellingWinds - 1-Hit DMG: {0}
			0.53607,
			0.57628,
			0.61648,
			0.67009,
			0.7103,
			0.7505,
			0.80411,
			0.85772,
			0.91132,
			0.96493,
			1.01854,
			1.07214,
			1.13915,
			1.20616,
			1.27317,
		},
		{ // attack: RiteOfDispellingWinds - 2-Hit DMG: {1}
			0.47467,
			0.51027,
			0.54587,
			0.59334,
			0.62894,
			0.66454,
			0.71201,
			0.75947,
			0.80694,
			0.85441,
			0.90188,
			0.94934,
			1.00868,
			1.06801,
			1.12735,
		},
		{ // attack: RiteOfDispellingWinds - 3-Hit DMG: {2}
			0.74758,
			0.80365,
			0.85972,
			0.93448,
			0.99055,
			1.04662,
			1.12138,
			1.19613,
			1.27089,
			1.34565,
			1.42041,
			1.49517,
			1.58862,
			1.68206,
			1.77551,
		},
	}
	// attack: RiteOfDispellingWinds - Charged Attack DMG: {3}
	charge = []float64{
		1.4704,
		1.58068,
		1.69096,
		1.838,
		1.94828,
		2.05856,
		2.2056,
		2.35264,
		2.49968,
		2.64672,
		2.79376,
		2.9408,
		3.1246,
		3.3084,
		3.4922,
	}
	// attack: RiteOfDispellingWinds - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: RiteOfDispellingWinds - Low/High Plunge DMG: {6}/{7}
	plungeLow = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: RiteOfDispellingWinds - Low/High Plunge DMG: {6}/{7}
	plungeHigh = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: AirborneDiseasePrevention - Tonicshot DMG: {0}
	skillDmg = []float64{
		1.3336,
		1.43362,
		1.53364,
		1.667,
		1.76702,
		1.86704,
		2.0004,
		2.13376,
		2.26712,
		2.40048,
		2.53384,
		2.6672,
		2.8339,
		3.0006,
		3.1673,
	}
	// skill: AirborneDiseasePrevention - Tonicshot Healing On Hit: {1} Elemental Mastery+{2}
	skillHeal = []float64{
		0.2016,
		0.21672,
		0.23184,
		0.252,
		0.26712,
		0.28224,
		0.3024,
		0.32256,
		0.34272,
		0.36288,
		0.38304,
		0.4032,
		0.4284,
		0.4536,
		0.4788,
	}
	// skill: AirborneDiseasePrevention - Tonicshot Healing On Hit: {1} Elemental Mastery+{2}
	skillHealFlat = []float64{
		48.14847,
		52.96399,
		58.1808,
		63.7989,
		69.8183,
		76.23898,
		83.06097,
		90.28424,
		97.90881,
		105.9347,
		114.3618,
		123.1903,
		132.42,
		142.051,
		152.0834,
	}
	// burst: CompoundSedationField - Skill DMG: {0}
	burstDmg = []float64{
		5.0848,
		5.46616,
		5.84752,
		6.356,
		6.73736,
		7.11872,
		7.6272,
		8.13568,
		8.64416,
		9.15264,
		9.66112,
		10.1696,
		10.8052,
		11.4408,
		12.0764,
	}
	// burst: CompoundSedationField - Sedation Mark DMG: {1}
	burstMark = []float64{
		1.0896,
		1.17132,
		1.25304,
		1.362,
		1.44372,
		1.52544,
		1.6344,
		1.74336,
		1.85232,
		1.96128,
		2.07024,
		2.1792,
		2.3154,
		2.4516,
		2.5878,
	}
)
