// Code generated by "pipeline"; DO NOT EDIT.

package razor

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Razor, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Razor, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SteelFang - 1-Hit DMG: {0}
			0.9592,
			1.0246,
			1.09,
			1.1772,
			1.2426,
			1.3189,
			1.417,
			1.5151,
			1.6132,
			1.7113,
			1.8094,
			1.9075,
			2.0056,
			2.1037,
			2.2018,
		},
		{ // attack: SteelFang - 2-Hit DMG: {1}
			0.82632,
			0.88266,
			0.939,
			1.01412,
			1.07046,
			1.13619,
			1.2207,
			1.30521,
			1.38972,
			1.47423,
			1.55874,
			1.64325,
			1.72776,
			1.81227,
			1.89678,
		},
		{ // attack: SteelFang - 3-Hit DMG: {2}
			1.03312,
			1.10356,
			1.174,
			1.26792,
			1.33836,
			1.42054,
			1.5262,
			1.63186,
			1.73752,
			1.84318,
			1.94884,
			2.0545,
			2.16016,
			2.26582,
			2.37148,
		},
		{ // attack: SteelFang - 4-Hit DMG: {3}
			1.36048,
			1.45324,
			1.546,
			1.66968,
			1.76244,
			1.87066,
			2.0098,
			2.14894,
			2.28808,
			2.42722,
			2.56636,
			2.7055,
			2.84464,
			2.98378,
			3.12292,
		},
	}
	// attack: SteelFang - Plunge DMG: {8}
	collision = []float64{
		0.82047,
		0.88725,
		0.95403,
		1.04943,
		1.11621,
		1.19254,
		1.29748,
		1.40242,
		1.50737,
		1.62185,
		1.73634,
		1.85082,
		1.9653,
		2.07979,
		2.19427,
	}
	// attack: SteelFang - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.64058,
		1.77412,
		1.90766,
		2.09842,
		2.23196,
		2.38457,
		2.59441,
		2.80425,
		3.0141,
		3.24302,
		3.47193,
		3.70085,
		3.92977,
		4.15869,
		4.38761,
	}
	// attack: SteelFang - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		2.04918,
		2.21597,
		2.38277,
		2.62104,
		2.78783,
		2.97846,
		3.24056,
		3.50267,
		3.76477,
		4.0507,
		4.33663,
		4.62256,
		4.9085,
		5.19443,
		5.48036,
	}
	// skill: ClawAndThunder - Press Skill DMG: {0}
	skillPress = []float64{
		1.992,
		2.1414,
		2.2908,
		2.49,
		2.6394,
		2.7888,
		2.988,
		3.1872,
		3.3864,
		3.5856,
		3.7848,
		3.984,
		4.233,
		4.482,
		4.731,
	}
	// skill: ClawAndThunder - Hold Skill DMG: {1}
	skillHold = []float64{
		2.952,
		3.1734,
		3.3948,
		3.69,
		3.9114,
		4.1328,
		4.428,
		4.7232,
		5.0184,
		5.3136,
		5.6088,
		5.904,
		6.273,
		6.642,
		7.011,
	}
	// burst: LightningFang - Burst DMG: {0}
	burstDmg = []float64{
		1.6,
		1.72,
		1.84,
		2.0,
		2.12,
		2.24,
		2.4,
		2.56,
		2.72,
		2.88,
		3.04,
		3.2,
		3.4,
		3.6,
		3.8,
	}
	// burst: LightningFang - Soul Companion DMG: {1} Normal Attack DMG
	wolfDmg = []float64{
		0.24,
		0.258,
		0.276,
		0.3,
		0.318,
		0.336,
		0.36,
		0.384,
		0.408,
		0.432,
		0.456,
		0.48,
		0.51,
		0.54,
		0.57,
	}
	// burst: LightningFang - Normal ATK SPD Bonus: {2}
	burstATKSpeed = []float64{
		0.26,
		0.28,
		0.3,
		0.32,
		0.34,
		0.36,
		0.37,
		0.38,
		0.39,
		0.4,
		0.4,
		0.4,
		0.4,
		0.4,
		0.4,
	}
)
