// Code generated by "pipeline"; DO NOT EDIT.

package valeriy

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Valeriy, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Valeriy, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: GuardTacticsSwordAndShield - 1-Hit DMG: {0}
			0.32484,
			0.35128,
			0.37772,
			0.41549,
			0.44193,
			0.47215,
			0.5137,
			0.55525,
			0.5968,
			0.64212,
			0.68745,
			0.73278,
			0.7781,
			0.82343,
			0.86876,
		},
		{ // attack: GuardTacticsSwordAndShield - 2-Hit DMG: {1}
			0.29326,
			0.31713,
			0.341,
			0.3751,
			0.39897,
			0.42625,
			0.46376,
			0.50127,
			0.53878,
			0.5797,
			0.62062,
			0.66154,
			0.70246,
			0.74338,
			0.7843,
		},
		{ // attack: GuardTacticsSwordAndShield - 3-Hit DMG: {2}
			0.45417,
			0.49114,
			0.52811,
			0.58092,
			0.61789,
			0.66014,
			0.71823,
			0.77632,
			0.83441,
			0.89779,
			0.96116,
			1.02453,
			1.08791,
			1.15128,
			1.21465,
		},
	}
	// attack: GuardTacticsSwordAndShield - Charged Attack DMG: {3}
	charge = []float64{
		1.00276,
		1.08438,
		1.166,
		1.2826,
		1.36422,
		1.4575,
		1.58576,
		1.71402,
		1.84228,
		1.9822,
		2.12212,
		2.26204,
		2.40196,
		2.54188,
		2.6818,
	}
	// attack: GuardTacticsSwordAndShield - Direct-Fire Mortar: Point-Blank Bombardment DMG: {4}
	specialCharge = []float64{
		2.292,
		2.4639,
		2.6358,
		2.865,
		3.0369,
		3.2088,
		3.438,
		3.6672,
		3.8964,
		4.1256,
		4.3548,
		4.584,
		4.8705,
		5.157,
		5.4435,
	}
	// attack: GuardTacticsSwordAndShield - Electro DMG Bonus: {6} ATK
	electro = []float64{
		0.2096,
		0.22532,
		0.24104,
		0.262,
		0.27772,
		0.29344,
		0.3144,
		0.33536,
		0.35632,
		0.37728,
		0.39824,
		0.4192,
		0.4454,
		0.4716,
		0.4978,
	}
	// attack: GuardTacticsSwordAndShield - Stellar-Conduct DMG Bonus: {7} ATK
	ssc = []float64{
		0.6288,
		0.67596,
		0.72312,
		0.786,
		0.83316,
		0.88032,
		0.9432,
		1.00608,
		1.06896,
		1.13184,
		1.19472,
		1.2576,
		1.3362,
		1.4148,
		1.4934,
	}
	// skill: ActiveDefenseBastionCharge - Skill DMG: {0}
	skill = []float64{
		1.66,
		1.7845,
		1.909,
		2.075,
		2.1995,
		2.324,
		2.49,
		2.656,
		2.822,
		2.988,
		3.154,
		3.32,
		3.5275,
		3.735,
		3.9425,
	}
	// skill: ActiveDefenseBastionCharge - Shield DMG Absorption: {1} ATK+{2}
	skillShieldAtk = []float64{
		2.08896,
		2.24563,
		2.4023,
		2.6112,
		2.76787,
		2.92454,
		3.13344,
		3.34234,
		3.55123,
		3.76013,
		3.96902,
		4.17792,
		4.43904,
		4.70016,
		4.96128,
	}
	// skill: ActiveDefenseBastionCharge - Shield DMG Absorption: {1} ATK+{2}
	skillShieldFlat = []float64{
		1309.638,
		1440.62,
		1582.518,
		1735.33,
		1899.058,
		2073.7,
		2259.258,
		2455.731,
		2663.119,
		2881.423,
		3110.641,
		3350.775,
		3601.824,
		3863.788,
		4136.667,
	}
	// burst: FocusedFireLightningSalvo - Skill DMG: {0}
	burst = []float64{
		1.3512,
		1.45254,
		1.55388,
		1.689,
		1.79034,
		1.89168,
		2.0268,
		2.16192,
		2.29704,
		2.43216,
		2.56728,
		2.7024,
		2.8713,
		3.0402,
		3.2091,
	}
	// burst: FocusedFireLightningSalvo - Thunderburst Shell DMG: {1}
	burstDot = []float64{
		0.3152,
		0.33884,
		0.36248,
		0.394,
		0.41764,
		0.44128,
		0.4728,
		0.50432,
		0.53584,
		0.56736,
		0.59888,
		0.6304,
		0.6698,
		0.7092,
		0.7486,
	}
)
