// Code generated by "pipeline"; DO NOT EDIT.

package kaveh

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Kaveh, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Kaveh, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SchematicSetup - 1-Hit DMG: {0}
			0.76186,
			0.82387,
			0.88588,
			0.97447,
			1.03648,
			1.10735,
			1.2048,
			1.30224,
			1.39969,
			1.506,
			1.6123,
			1.71861,
			1.82491,
			1.93122,
			2.03752,
		},
		{ // attack: SchematicSetup - 2-Hit DMG: {1}
			0.69639,
			0.75307,
			0.80975,
			0.89073,
			0.94741,
			1.01219,
			1.10126,
			1.19033,
			1.2794,
			1.37657,
			1.47374,
			1.57091,
			1.66808,
			1.76525,
			1.86242,
		},
		{ // attack: SchematicSetup - 3-Hit DMG: {2}
			0.84261,
			0.91119,
			0.97978,
			1.07776,
			1.14634,
			1.22473,
			1.3325,
			1.44028,
			1.54805,
			1.66563,
			1.7832,
			1.90077,
			2.01835,
			2.13592,
			2.25349,
		},
		{ // attack: SchematicSetup - 4-Hit DMG: {3}
			1.02688,
			1.11047,
			1.19405,
			1.31345,
			1.39704,
			1.49256,
			1.62391,
			1.75525,
			1.8866,
			2.02989,
			2.17317,
			2.31646,
			2.45974,
			2.60303,
			2.74632,
		},
	}
	// attack: SchematicSetup - Plunge DMG: {8}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: SchematicSetup - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: SchematicSetup - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: ArtisticIngenuity - Skill DMG: {0}
	skill = []float64{
		2.04,
		2.193,
		2.346,
		2.55,
		2.703,
		2.856,
		3.06,
		3.264,
		3.468,
		3.672,
		3.876,
		4.08,
		4.335,
		4.59,
		4.845,
	}
	// burst: PaintedDome - Skill DMG: {0}
	burst = []float64{
		1.6,
		1.72,
		1.84,
		2.0,
		2.12,
		2.24,
		2.4,
		2.56,
		2.72,
		2.88,
		3.04,
		3.2,
		3.4,
		3.6,
		3.8,
	}
	// burst: PaintedDome - Dendro Core Burst DMG Bonus: {2}
	burstDmgBonus = []float64{
		0.27488,
		0.2955,
		0.31611,
		0.3436,
		0.36422,
		0.38483,
		0.41232,
		0.43981,
		0.4673,
		0.49478,
		0.52227,
		0.54976,
		0.58412,
		0.61848,
		0.65284,
	}
)
