// Code generated by "pipeline"; DO NOT EDIT.

package navia

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Navia, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Navia, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][][]float64{
		{{ // attack: BluntRefusal - 1-Hit DMG: {0}
			0.93519,
			1.01131,
			1.08743,
			1.19617,
			1.27229,
			1.35929,
			1.4789,
			1.59852,
			1.71814,
			1.84863,
			1.97912,
			2.10961,
			2.24011,
			2.3706,
			2.50109,
		}},
		{{ // attack: BluntRefusal - 2-Hit DMG: {1}
			0.86506,
			0.93548,
			1.00589,
			1.10648,
			1.17689,
			1.25736,
			1.36801,
			1.47866,
			1.58931,
			1.71001,
			1.83072,
			1.95143,
			2.07213,
			2.19284,
			2.31355,
		}},
		{
			{ // attack: BluntRefusal - 3-Hit DMG: {2}×3
				0.34886,
				0.37725,
				0.40565,
				0.44622,
				0.47461,
				0.50706,
				0.55168,
				0.59631,
				0.64093,
				0.6896,
				0.73828,
				0.78696,
				0.83564,
				0.88432,
				0.933,
			},
			{ // attack: BluntRefusal - 3-Hit DMG: {2}×3
				0.34886,
				0.37725,
				0.40565,
				0.44622,
				0.47461,
				0.50706,
				0.55168,
				0.59631,
				0.64093,
				0.6896,
				0.73828,
				0.78696,
				0.83564,
				0.88432,
				0.933,
			},
			{ // attack: BluntRefusal - 3-Hit DMG: {2}×3
				0.34886,
				0.37725,
				0.40565,
				0.44622,
				0.47461,
				0.50706,
				0.55168,
				0.59631,
				0.64093,
				0.6896,
				0.73828,
				0.78696,
				0.83564,
				0.88432,
				0.933,
			},
		},
		{{ // attack: BluntRefusal - 4-Hit DMG: {3}
			1.33432,
			1.44292,
			1.55153,
			1.70668,
			1.81529,
			1.93941,
			2.11008,
			2.28075,
			2.45142,
			2.6376,
			2.82379,
			3.00997,
			3.19615,
			3.38233,
			3.56852,
		}},
	}
	// attack: BluntRefusal - Plunge DMG: {8}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: BluntRefusal - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: BluntRefusal - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: CeremonialCrystalshot - Rosula Shardshot Base DMG: {0}
	skillshotgun = []float64{
		3.948,
		4.2441,
		4.5402,
		4.935,
		5.2311,
		5.5272,
		5.922,
		6.3168,
		6.7116,
		7.1064,
		7.5012,
		7.896,
		8.3895,
		8.883,
		9.3765,
	}
	// skill: CeremonialCrystalshot - Surging Blade DMG: {4}
	skillblade = []float64{
		0.36,
		0.387,
		0.414,
		0.45,
		0.477,
		0.504,
		0.54,
		0.576,
		0.612,
		0.648,
		0.684,
		0.72,
		0.765,
		0.81,
		0.855,
	}
	burst = [][]float64{
		{ // burst: AsTheSunlitSkysSingingSalute - Skill DMG: {0}
			0.752,
			0.8084,
			0.8648,
			0.94,
			0.9964,
			1.0528,
			1.128,
			1.2032,
			1.2784,
			1.3536,
			1.4288,
			1.504,
			1.598,
			1.692,
			1.786,
		},
		{ // burst: AsTheSunlitSkysSingingSalute - Cannon Fire Support DMG: {1}
			0.4315,
			0.46386,
			0.49622,
			0.53938,
			0.57174,
			0.6041,
			0.64725,
			0.6904,
			0.73355,
			0.7767,
			0.81985,
			0.863,
			0.91694,
			0.97088,
			1.02481,
		},
	}
)
