// Code generated by "pipeline"; DO NOT EDIT.

package kazuha

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.KaedeharaKazuha, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"glide_cancel", "hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.KaedeharaKazuha, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: GaryuuBladework - 1-Hit DMG: {0}
			0.44978,
			0.48639,
			0.523,
			0.5753,
			0.61191,
			0.65375,
			0.71128,
			0.76881,
			0.82634,
			0.8891,
			0.96101,
			1.04558,
			1.13015,
			1.21472,
			1.30698,
		}},
		{{ // attack: GaryuuBladework - 2-Hit DMG: {1}
			0.45236,
			0.48918,
			0.526,
			0.5786,
			0.61542,
			0.6575,
			0.71536,
			0.77322,
			0.83108,
			0.8942,
			0.96653,
			1.05158,
			1.13663,
			1.22169,
			1.31447,
		}},
		{
			{ // attack: GaryuuBladework - 3-Hit DMG: {2}+{3}
				0.258,
				0.279,
				0.3,
				0.33,
				0.351,
				0.375,
				0.408,
				0.441,
				0.474,
				0.51,
				0.55125,
				0.59976,
				0.64827,
				0.69678,
				0.7497,
			},
			{ // attack: GaryuuBladework - 3-Hit DMG: {2}+{3}
				0.3096,
				0.3348,
				0.36,
				0.396,
				0.4212,
				0.45,
				0.4896,
				0.5292,
				0.5688,
				0.612,
				0.6615,
				0.71971,
				0.77792,
				0.83614,
				0.89964,
			},
		},
		{{ // attack: GaryuuBladework - 4-Hit DMG: {4}
			0.60716,
			0.65658,
			0.706,
			0.7766,
			0.82602,
			0.8825,
			0.96016,
			1.03782,
			1.11548,
			1.2002,
			1.29727,
			1.41144,
			1.52559,
			1.63976,
			1.76429,
		}},
		{
			{ // attack: GaryuuBladework - 5-Hit DMG: {5}×3
				0.2537,
				0.27435,
				0.295,
				0.3245,
				0.34515,
				0.36875,
				0.4012,
				0.43365,
				0.4661,
				0.5015,
				0.54206,
				0.58976,
				0.63747,
				0.68517,
				0.73721,
			},
			{ // attack: GaryuuBladework - 5-Hit DMG: {5}×3
				0.2537,
				0.27435,
				0.295,
				0.3245,
				0.34515,
				0.36875,
				0.4012,
				0.43365,
				0.4661,
				0.5015,
				0.54206,
				0.58976,
				0.63747,
				0.68517,
				0.73721,
			},
			{ // attack: GaryuuBladework - 5-Hit DMG: {5}×3
				0.2537,
				0.27435,
				0.295,
				0.3245,
				0.34515,
				0.36875,
				0.4012,
				0.43365,
				0.4661,
				0.5015,
				0.54206,
				0.58976,
				0.63747,
				0.68517,
				0.73721,
			},
		},
	}
	charge = [][]float64{
		{ // attack: GaryuuBladework - Charged Attack DMG: {6}+{7}
			0.43,
			0.465,
			0.5,
			0.55,
			0.585,
			0.625,
			0.68,
			0.735,
			0.79,
			0.85,
			0.91875,
			0.9996,
			1.08045,
			1.1613,
			1.2495,
		},
		{ // attack: GaryuuBladework - Charged Attack DMG: {6}+{7}
			0.74648,
			0.80724,
			0.868,
			0.9548,
			1.01556,
			1.085,
			1.18048,
			1.27596,
			1.37144,
			1.4756,
			1.59495,
			1.73531,
			1.87566,
			2.01602,
			2.16913,
		},
	}
	// attack: GaryuuBladework - Plunge DMG: {9}
	collision = []float64{
		0.81833,
		0.88494,
		0.95155,
		1.04671,
		1.11332,
		1.18944,
		1.29411,
		1.39878,
		1.50345,
		1.61764,
		1.73182,
		1.84601,
		1.9602,
		2.07438,
		2.18857,
	}
	// attack: GaryuuBladework - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.63632,
		1.76951,
		1.9027,
		2.09297,
		2.22616,
		2.37838,
		2.58767,
		2.79697,
		3.00627,
		3.23459,
		3.46291,
		3.69124,
		3.91956,
		4.14789,
		4.37621,
	}
	// attack: GaryuuBladework - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		2.04385,
		2.21022,
		2.37658,
		2.61423,
		2.78059,
		2.97072,
		3.23214,
		3.49357,
		3.75499,
		4.04018,
		4.32537,
		4.61056,
		4.89575,
		5.18094,
		5.46613,
	}
	// skill: Chihayaburu - Press Skill DMG: {0}
	skill = []float64{
		1.92,
		2.064,
		2.208,
		2.4,
		2.544,
		2.688,
		2.88,
		3.072,
		3.264,
		3.456,
		3.648,
		3.84,
		4.08,
		4.32,
		4.56,
	}
	// skill: Chihayaburu - Hold Skill DMG: {2}
	skillHold = []float64{
		2.608,
		2.8036,
		2.9992,
		3.26,
		3.4556,
		3.6512,
		3.912,
		4.1728,
		4.4336,
		4.6944,
		4.9552,
		5.216,
		5.542,
		5.868,
		6.194,
	}
	// burst: KazuhaSlash - Slashing DMG: {0}
	burstSlash = []float64{
		2.624,
		2.8208,
		3.0176,
		3.28,
		3.4768,
		3.6736,
		3.936,
		4.1984,
		4.4608,
		4.7232,
		4.9856,
		5.248,
		5.576,
		5.904,
		6.232,
	}
	// burst: KazuhaSlash - DoT: {1}
	burstDot = []float64{
		1.2,
		1.29,
		1.38,
		1.5,
		1.59,
		1.68,
		1.8,
		1.92,
		2.04,
		2.16,
		2.28,
		2.4,
		2.55,
		2.7,
		2.85,
	}
	// burst: KazuhaSlash - Additional Elemental DMG: {2}
	burstEleDot = []float64{
		0.36,
		0.387,
		0.414,
		0.45,
		0.477,
		0.504,
		0.54,
		0.576,
		0.612,
		0.648,
		0.684,
		0.72,
		0.765,
		0.81,
		0.855,
	}
)
