// Code generated by "pipeline"; DO NOT EDIT.

package sigewinne

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Sigewinne, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
		action.ActionSkill:  {"hold"},
		action.ActionBurst:  {"ticks"},
		action.ActionDash:   {"pickup_droplets"},
	}
	validation.RegisterCharParamValidationFunc(keys.Sigewinne, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	finalBounceHealing  = 0.5 // skill: ReboundHydrotherapy - Final Bounce Healing: {3} Max HP
	suringBladeInterval = 10  // skill: ReboundHydrotherapy - Surging Blade Interval: {7}s
)

var (
	attack = [][]float64{
		{ // attack: TargetedTreatment - 1-Hit DMG: {0}
			0.52614,
			0.56897,
			0.61179,
			0.67297,
			0.71579,
			0.76474,
			0.83203,
			0.89933,
			0.96663,
			1.04004,
			1.11346,
			1.18687,
			1.26029,
			1.3337,
			1.40712,
		},
		{ // attack: TargetedTreatment - 2-Hit DMG: {1}
			0.51071,
			0.55228,
			0.59385,
			0.65324,
			0.6948,
			0.74231,
			0.80764,
			0.87296,
			0.93828,
			1.00954,
			1.08081,
			1.15207,
			1.22333,
			1.29459,
			1.36585,
		},
		{ // attack: TargetedTreatment - 3-Hit DMG: {2}
			0.78291,
			0.84663,
			0.91036,
			1.0014,
			1.06512,
			1.13795,
			1.23809,
			1.33823,
			1.43837,
			1.54761,
			1.65685,
			1.7661,
			1.87534,
			1.98459,
			2.09383,
		},
	}
	// attack: TargetedTreatment - Aimed Shot: {6}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: TargetedTreatment - Fully-Charged Aimed Shot: {7}
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// attack: TargetedTreatment - Mini-Stration Bubble DMG: {8}
	miniStrationBubbleDMG = []float64{
		0.248,
		0.2666,
		0.2852,
		0.31,
		0.3286,
		0.3472,
		0.372,
		0.3968,
		0.4216,
		0.4464,
		0.4712,
		0.496,
		0.527,
		0.558,
		0.589,
	}
	// skill: ReboundHydrotherapy - Bolstering Bubblebalm DMG: {0} Max HP
	bolsteringBubblebalmDMG = []float64{
		0.0228,
		0.02451,
		0.02622,
		0.0285,
		0.03021,
		0.03192,
		0.0342,
		0.03648,
		0.03876,
		0.04104,
		0.04332,
		0.0456,
		0.04845,
		0.0513,
		0.05415,
	}
	// skill: ReboundHydrotherapy - Bolstering Bubblebalm Healing: {1} Max HP+{2}
	bolsteringBubblebalmHealingPct = []float64{
		0.028,
		0.0301,
		0.0322,
		0.035,
		0.0371,
		0.0392,
		0.042,
		0.0448,
		0.0476,
		0.0504,
		0.0532,
		0.056,
		0.0595,
		0.063,
		0.0665,
	}
	// skill: ReboundHydrotherapy - Bolstering Bubblebalm Healing: {1} Max HP+{2}
	bolsteringBubblebalmHealingFlat = []float64{
		269.6314,
		296.5983,
		325.8124,
		357.2738,
		390.9824,
		426.9383,
		465.1414,
		505.5917,
		548.2893,
		593.2341,
		640.4262,
		689.8654,
		741.5519,
		795.4857,
		851.6668,
	}
	// skill: ReboundHydrotherapy - Surging Blade DMG: {6} Max HP
	surgingBladeDMG = []float64{
		0.00684,
		0.00735,
		0.00787,
		0.00855,
		0.00906,
		0.00958,
		0.01026,
		0.01094,
		0.01163,
		0.01231,
		0.013,
		0.01368,
		0.01453,
		0.01539,
		0.01625,
	}
	// burst: SuperSaturatedSyringing - Skill DMG: {0} Max HP
	burstDMG = []float64{
		0.11771,
		0.12654,
		0.13536,
		0.14714,
		0.15596,
		0.16479,
		0.17656,
		0.18833,
		0.2001,
		0.21187,
		0.22365,
		0.23542,
		0.25013,
		0.26484,
		0.27956,
	}
)
