// Code generated by "pipeline"; DO NOT EDIT.

package arlecchino

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Arlecchino, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionCharge:     {"early_cancel"},
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Arlecchino, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: InvitationToABeheading - 1-Hit DMG: {0}
			0.475,
			0.51367,
			0.55233,
			0.60756,
			0.64623,
			0.69041,
			0.75117,
			0.81192,
			0.87268,
			0.93896,
			1.00524,
			1.07152,
			1.1378,
			1.20408,
			1.27036,
		}},
		{{ // attack: InvitationToABeheading - 2-Hit DMG: {1}
			0.52106,
			0.56347,
			0.60588,
			0.66647,
			0.70888,
			0.75735,
			0.824,
			0.89064,
			0.95729,
			1.03,
			1.1027,
			1.17541,
			1.24811,
			1.32082,
			1.39352,
		}},
		{{ // attack: InvitationToABeheading - 3-Hit DMG: {2}
			0.65386,
			0.70708,
			0.7603,
			0.83633,
			0.88955,
			0.95038,
			1.03401,
			1.11764,
			1.20127,
			1.29251,
			1.38375,
			1.47498,
			1.56622,
			1.65745,
			1.74869,
		}},
		{
			{ // attack: InvitationToABeheading - 4-Hit DMG: {3}+{3}
				0.37145,
				0.40169,
				0.43192,
				0.47511,
				0.50535,
				0.5399,
				0.58741,
				0.63492,
				0.68243,
				0.73426,
				0.78609,
				0.83793,
				0.88976,
				0.94159,
				0.99342,
			},
			{ // attack: InvitationToABeheading - 4-Hit DMG: {3}+{3}
				0.37145,
				0.40169,
				0.43192,
				0.47511,
				0.50535,
				0.5399,
				0.58741,
				0.63492,
				0.68243,
				0.73426,
				0.78609,
				0.83793,
				0.88976,
				0.94159,
				0.99342,
			},
		},
		{{ // attack: InvitationToABeheading - 5-Hit DMG: {4}
			0.69982,
			0.75678,
			0.81374,
			0.89511,
			0.95208,
			1.01717,
			1.10669,
			1.1962,
			1.28571,
			1.38336,
			1.48101,
			1.57866,
			1.6763,
			1.77395,
			1.8716,
		}},
		{{ // attack: InvitationToABeheading - 6-Hit DMG: {5}
			0.85378,
			0.92328,
			0.99277,
			1.09205,
			1.16154,
			1.24096,
			1.35017,
			1.45937,
			1.56858,
			1.68771,
			1.80684,
			1.92597,
			2.04511,
			2.16424,
			2.28337,
		}},
	}
	// attack: InvitationToABeheading - Charged Attack DMG: {6}
	charge = []float64{
		0.90816,
		0.98208,
		1.056,
		1.1616,
		1.23552,
		1.32,
		1.43616,
		1.55232,
		1.66848,
		1.7952,
		1.92192,
		2.04864,
		2.17536,
		2.30208,
		2.4288,
	}
	// attack: InvitationToABeheading - Plunge DMG: {8}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: InvitationToABeheading - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: InvitationToABeheading - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// attack: InvitationToABeheading - Masque of the Red Death Increase: {11}
	masque = []float64{
		1.204,
		1.302,
		1.4,
		1.54,
		1.638,
		1.75,
		1.904,
		2.058,
		2.212,
		2.38,
		2.548,
		2.716,
		2.884,
		3.052,
		3.22,
	}
	// skill: AllIsAsh - Spike DMG: {0}
	skillSpike = []float64{
		0.1484,
		0.15953,
		0.17066,
		0.1855,
		0.19663,
		0.20776,
		0.2226,
		0.23744,
		0.25228,
		0.26712,
		0.28196,
		0.2968,
		0.31535,
		0.3339,
		0.35245,
	}
	// skill: AllIsAsh - Cleave DMG: {1}
	skillFinal = []float64{
		1.3356,
		1.43577,
		1.53594,
		1.6695,
		1.76967,
		1.86984,
		2.0034,
		2.13696,
		2.27052,
		2.40408,
		2.53764,
		2.6712,
		2.83815,
		3.0051,
		3.17205,
	}
	// skill: AllIsAsh - Blood-Debt Directive DMG: {2}
	skillSigil = []float64{
		0.318,
		0.34185,
		0.3657,
		0.3975,
		0.42135,
		0.4452,
		0.477,
		0.5088,
		0.5406,
		0.5724,
		0.6042,
		0.636,
		0.67575,
		0.7155,
		0.75525,
	}
	// burst: BalemoonRising - Skill DMG: {0}
	burst = []float64{
		3.704,
		3.9818,
		4.2596,
		4.63,
		4.9078,
		5.1856,
		5.556,
		5.9264,
		6.2968,
		6.6672,
		7.0376,
		7.408,
		7.871,
		8.334,
		8.797,
	}
)
