// Code generated by "pipeline"; DO NOT EDIT.

package chasca

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Chasca, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack:    {"travel"},
		action.ActionAim:       {"bullets", "hold", "travel", "weakspot"},
		action.ActionLowPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Chasca, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: PhantomFeatherFlurry - 1-Hit DMG: {0}
			0.48008,
			0.51915,
			0.55823,
			0.61405,
			0.65313,
			0.69779,
			0.75919,
			0.8206,
			0.882,
			0.94899,
			1.01598,
			1.08297,
			1.14995,
			1.21694,
			1.28393,
		},
		{ // attack: PhantomFeatherFlurry - 2-Hit DMG: {1}
			0.44588,
			0.48218,
			0.51847,
			0.57032,
			0.60661,
			0.64809,
			0.70512,
			0.76215,
			0.81918,
			0.8814,
			0.94362,
			1.00583,
			1.06805,
			1.13026,
			1.19248,
		},
		{ // attack: PhantomFeatherFlurry - 3-Hit DMG: {2}×2
			0.29697,
			0.32115,
			0.34532,
			0.37985,
			0.40402,
			0.43165,
			0.46964,
			0.50762,
			0.54561,
			0.58704,
			0.62848,
			0.66992,
			0.71136,
			0.7528,
			0.79424,
		},
		{ // attack: PhantomFeatherFlurry - 4-Hit DMG: {3}×3
			0.25467,
			0.2754,
			0.29613,
			0.32574,
			0.34647,
			0.37016,
			0.40274,
			0.43531,
			0.46788,
			0.50342,
			0.53896,
			0.57449,
			0.61003,
			0.64556,
			0.6811,
		},
	}
	// attack: PhantomFeatherFlurry - Aimed Shot: {4}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: PhantomFeatherFlurry - Fully-Charged Aimed Shot: {5}
	fullAim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// attack: PhantomFeatherFlurry - Plunge DMG: {6}
	plunge = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: PhantomFeatherFlurry - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// skill: SpiritReinsShadowHunt - Resonance DMG: {0}
	skillResonance = []float64{
		0.6,
		0.645,
		0.69,
		0.75,
		0.795,
		0.84,
		0.9,
		0.96,
		1.02,
		1.08,
		1.14,
		1.2,
		1.275,
		1.35,
		1.425,
	}
	// skill: SpiritReinsShadowHunt - Multitarget Fire Tap DMG: {1}
	skillNA = []float64{
		0.36,
		0.387,
		0.414,
		0.45,
		0.477,
		0.504,
		0.54,
		0.576,
		0.612,
		0.648,
		0.684,
		0.72,
		0.765,
		0.81,
		0.855,
	}
	// skill: SpiritReinsShadowHunt - Shadowhunt Shell DMG: {2}
	skillShadowhunt = []float64{
		0.488,
		0.5246,
		0.5612,
		0.61,
		0.6466,
		0.6832,
		0.732,
		0.7808,
		0.8296,
		0.8784,
		0.9272,
		0.976,
		1.037,
		1.098,
		1.159,
	}
	// skill: SpiritReinsShadowHunt - Shining Shadowhunt Shell DMG: {3}
	skillShining = []float64{
		1.66572,
		1.79065,
		1.91558,
		2.08215,
		2.20708,
		2.33201,
		2.49858,
		2.66515,
		2.83172,
		2.9983,
		3.16487,
		3.33144,
		3.53965,
		3.74787,
		3.95608,
	}
	// burst: SoulReapersFatalRound - Galesplitting Soulseeker Shell DMG: {0}
	burstGalesplitting = []float64{
		0.88,
		0.946,
		1.012,
		1.1,
		1.166,
		1.232,
		1.32,
		1.408,
		1.496,
		1.584,
		1.672,
		1.76,
		1.87,
		1.98,
		2.09,
	}
	// burst: SoulReapersFatalRound - Soulseeker Shell DMG: {1}
	burstSoulseeker = []float64{
		1.034,
		1.11155,
		1.1891,
		1.2925,
		1.37005,
		1.4476,
		1.551,
		1.6544,
		1.7578,
		1.8612,
		1.9646,
		2.068,
		2.19725,
		2.3265,
		2.45575,
	}
	// burst: SoulReapersFatalRound - Radiant Soulseeker Shell DMG: {2}
	burstRadiant = []float64{
		2.068,
		2.2231,
		2.3782,
		2.585,
		2.7401,
		2.8952,
		3.102,
		3.3088,
		3.5156,
		3.7224,
		3.9292,
		4.136,
		4.3945,
		4.653,
		4.9115,
	}
)
