// Code generated by "pipeline"; DO NOT EDIT.

package gaming

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Gaming, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision", "man_chai_delay"},
		action.ActionHighPlunge: {"collision", "man_chai_delay"},
		action.ActionBurst:      {"man_chai_delay"},
	}
	validation.RegisterCharParamValidationFunc(keys.Gaming, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: StellarRend - 1-Hit DMG: {0}
			0.83856,
			0.90681,
			0.97507,
			1.07258,
			1.14083,
			1.21884,
			1.32609,
			1.43335,
			1.54061,
			1.65762,
			1.77463,
			1.89164,
			2.00864,
			2.12565,
			2.24266,
		},
		{ // attack: StellarRend - 2-Hit DMG: {1}
			0.79044,
			0.85478,
			0.91912,
			1.01103,
			1.07537,
			1.1489,
			1.25,
			1.35111,
			1.45221,
			1.5625,
			1.6728,
			1.78309,
			1.89339,
			2.00368,
			2.11398,
		},
		{ // attack: StellarRend - 3-Hit DMG: {2}
			1.06646,
			1.15326,
			1.24007,
			1.36408,
			1.45088,
			1.55009,
			1.68649,
			1.8229,
			1.95931,
			2.10812,
			2.25693,
			2.40574,
			2.55454,
			2.70335,
			2.85216,
		},
		{ // attack: StellarRend - 4-Hit DMG: {3}
			1.27949,
			1.38364,
			1.48778,
			1.63656,
			1.7407,
			1.85972,
			2.02338,
			2.18704,
			2.35069,
			2.52923,
			2.70776,
			2.88629,
			3.06483,
			3.24336,
			3.42189,
		},
	}
	// attack: StellarRend - Plunge DMG: {8}
	collision = []float64{
		0.64146,
		0.69367,
		0.74588,
		0.82047,
		0.87268,
		0.93235,
		1.0144,
		1.09644,
		1.17849,
		1.268,
		1.3575,
		1.44701,
		1.53651,
		1.62602,
		1.71552,
	}
	// attack: StellarRend - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.28264,
		1.38704,
		1.49144,
		1.64058,
		1.74498,
		1.8643,
		2.02836,
		2.19242,
		2.35648,
		2.53545,
		2.71442,
		2.89339,
		3.07237,
		3.25134,
		3.43031,
	}
	// attack: StellarRend - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.60208,
		1.73249,
		1.86289,
		2.04918,
		2.17958,
		2.32861,
		2.53353,
		2.73845,
		2.94337,
		3.16691,
		3.39046,
		3.61401,
		3.83755,
		4.0611,
		4.28465,
	}
	// skill: BestialAscent - Plunging Attack: Charmed Cloudstrider DMG: {0}
	skill = []float64{
		2.304,
		2.4768,
		2.6496,
		2.88,
		3.0528,
		3.2256,
		3.456,
		3.6864,
		3.9168,
		4.1472,
		4.3776,
		4.608,
		4.896,
		5.184,
		5.472,
	}
	// burst: SuannisGildedDance - Suanni Man Chai Smash DMG: {0}
	burst = []float64{
		3.704,
		3.9818,
		4.2596,
		4.63,
		4.9078,
		5.1856,
		5.556,
		5.9264,
		6.2968,
		6.6672,
		7.0376,
		7.408,
		7.871,
		8.334,
		8.797,
	}
)
