// Code generated by "pipeline"; DO NOT EDIT.

package dehya

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Dehya, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Dehya, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SandstormAssault - 1-Hit DMG: {0}
			0.62118,
			0.67174,
			0.7223,
			0.79453,
			0.84509,
			0.90288,
			0.98233,
			1.06178,
			1.14123,
			1.22791,
			1.31459,
			1.40126,
			1.48794,
			1.57461,
			1.66129,
		},
		{ // attack: SandstormAssault - 2-Hit DMG: {1}
			0.6171,
			0.66733,
			0.71756,
			0.78932,
			0.83955,
			0.89695,
			0.97588,
			1.05481,
			1.13374,
			1.21985,
			1.30596,
			1.39207,
			1.47817,
			1.56428,
			1.65039,
		},
		{ // attack: SandstormAssault - 3-Hit DMG: {2}
			0.76631,
			0.82869,
			0.89106,
			0.98017,
			1.04254,
			1.11382,
			1.21184,
			1.30986,
			1.40787,
			1.5148,
			1.62173,
			1.72866,
			1.83558,
			1.94251,
			2.04944,
		},
		{ // attack: SandstormAssault - 4-Hit DMG: {3}
			0.95291,
			1.03048,
			1.10804,
			1.21884,
			1.29641,
			1.38505,
			1.50693,
			1.62882,
			1.7507,
			1.88367,
			2.01663,
			2.1496,
			2.28256,
			2.41553,
			2.54849,
		},
	}
	// attack: SandstormAssault - Plunge DMG: {8}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: SandstormAssault - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: SandstormAssault - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: MoltenInferno - Indomitable Flame DMG: {0}
	skill = []float64{
		1.1288,
		1.21346,
		1.29812,
		1.411,
		1.49566,
		1.58032,
		1.6932,
		1.80608,
		1.91896,
		2.03184,
		2.14472,
		2.2576,
		2.3987,
		2.5398,
		2.6809,
	}
	// skill: MoltenInferno - Ranging Flame DMG: {1}
	skillReposition = []float64{
		1.328,
		1.4276,
		1.5272,
		1.66,
		1.7596,
		1.8592,
		1.992,
		2.1248,
		2.2576,
		2.3904,
		2.5232,
		2.656,
		2.822,
		2.988,
		3.154,
	}
	// skill: MoltenInferno - Field DMG: {2} ATK+{3} Max HP
	skillDotAtk = []float64{
		0.602,
		0.64715,
		0.6923,
		0.7525,
		0.79765,
		0.8428,
		0.903,
		0.9632,
		1.0234,
		1.0836,
		1.1438,
		1.204,
		1.27925,
		1.3545,
		1.42975,
	}
	// skill: MoltenInferno - Field DMG: {2} ATK+{3} Max HP
	skillDotHP = []float64{
		0.01032,
		0.01109,
		0.01187,
		0.0129,
		0.01367,
		0.01445,
		0.01548,
		0.01651,
		0.01754,
		0.01858,
		0.01961,
		0.02064,
		0.02193,
		0.02322,
		0.02451,
	}
	// skill: MoltenInferno - Mitigation: {4}
	skillMitigation = []float64{
		0.32,
		0.34,
		0.36,
		0.38,
		0.4,
		0.42,
		0.44,
		0.46,
		0.48,
		0.5,
		0.52,
		0.54,
		0.56,
		0.56,
		0.56,
	}
	// burst: LeonineBite - Flame-Mane's Fist DMG: {0} ATK+{1} Max HP
	burstPunchAtk = []float64{
		0.987,
		1.06103,
		1.13505,
		1.23375,
		1.30778,
		1.3818,
		1.4805,
		1.5792,
		1.6779,
		1.7766,
		1.8753,
		1.974,
		2.09737,
		2.22075,
		2.34413,
	}
	// burst: LeonineBite - Flame-Mane's Fist DMG: {0} ATK+{1} Max HP
	burstPunchHP = []float64{
		0.01692,
		0.01819,
		0.01946,
		0.02115,
		0.02242,
		0.02369,
		0.02538,
		0.02707,
		0.02876,
		0.03046,
		0.03215,
		0.03384,
		0.03596,
		0.03807,
		0.04019,
	}
	// burst: LeonineBite - Incineration Drive DMG: {2} ATK+{3} Max HP
	burstKickAtk = []float64{
		1.393,
		1.49748,
		1.60195,
		1.74125,
		1.84573,
		1.9502,
		2.0895,
		2.2288,
		2.3681,
		2.5074,
		2.6467,
		2.786,
		2.96012,
		3.13425,
		3.30837,
	}
	// burst: LeonineBite - Incineration Drive DMG: {2} ATK+{3} Max HP
	burstKickHP = []float64{
		0.02388,
		0.02567,
		0.02746,
		0.02985,
		0.03164,
		0.03343,
		0.03582,
		0.03821,
		0.0406,
		0.04298,
		0.04537,
		0.04776,
		0.05074,
		0.05373,
		0.05672,
	}
)
