// Code generated by "pipeline"; DO NOT EDIT.

package escoffier

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Escoffier, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Escoffier, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	skillDur    = 20 // skill: LowTemperatureCooking - Cold Storage Mode Duration: {2}s
	burstCD     = 15 // burst: ScoringCuts - CD: {3}s
	burstEnergy = 60 // burst: ScoringCuts - Energy Cost: {4}
)

var (
	attack = [][][]float64{
		{{ // attack: KitchenSkills - 1-Hit DMG: {0}
			0.51551,
			0.55747,
			0.59943,
			0.65937,
			0.70133,
			0.74929,
			0.81523,
			0.88116,
			0.9471,
			1.01903,
			1.09096,
			1.16289,
			1.23483,
			1.30676,
			1.37869,
		}},
		{{ // attack: KitchenSkills - 2-Hit DMG: {1}
			0.47593,
			0.51467,
			0.55341,
			0.60875,
			0.64749,
			0.69176,
			0.75264,
			0.81351,
			0.87439,
			0.9408,
			1.00721,
			1.07361,
			1.14003,
			1.20643,
			1.27284,
		}},
		{
			{ // attack: KitchenSkills - 3-Hit DMG: {2}+{3}
				0.33,
				0.35686,
				0.38372,
				0.42209,
				0.44895,
				0.47964,
				0.52185,
				0.56406,
				0.60627,
				0.65232,
				0.69836,
				0.74441,
				0.79045,
				0.8365,
				0.88254,
			},
			{ // attack: KitchenSkills - 3-Hit DMG: {2}+{3}
				0.40333,
				0.43616,
				0.46898,
				0.51588,
				0.54871,
				0.58623,
				0.63782,
				0.68941,
				0.741,
				0.79727,
				0.85355,
				0.90983,
				0.96611,
				1.02239,
				1.07867,
			},
		},
	}
	// attack: KitchenSkills - Charged Attack DMG: {4}
	charge = []float64{
		1.15412,
		1.24806,
		1.342,
		1.4762,
		1.57014,
		1.6775,
		1.82512,
		1.97274,
		2.12036,
		2.2814,
		2.44244,
		2.60348,
		2.76452,
		2.92556,
		3.0866,
	}
	// attack: KitchenSkills - Plunge DMG: {6}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: KitchenSkills - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: KitchenSkills - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: LowTemperatureCooking - Skill DMG: {0}
	skillInital = []float64{
		0.504,
		0.5418,
		0.5796,
		0.63,
		0.6678,
		0.7056,
		0.756,
		0.8064,
		0.8568,
		0.9072,
		0.9576,
		1.008,
		1.071,
		1.134,
		1.197,
	}
	// skill: LowTemperatureCooking - Frosty Parfait DMG: {1}
	skillDot = []float64{
		1.2,
		1.29,
		1.38,
		1.5,
		1.59,
		1.68,
		1.8,
		1.92,
		2.04,
		2.16,
		2.28,
		2.4,
		2.55,
		2.7,
		2.85,
	}
	// skill: LowTemperatureCooking - Surging Blade DMG: {3}
	arkhe = []float64{
		0.336,
		0.3612,
		0.3864,
		0.42,
		0.4452,
		0.4704,
		0.504,
		0.5376,
		0.5712,
		0.6048,
		0.6384,
		0.672,
		0.714,
		0.756,
		0.798,
	}
	// burst: ScoringCuts - Skill DMG: {0}
	burst = []float64{
		5.928,
		6.3726,
		6.8172,
		7.41,
		7.8546,
		8.2992,
		8.892,
		9.4848,
		10.0776,
		10.6704,
		11.2632,
		11.856,
		12.597,
		13.338,
		14.079,
	}
	// burst: ScoringCuts - Healing: {1} ATK+{2}
	burstHealPer = []float64{
		1.72032,
		1.84934,
		1.97837,
		2.1504,
		2.27942,
		2.40845,
		2.58048,
		2.75251,
		2.92454,
		3.09658,
		3.26861,
		3.44064,
		3.65568,
		3.87072,
		4.08576,
	}
	// burst: ScoringCuts - Healing: {1} ATK+{2}
	burstHealFlat = []float64{
		1078.526,
		1186.393,
		1303.25,
		1429.095,
		1563.929,
		1707.753,
		1860.565,
		2022.366,
		2193.157,
		2372.936,
		2561.704,
		2759.461,
		2966.208,
		3181.943,
		3406.667,
	}
)
