// Code generated by "pipeline"; DO NOT EDIT.

package dori

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Dori, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"travel"},
		action.ActionBurst:      {"c2_travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Dori, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][][]float64{
		{{ // attack: MarvelousSwordDanceModified - 1-Hit DMG: {0}
			0.90214,
			0.97557,
			1.049,
			1.1539,
			1.22733,
			1.31125,
			1.42664,
			1.54203,
			1.65742,
			1.7833,
			1.90918,
			2.03506,
			2.16094,
			2.28682,
			2.4127,
		}},
		{
			{ // attack: MarvelousSwordDanceModified - 2-Hit DMG: {1}+{2}
				0.41074,
				0.44417,
				0.4776,
				0.52536,
				0.55879,
				0.597,
				0.64954,
				0.70207,
				0.75461,
				0.81192,
				0.86923,
				0.92654,
				0.98386,
				1.04117,
				1.09848,
			},
			{ // attack: MarvelousSwordDanceModified - 2-Hit DMG: {1}+{2}
				0.4312,
				0.4663,
				0.5014,
				0.55154,
				0.58664,
				0.62675,
				0.6819,
				0.73706,
				0.79221,
				0.85238,
				0.91255,
				0.97272,
				1.03288,
				1.09305,
				1.15322,
			},
		},
		{{ // attack: MarvelousSwordDanceModified - 3-Hit DMG: {3}
			1.28398,
			1.38849,
			1.493,
			1.6423,
			1.74681,
			1.86625,
			2.03048,
			2.19471,
			2.35894,
			2.5381,
			2.71726,
			2.89642,
			3.07558,
			3.25474,
			3.4339,
		}},
	}
	// attack: MarvelousSwordDanceModified - Plunge DMG: {8}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: MarvelousSwordDanceModified - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: MarvelousSwordDanceModified - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: SpiritWardingLampTroubleshooterCannon - Troubleshooter Shot DMG: {0}
	skill = []float64{
		1.4728,
		1.58326,
		1.69372,
		1.841,
		1.95146,
		2.06192,
		2.2092,
		2.35648,
		2.50376,
		2.65104,
		2.79832,
		2.9456,
		3.1297,
		3.3138,
		3.4979,
	}
	// skill: SpiritWardingLampTroubleshooterCannon - After-Sales Service Round DMG: {1}
	skillAfter = []float64{
		0.3156,
		0.33927,
		0.36294,
		0.3945,
		0.41817,
		0.44184,
		0.4734,
		0.50496,
		0.53652,
		0.56808,
		0.59964,
		0.6312,
		0.67065,
		0.7101,
		0.74955,
	}
	// burst: AlcazarzaraysExactitude - Connector DMG: {0}
	burst = []float64{
		0.15882,
		0.17074,
		0.18265,
		0.19853,
		0.21044,
		0.22235,
		0.23824,
		0.25412,
		0.27,
		0.28588,
		0.30177,
		0.31765,
		0.3375,
		0.35735,
		0.37721,
	}
	// burst: AlcazarzaraysExactitude - Continuous Healing: {1} Max HP+{2}
	bursthealpp = []float64{
		0.0667,
		0.0717,
		0.07671,
		0.08337,
		0.08838,
		0.09338,
		0.10005,
		0.10672,
		0.11339,
		0.12006,
		0.12673,
		0.1334,
		0.14174,
		0.15008,
		0.15841,
	}
	// burst: AlcazarzaraysExactitude - Continuous Healing: {1} Max HP+{2}
	bursthealflat = []float64{
		641.9796,
		706.1865,
		775.7439,
		850.6519,
		930.9105,
		1016.52,
		1107.479,
		1203.79,
		1305.451,
		1412.462,
		1524.824,
		1642.537,
		1765.6,
		1894.014,
		2027.778,
	}
	// burst: AlcazarzaraysExactitude - Energy Regeneration: {3}
	burstenergy = []float64{
		1.6,
		1.7,
		1.8,
		1.9,
		2.0,
		2.1,
		2.2,
		2.3,
		2.4,
		2.5,
		2.5,
		2.5,
		2.5,
		2.5,
		2.5,
	}
)
