// Code generated by "pipeline"; DO NOT EDIT.

package charlotte

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Charlotte, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Charlotte, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: CoolColorCapture - 1-Hit DMG: {0}
			0.49846,
			0.53584,
			0.57322,
			0.62307,
			0.66045,
			0.69784,
			0.74768,
			0.79753,
			0.84737,
			0.89722,
			0.94707,
			0.99691,
			1.05922,
			1.12153,
			1.18383,
		},
		{ // attack: CoolColorCapture - 2-Hit DMG: {1}
			0.43375,
			0.46628,
			0.49882,
			0.54219,
			0.57472,
			0.60725,
			0.65063,
			0.694,
			0.73738,
			0.78075,
			0.82413,
			0.8675,
			0.92172,
			0.97594,
			1.03016,
		},
		{ // attack: CoolColorCapture - 3-Hit DMG: {2}
			0.64601,
			0.69446,
			0.74291,
			0.80751,
			0.85596,
			0.90441,
			0.96901,
			1.03361,
			1.09821,
			1.16281,
			1.22741,
			1.29202,
			1.37277,
			1.45352,
			1.53427,
		},
	}
	// attack: CoolColorCapture - Charged Attack DMG: {3}
	charge = []float64{
		1.00512,
		1.0805,
		1.15589,
		1.2564,
		1.33178,
		1.40717,
		1.50768,
		1.60819,
		1.7087,
		1.80922,
		1.90973,
		2.01024,
		2.13588,
		2.26152,
		2.38716,
	}
	// attack: CoolColorCapture - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: CoolColorCapture - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: CoolColorCapture - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// attack: CoolColorCapture - Spiritbreath Thorn DMG: {8}
	arkhe = []float64{
		0.11168,
		0.12006,
		0.12843,
		0.1396,
		0.14798,
		0.15635,
		0.16752,
		0.17869,
		0.18986,
		0.20102,
		0.21219,
		0.22336,
		0.23732,
		0.25128,
		0.26524,
	}
	// skill: FramingFreezingPointComposition - Photo DMG (Press): {0}
	skillPress = []float64{
		0.672,
		0.7224,
		0.7728,
		0.84,
		0.8904,
		0.9408,
		1.008,
		1.0752,
		1.1424,
		1.2096,
		1.2768,
		1.344,
		1.428,
		1.512,
		1.596,
	}
	// skill: FramingFreezingPointComposition - Photo DMG (Hold): {1}
	skillHold = []float64{
		1.392,
		1.4964,
		1.6008,
		1.74,
		1.8444,
		1.9488,
		2.088,
		2.2272,
		2.3664,
		2.5056,
		2.6448,
		2.784,
		2.958,
		3.132,
		3.306,
	}
	// skill: FramingFreezingPointComposition - "Snappy Silhouette" Mark DMG: {2}
	skillPressMark = []float64{
		0.392,
		0.4214,
		0.4508,
		0.49,
		0.5194,
		0.5488,
		0.588,
		0.6272,
		0.6664,
		0.7056,
		0.7448,
		0.784,
		0.833,
		0.882,
		0.931,
	}
	// skill: FramingFreezingPointComposition - "Focused Impression" Mark DMG: {5}
	skillHoldMark = []float64{
		0.406,
		0.43645,
		0.4669,
		0.5075,
		0.53795,
		0.5684,
		0.609,
		0.6496,
		0.6902,
		0.7308,
		0.7714,
		0.812,
		0.86275,
		0.9135,
		0.96425,
	}
	// burst: StillPhotoComprehensiveConfirmation - Cast Healing: {0} ATK+{1}
	burstInitialHealPer = []float64{
		2.56573,
		2.75816,
		2.95059,
		3.20717,
		3.3996,
		3.59203,
		3.8486,
		4.10518,
		4.36175,
		4.61832,
		4.8749,
		5.13147,
		5.45219,
		5.7729,
		6.09362,
	}
	// burst: StillPhotoComprehensiveConfirmation - Cast Healing: {0} ATK+{1}
	burstInitialHealFlat = []float64{
		1608.486,
		1769.357,
		1943.634,
		2131.317,
		2332.406,
		2546.9,
		2774.801,
		3016.107,
		3270.82,
		3538.938,
		3820.462,
		4115.393,
		4423.729,
		4745.471,
		5080.619,
	}
	// burst: StillPhotoComprehensiveConfirmation - Skill DMG: {2}
	burst = []float64{
		0.77616,
		0.83437,
		0.89258,
		0.9702,
		1.02841,
		1.08662,
		1.16424,
		1.24186,
		1.31947,
		1.39709,
		1.4747,
		1.55232,
		1.64934,
		1.74636,
		1.84338,
	}
	// burst: StillPhotoComprehensiveConfirmation - Kamera Continuous Regeneration: {3} ATK+{4}
	burstDotHealPer = []float64{
		0.09216,
		0.09907,
		0.10598,
		0.1152,
		0.12211,
		0.12902,
		0.13824,
		0.14746,
		0.15667,
		0.16589,
		0.1751,
		0.18432,
		0.19584,
		0.20736,
		0.21888,
	}
	// burst: StillPhotoComprehensiveConfirmation - Kamera Continuous Regeneration: {3} ATK+{4}
	burstDotHealFlat = []float64{
		57.4471,
		63.19261,
		69.41691,
		76.12,
		83.30189,
		90.96256,
		99.10204,
		107.7203,
		116.8174,
		126.3932,
		136.4478,
		146.9813,
		157.9935,
		169.4845,
		181.4543,
	}
	// burst: StillPhotoComprehensiveConfirmation - Kamera DMG: {5}
	burstDot = []float64{
		0.06468,
		0.06953,
		0.07438,
		0.08085,
		0.0857,
		0.09055,
		0.09702,
		0.10349,
		0.10996,
		0.11642,
		0.12289,
		0.12936,
		0.13745,
		0.14553,
		0.15361,
	}
)
