// Code generated by "pipeline"; DO NOT EDIT.

package lynette

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Lynette, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
		action.ActionBurst:      {"vivid_travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Lynette, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: RapidRitesword - 1-Hit DMG: {0}
			0.43082,
			0.46588,
			0.50095,
			0.55105,
			0.58611,
			0.62619,
			0.68129,
			0.7364,
			0.7915,
			0.85162,
			0.91173,
			0.97184,
			1.03196,
			1.09207,
			1.15218,
		}},
		{{ // attack: RapidRitesword - 2-Hit DMG: {1}
			0.37612,
			0.40674,
			0.43735,
			0.48109,
			0.5117,
			0.54669,
			0.5948,
			0.6429,
			0.69101,
			0.74349,
			0.79598,
			0.84846,
			0.90094,
			0.95342,
			1.00591,
		}},
		{
			{ // attack: RapidRitesword - 3-Hit DMG: {2}+{3}
				0.27864,
				0.30132,
				0.324,
				0.3564,
				0.37908,
				0.405,
				0.44064,
				0.47628,
				0.51192,
				0.5508,
				0.58968,
				0.62856,
				0.66744,
				0.70632,
				0.7452,
			},
			{ // attack: RapidRitesword - 3-Hit DMG: {2}+{3}
				0.21593,
				0.2335,
				0.25108,
				0.27619,
				0.29376,
				0.31385,
				0.34147,
				0.36909,
				0.39671,
				0.42684,
				0.45697,
				0.48709,
				0.51723,
				0.54735,
				0.57748,
			},
		},
		{{ // attack: RapidRitesword - 4-Hit DMG: {4}
			0.63154,
			0.68295,
			0.73435,
			0.80778,
			0.85919,
			0.91794,
			0.99872,
			1.07949,
			1.16027,
			1.24839,
			1.33652,
			1.42464,
			1.51276,
			1.60088,
			1.68901,
		}},
	}
	charge = [][]float64{
		{ // attack: RapidRitesword - Charged Attack DMG: {5}+{6}
			0.44204,
			0.47802,
			0.514,
			0.5654,
			0.60138,
			0.6425,
			0.69904,
			0.75558,
			0.81212,
			0.8738,
			0.93548,
			0.99716,
			1.05884,
			1.12052,
			1.1822,
		},
		{ // attack: RapidRitesword - Charged Attack DMG: {5}+{6}
			0.61404,
			0.66402,
			0.714,
			0.7854,
			0.83538,
			0.8925,
			0.97104,
			1.04958,
			1.12812,
			1.2138,
			1.29948,
			1.38516,
			1.47084,
			1.55652,
			1.6422,
		},
	}
	// attack: RapidRitesword - Plunge DMG: {8}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: RapidRitesword - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: RapidRitesword - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: EnigmaticFeint - Enigma Thrust DMG: {0}
	skill = []float64{
		2.68,
		2.881,
		3.082,
		3.35,
		3.551,
		3.752,
		4.02,
		4.288,
		4.556,
		4.824,
		5.092,
		5.36,
		5.695,
		6.03,
		6.365,
	}
	// skill: EnigmaticFeint - Surging Blade DMG: {2}
	skillAligned = []float64{
		0.312,
		0.3354,
		0.3588,
		0.39,
		0.4134,
		0.4368,
		0.468,
		0.4992,
		0.5304,
		0.5616,
		0.5928,
		0.624,
		0.663,
		0.702,
		0.741,
	}
	// burst: MagicTrickAstonishingShift - Skill DMG: {0}
	burst = []float64{
		0.832,
		0.8944,
		0.9568,
		1.04,
		1.1024,
		1.1648,
		1.248,
		1.3312,
		1.4144,
		1.4976,
		1.5808,
		1.664,
		1.768,
		1.872,
		1.976,
	}
	// burst: MagicTrickAstonishingShift - Bogglecat Box DMG: {1}
	bogglecat = []float64{
		0.512,
		0.5504,
		0.5888,
		0.64,
		0.6784,
		0.7168,
		0.768,
		0.8192,
		0.8704,
		0.9216,
		0.9728,
		1.024,
		1.088,
		1.152,
		1.216,
	}
	// burst: MagicTrickAstonishingShift - Vivid Shot DMG: {2}
	vivid = []float64{
		0.456,
		0.4902,
		0.5244,
		0.57,
		0.6042,
		0.6384,
		0.684,
		0.7296,
		0.7752,
		0.8208,
		0.8664,
		0.912,
		0.969,
		1.026,
		1.083,
	}
)
