// Code generated by "pipeline"; DO NOT EDIT.

package lauma

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Lauma, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Lauma, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: PeregrinationOfLinnunrata - 1-Hit DMG: {0}
			0.33702,
			0.3623,
			0.38758,
			0.42128,
			0.44656,
			0.47183,
			0.50554,
			0.53924,
			0.57294,
			0.60664,
			0.64035,
			0.67405,
			0.71618,
			0.7583,
			0.80043,
		},
		{ // attack: PeregrinationOfLinnunrata - 2-Hit DMG: {1}
			0.31805,
			0.3419,
			0.36575,
			0.39756,
			0.42141,
			0.44527,
			0.47707,
			0.50888,
			0.54068,
			0.57249,
			0.60429,
			0.6361,
			0.67585,
			0.71561,
			0.75536,
		},
		{ // attack: PeregrinationOfLinnunrata - 3-Hit DMG: {2}
			0.44497,
			0.47834,
			0.51171,
			0.55621,
			0.58958,
			0.62296,
			0.66745,
			0.71195,
			0.75645,
			0.80094,
			0.84544,
			0.88994,
			0.94556,
			1.00118,
			1.0568,
		},
	}
	// attack: PeregrinationOfLinnunrata - Spiritcall Prayer DMG: {8}
	charge = []float64{
		1.2904,
		1.38718,
		1.48396,
		1.613,
		1.70978,
		1.80656,
		1.9356,
		2.06464,
		2.19368,
		2.32272,
		2.45176,
		2.5808,
		2.7421,
		2.9034,
		3.0647,
	}
	// attack: PeregrinationOfLinnunrata - Plunge DMG: {9}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: PeregrinationOfLinnunrata - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: PeregrinationOfLinnunrata - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: RunoDawnlessRestOfKarsikko - Press DMG: {0}
	skillPress = []float64{
		1.216,
		1.3072,
		1.3984,
		1.52,
		1.6112,
		1.7024,
		1.824,
		1.9456,
		2.0672,
		2.1888,
		2.3104,
		2.432,
		2.584,
		2.736,
		2.888,
	}
	// skill: RunoDawnlessRestOfKarsikko - 1-Hit Hold DMG: {1}
	skillHold1 = []float64{
		1.5808,
		1.69936,
		1.81792,
		1.976,
		2.09456,
		2.21312,
		2.3712,
		2.52928,
		2.68736,
		2.84544,
		3.00352,
		3.1616,
		3.3592,
		3.5568,
		3.7544,
	}
	// skill: RunoDawnlessRestOfKarsikko - 2-Hit Hold DMG: {2} Elemental Mastery Per Verdant Dew
	skillHold2 = []float64{
		1.52,
		1.634,
		1.748,
		1.9,
		2.014,
		2.128,
		2.28,
		2.432,
		2.584,
		2.736,
		2.888,
		3.04,
		3.23,
		3.42,
		3.61,
	}
	// skill: RunoDawnlessRestOfKarsikko - Frostgrove Sanctuary Attack DMG: {3} ATK+{4} Elemental Mastery
	frostgroveSanctuaryAtk = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
	// skill: RunoDawnlessRestOfKarsikko - Frostgrove Sanctuary Attack DMG: {3} ATK+{4} Elemental Mastery
	frostgroveSanctuaryEM = []float64{
		1.92,
		2.064,
		2.208,
		2.4,
		2.544,
		2.688,
		2.88,
		3.072,
		3.264,
		3.456,
		3.648,
		3.84,
		4.08,
		4.32,
		4.56,
	}
	// skill: RunoDawnlessRestOfKarsikko - Elemental RES Decrease: {7}
	skillResShred = []float64{
		0.025,
		0.05,
		0.075,
		0.1,
		0.125,
		0.15,
		0.175,
		0.2,
		0.225,
		0.25,
		0.28,
		0.31,
		0.34,
		0.37,
		0.4,
	}
	// burst: RunoAllHeartsBecomeTheBeatingMoon - Bloom, Hyperbloom, and Burgeon DMG Increase: {2} Elemental Mastery
	bloomDmgIncrease = []float64{
		2.7776,
		2.98592,
		3.19424,
		3.472,
		3.68032,
		3.88864,
		4.1664,
		4.44416,
		4.72192,
		4.99968,
		5.27744,
		5.5552,
		5.9024,
		6.2496,
		6.5968,
	}
	// burst: RunoAllHeartsBecomeTheBeatingMoon - Lunar-Bloom DMG Increase: {3} Elemental Mastery
	lunarBloomDmgIncrease = []float64{
		2.2224,
		2.38908,
		2.55576,
		2.778,
		2.94468,
		3.11136,
		3.3336,
		3.55584,
		3.77808,
		4.00032,
		4.22256,
		4.4448,
		4.7226,
		5.0004,
		5.2782,
	}
)
