// Code generated by "pipeline"; DO NOT EDIT.

package vodyanitsa

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Vodyanitsa, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Vodyanitsa, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: PsyshkhweArietta - 1-Hit DMG: {0}
			0.43385,
			0.46639,
			0.49893,
			0.54231,
			0.57485,
			0.60739,
			0.65077,
			0.69416,
			0.73754,
			0.78093,
			0.82431,
			0.8677,
			0.92193,
			0.97616,
			1.03039,
		},
		{ // attack: PsyshkhweArietta - 2-Hit DMG: {1}
			0.40232,
			0.43249,
			0.46267,
			0.5029,
			0.53307,
			0.56325,
			0.60348,
			0.64371,
			0.68394,
			0.72418,
			0.76441,
			0.80464,
			0.85493,
			0.90522,
			0.95551,
		},
		{ // attack: PsyshkhweArietta - 3-Hit DMG: {2}
			0.49302,
			0.52999,
			0.56697,
			0.61627,
			0.65325,
			0.69022,
			0.73952,
			0.78883,
			0.83813,
			0.88743,
			0.93673,
			0.98603,
			1.04766,
			1.10929,
			1.17091,
		},
		{ // attack: PsyshkhweArietta - 4-Hit DMG: {3}
			0.65563,
			0.7048,
			0.75398,
			0.81954,
			0.86871,
			0.91789,
			0.98345,
			1.04901,
			1.11457,
			1.18014,
			1.2457,
			1.31126,
			1.39322,
			1.47517,
			1.55713,
		},
	}
	// attack: PsyshkhweArietta - Charged Attack DMG: {4}
	charge = []float64{
		1.2376,
		1.33042,
		1.42324,
		1.547,
		1.63982,
		1.73264,
		1.8564,
		1.98016,
		2.10392,
		2.22768,
		2.35144,
		2.4752,
		2.6299,
		2.7846,
		2.9393,
	}
	// skill: RechitativSonorousDawn - Skill DMG: {0} Max HP
	skill = []float64{
		0.03272,
		0.03517,
		0.03763,
		0.0409,
		0.04335,
		0.04581,
		0.04908,
		0.05235,
		0.05562,
		0.0589,
		0.06217,
		0.06544,
		0.06953,
		0.07362,
		0.07771,
	}
	// skill: RechitativSonorousDawn - Horn of Spring's Call DMG: {3} Max HP
	skillDot = []float64{
		0.03272,
		0.03517,
		0.03763,
		0.0409,
		0.04335,
		0.04581,
		0.04908,
		0.05235,
		0.05562,
		0.0589,
		0.06217,
		0.06544,
		0.06953,
		0.07362,
		0.07771,
	}
	// skill: RechitativSonorousDawn - Song of Ages Past Healing: {4} + {5} Max HP
	skillHealFlat = []float64{
		269.6285,
		296.5952,
		325.809,
		357.27,
		390.9782,
		426.9337,
		465.1364,
		505.5863,
		548.2835,
		593.2278,
		640.4193,
		689.8581,
		741.5441,
		795.4773,
		851.6577,
	}
	// skill: RechitativSonorousDawn - Song of Ages Past Healing: {4} + {5} Max HP
	skillHealRatio = []float64{
		0.028,
		0.0301,
		0.0322,
		0.035,
		0.0371,
		0.0392,
		0.042,
		0.0448,
		0.0476,
		0.0504,
		0.0532,
		0.056,
		0.0595,
		0.063,
		0.0665,
	}
	// skill: RechitativSonorousDawn - Hydro/Cryo RES Reduction: {7}
	skillShred = []float64{
		0.165,
		0.18,
		0.195,
		0.21,
		0.225,
		0.24,
		0.255,
		0.27,
		0.285,
		0.3,
		0.318,
		0.336,
		0.354,
		0.372,
		0.39,
	}
	// burst: KodaSinkWithThee - Skill DMG: {0} Max HP
	burst = []float64{
		0.45677,
		0.49103,
		0.52528,
		0.57096,
		0.60522,
		0.63947,
		0.68515,
		0.73083,
		0.77651,
		0.82218,
		0.86786,
		0.91354,
		0.97063,
		1.02773,
		1.08482,
	}
	// burst: KodaSinkWithThee - Song of Ages Past DMG Bonus: {1}
	burstBonus = []float64{
		0.48,
		0.516,
		0.552,
		0.6,
		0.636,
		0.672,
		0.72,
		0.768,
		0.816,
		0.864,
		0.912,
		0.96,
		1.02,
		1.08,
		1.14,
	}
)
