// Code generated by "pipeline"; DO NOT EDIT.

package ororon

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Ororon, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
		action.ActionSkill:  {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Ororon, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SpiritvesselSnapshot - 1-Hit DMG: {0}
			0.50642,
			0.54764,
			0.58886,
			0.64775,
			0.68897,
			0.73607,
			0.80085,
			0.86562,
			0.9304,
			1.00106,
			1.07173,
			1.14239,
			1.21305,
			1.28372,
			1.35438,
		},
		{ // attack: SpiritvesselSnapshot - 2-Hit DMG: {1}
			0.44373,
			0.47985,
			0.51597,
			0.56757,
			0.60369,
			0.64496,
			0.70172,
			0.75848,
			0.81523,
			0.87715,
			0.93906,
			1.00098,
			1.0629,
			1.12481,
			1.18673,
		},
		{ // attack: SpiritvesselSnapshot - 3-Hit DMG: {2}
			0.69821,
			0.75504,
			0.81187,
			0.89306,
			0.94989,
			1.01484,
			1.10414,
			1.19345,
			1.28276,
			1.38018,
			1.4776,
			1.57503,
			1.67245,
			1.76988,
			1.8673,
		},
	}
	// attack: SpiritvesselSnapshot - Aimed Shot: {3}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: SpiritvesselSnapshot - Fully-Charged Aimed Shot: {4}
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// skill: NightsSling - Spirit Orb DMG: {0}
	spiritOrb = []float64{
		1.976,
		2.1242,
		2.2724,
		2.47,
		2.6182,
		2.7664,
		2.964,
		3.1616,
		3.3592,
		3.5568,
		3.7544,
		3.952,
		4.199,
		4.446,
		4.693,
	}
	// burst: DarkVoicesEcho - Ritual DMG: {0}
	burst = []float64{
		1.74384,
		1.87463,
		2.00542,
		2.1798,
		2.31059,
		2.44138,
		2.61576,
		2.79014,
		2.96453,
		3.13891,
		3.3133,
		3.48768,
		3.70566,
		3.92364,
		4.14162,
	}
	// burst: DarkVoicesEcho - Soundwave Collision DMG: {1}
	soundwave = []float64{
		0.332,
		0.3569,
		0.3818,
		0.415,
		0.4399,
		0.4648,
		0.498,
		0.5312,
		0.5644,
		0.5976,
		0.6308,
		0.664,
		0.7055,
		0.747,
		0.7885,
	}
)
