// Code generated by "pipeline"; DO NOT EDIT.

package sethos

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Sethos, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
	}
	validation.RegisterCharParamValidationFunc(keys.Sethos, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	skillEnergyRegen = 12 // skill: AncientRiteTheThunderingSands - Energy Regeneration: {1}
)

var (
	attack = [][][]float64{
		{{ // attack: RoyalReedArchery - 1-Hit DMG: {0}
			0.52614,
			0.56897,
			0.61179,
			0.67297,
			0.71579,
			0.76474,
			0.83203,
			0.89933,
			0.96663,
			1.04004,
			1.11346,
			1.18687,
			1.26029,
			1.3337,
			1.40712,
		}},
		{
			{ // attack: RoyalReedArchery - 2-Hit DMG: {1}+{2}
				0.23796,
				0.25733,
				0.2767,
				0.30437,
				0.32374,
				0.34587,
				0.37631,
				0.40675,
				0.43719,
				0.47039,
				0.50359,
				0.5368,
				0.57,
				0.60321,
				0.63641,
			},
			{ // attack: RoyalReedArchery - 2-Hit DMG: {1}+{2}
				0.26608,
				0.28774,
				0.3094,
				0.34034,
				0.362,
				0.38675,
				0.42078,
				0.45482,
				0.48885,
				0.52598,
				0.56311,
				0.60024,
				0.63736,
				0.67449,
				0.71162,
			},
		},
		{{ // attack: RoyalReedArchery - 3-Hit DMG: {3}
			0.73987,
			0.80009,
			0.86031,
			0.94634,
			1.00656,
			1.07539,
			1.17002,
			1.26466,
			1.35929,
			1.46253,
			1.56576,
			1.669,
			1.77224,
			1.87548,
			1.97871,
		}},
	}
	// attack: RoyalReedArchery - Aimed Shot: {4}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: RoyalReedArchery - Aimed Shot Charge Level 1: {5}
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// attack: RoyalReedArchery - Shadowpiercing Shot DMG: {6} ATK+{7} Elemental Mastery
	shadowpierceAtk = []float64{
		1.4,
		1.505,
		1.61,
		1.75,
		1.855,
		1.96,
		2.1,
		2.24,
		2.38,
		2.52,
		2.66,
		2.8,
		2.975,
		3.15,
		3.325,
	}
	// attack: RoyalReedArchery - Shadowpiercing Shot DMG: {6} ATK+{7} Elemental Mastery
	shadowpierceEM = []float64{
		1.3456,
		1.44652,
		1.54744,
		1.682,
		1.78292,
		1.88384,
		2.0184,
		2.15296,
		2.28752,
		2.42208,
		2.55664,
		2.6912,
		2.8594,
		3.0276,
		3.1958,
	}
	// skill: AncientRiteTheThunderingSands - Skill DMG: {0}
	skill = []float64{
		1.156,
		1.2427,
		1.3294,
		1.445,
		1.5317,
		1.6184,
		1.734,
		1.8496,
		1.9652,
		2.0808,
		2.1964,
		2.312,
		2.4565,
		2.601,
		2.7455,
	}
	// burst: SecretRiteTwilightShadowpiercer - Dusk Bolt DMG Increase: {0} Elemental Mastery
	burstEM = []float64{
		1.9616,
		2.10872,
		2.25584,
		2.452,
		2.59912,
		2.74624,
		2.9424,
		3.13856,
		3.33472,
		3.53088,
		3.72704,
		3.9232,
		4.1684,
		4.4136,
		4.6588,
	}
)
