// Code generated by "pipeline"; DO NOT EDIT.

package prune

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Prune, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Prune, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: BadaboomHexbusterHammer - 1-Hit DMG: {0}
			0.48621,
			0.52267,
			0.55914,
			0.60776,
			0.64423,
			0.68069,
			0.72931,
			0.77793,
			0.82655,
			0.87517,
			0.92379,
			0.97242,
			1.03319,
			1.09397,
			1.15474,
		},
		{ // attack: BadaboomHexbusterHammer - 2-Hit DMG: {1}
			0.48281,
			0.51902,
			0.55523,
			0.60351,
			0.63972,
			0.67593,
			0.72421,
			0.77249,
			0.82077,
			0.86905,
			0.91733,
			0.96562,
			1.02597,
			1.08632,
			1.14667,
		},
		{ // attack: BadaboomHexbusterHammer - 3-Hit DMG: {2}
			0.67977,
			0.73075,
			0.78173,
			0.84971,
			0.90069,
			0.95167,
			1.01965,
			1.08763,
			1.15561,
			1.22358,
			1.29156,
			1.35954,
			1.44451,
			1.52948,
			1.61445,
		},
	}
	// attack: BadaboomHexbusterHammer - Charged Attack DMG: {3}
	charge = []float64{
		1.3352,
		1.43534,
		1.53548,
		1.669,
		1.76914,
		1.86928,
		2.0028,
		2.13632,
		2.26984,
		2.40336,
		2.53688,
		2.6704,
		2.8373,
		3.0042,
		3.1711,
	}
	// attack: BadaboomHexbusterHammer - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: BadaboomHexbusterHammer - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: BadaboomHexbusterHammer - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: RingADingDingHexhunterChime - Ring-A-Ding-Ding! Hexhunter Chime DMG: {0}
	skill = []float64{
		1.6744,
		1.79998,
		1.92556,
		2.093,
		2.21858,
		2.34416,
		2.5116,
		2.67904,
		2.84648,
		3.01392,
		3.18136,
		3.3488,
		3.5581,
		3.7674,
		3.9767,
	}
	// skill: RingADingDingHexhunterChime - Clang Clang! Witch-tribution Comes! DMG: {1}
	skillConvert = []float64{
		2.0456,
		2.19902,
		2.35244,
		2.557,
		2.71042,
		2.86384,
		3.0684,
		3.27296,
		3.47752,
		3.68208,
		3.88664,
		4.0912,
		4.3469,
		4.6026,
		4.8583,
	}
	// burst: TheBellTollsTheHuntIsOn - Skill DMG: {0}
	burst = []float64{
		0.9696,
		1.04232,
		1.11504,
		1.212,
		1.28472,
		1.35744,
		1.4544,
		1.55136,
		1.64832,
		1.74528,
		1.84224,
		1.9392,
		2.0604,
		2.1816,
		2.3028,
	}
	// burst: TheBellTollsTheHuntIsOn - Witchlure Bell DMG: {1}
	burstDot = []float64{
		0.7044,
		0.75723,
		0.81006,
		0.8805,
		0.93333,
		0.98616,
		1.0566,
		1.12704,
		1.19748,
		1.26792,
		1.33836,
		1.4088,
		1.49685,
		1.5849,
		1.67295,
	}
)
