// Code generated by "pipeline"; DO NOT EDIT.

package mika

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Mika, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Mika, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: SpearOfFavoniusArrowsPassage - 1-Hit DMG: {0}
			0.43263,
			0.46785,
			0.50306,
			0.55337,
			0.58858,
			0.62883,
			0.68416,
			0.7395,
			0.79483,
			0.8552,
			0.91557,
			0.97594,
			1.0363,
			1.09667,
			1.15704,
		}},
		{{ // attack: SpearOfFavoniusArrowsPassage - 2-Hit DMG: {1}
			0.41502,
			0.4488,
			0.48258,
			0.53084,
			0.56462,
			0.60322,
			0.65631,
			0.70939,
			0.76248,
			0.82039,
			0.8783,
			0.93621,
			0.99411,
			1.05202,
			1.10993,
		}},
		{{ // attack: SpearOfFavoniusArrowsPassage - 3-Hit DMG: {2}
			0.54503,
			0.5894,
			0.63376,
			0.69714,
			0.7415,
			0.7922,
			0.86191,
			0.93163,
			1.00134,
			1.07739,
			1.15344,
			1.22949,
			1.30555,
			1.3816,
			1.45765,
		}},
		{
			{ // attack: SpearOfFavoniusArrowsPassage - 4-Hit DMG: {3}+{4}
				0.27615,
				0.29862,
				0.3211,
				0.35321,
				0.37569,
				0.40137,
				0.4367,
				0.47202,
				0.50734,
				0.54587,
				0.5844,
				0.62293,
				0.66147,
				0.7,
				0.73853,
			},
			{ // attack: SpearOfFavoniusArrowsPassage - 4-Hit DMG: {3}+{4}
				0.27615,
				0.29862,
				0.3211,
				0.35321,
				0.37569,
				0.40137,
				0.4367,
				0.47202,
				0.50734,
				0.54587,
				0.5844,
				0.62293,
				0.66147,
				0.7,
				0.73853,
			},
		},
		{{ // attack: SpearOfFavoniusArrowsPassage - 5-Hit DMG: {5}
			0.70874,
			0.76643,
			0.82412,
			0.90653,
			0.96422,
			1.03015,
			1.1208,
			1.21146,
			1.30211,
			1.401,
			1.4999,
			1.59879,
			1.69769,
			1.79658,
			1.89548,
		}},
	}
	// attack: SpearOfFavoniusArrowsPassage - Charged Attack DMG: {6}
	charge = []float64{
		1.12746,
		1.21923,
		1.311,
		1.4421,
		1.53387,
		1.63875,
		1.78296,
		1.92717,
		2.07138,
		2.2287,
		2.38602,
		2.54334,
		2.70066,
		2.85798,
		3.0153,
	}
	// skill: StarfrostSwirl - Flowfrost Arrow DMG: {0}
	skillPress = []float64{
		0.672,
		0.7224,
		0.7728,
		0.84,
		0.8904,
		0.9408,
		1.008,
		1.0752,
		1.1424,
		1.2096,
		1.2768,
		1.344,
		1.428,
		1.512,
		1.596,
	}
	// skill: StarfrostSwirl - Rimestar Flare DMG: {1}
	skillHold = []float64{
		0.84,
		0.903,
		0.966,
		1.05,
		1.113,
		1.176,
		1.26,
		1.344,
		1.428,
		1.512,
		1.596,
		1.68,
		1.785,
		1.89,
		1.995,
	}
	// skill: StarfrostSwirl - Rimestar Shard DMG: {2}
	skillExplode = []float64{
		0.252,
		0.2709,
		0.2898,
		0.315,
		0.3339,
		0.3528,
		0.378,
		0.4032,
		0.4284,
		0.4536,
		0.4788,
		0.504,
		0.5355,
		0.567,
		0.5985,
	}
	// skill: StarfrostSwirl - ATK SPD Bonus: {3}
	atkSpdBuff = []float64{
		0.13,
		0.14,
		0.15,
		0.16,
		0.17,
		0.18,
		0.19,
		0.2,
		0.21,
		0.22,
		0.23,
		0.24,
		0.25,
		0.25,
		0.25,
	}
	// burst: SkyfeatherSong - Cast Healing: {1} Max HP+{0}
	burstHealFirstF = []float64{
		1172.036,
		1289.255,
		1416.244,
		1553.0,
		1699.525,
		1855.818,
		2021.879,
		2197.709,
		2383.307,
		2578.674,
		2783.808,
		2998.711,
		3223.383,
		3457.823,
		3702.031,
	}
	// burst: SkyfeatherSong - Cast Healing: {1} Max HP+{0}
	burstHealFirstP = []float64{
		0.12168,
		0.13081,
		0.13993,
		0.1521,
		0.16123,
		0.17035,
		0.18252,
		0.19469,
		0.20686,
		0.21902,
		0.23119,
		0.24336,
		0.25857,
		0.27378,
		0.28899,
	}
	// burst: SkyfeatherSong - Eagleplume Healing: {3} Max HP+{2}
	burstHealF = []float64{
		233.9543,
		257.353,
		282.7015,
		310.0,
		339.2484,
		370.4466,
		403.5947,
		438.6928,
		475.7407,
		514.7385,
		555.6862,
		598.5837,
		643.4312,
		690.2286,
		738.9758,
	}
	// burst: SkyfeatherSong - Eagleplume Healing: {3} Max HP+{2}
	burstHealP = []float64{
		0.02432,
		0.02614,
		0.02797,
		0.0304,
		0.03222,
		0.03405,
		0.03648,
		0.03891,
		0.04134,
		0.04378,
		0.04621,
		0.04864,
		0.05168,
		0.05472,
		0.05776,
	}
)
