// Code generated by "pipeline"; DO NOT EDIT.

package dahlia

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Dahlia, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"short_hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Dahlia, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: FavoniusBladeworkRitual - 1-Hit DMG: {0}
			0.43547,
			0.47091,
			0.50636,
			0.557,
			0.59244,
			0.63295,
			0.68865,
			0.74435,
			0.80005,
			0.86081,
			0.92158,
			0.98234,
			1.0431,
			1.10387,
			1.16463,
		}},
		{{ // attack: FavoniusBladeworkRitual - 2-Hit DMG: {1}
			0.401,
			0.43364,
			0.46628,
			0.51291,
			0.54555,
			0.58285,
			0.63414,
			0.68543,
			0.73672,
			0.79268,
			0.84863,
			0.90458,
			0.96054,
			1.01649,
			1.07244,
		}},
		{
			{ // attack: FavoniusBladeworkRitual - 3-Hit DMG: {2}+{3}
				0.23745,
				0.25677,
				0.2761,
				0.30371,
				0.32304,
				0.34512,
				0.3755,
				0.40587,
				0.43624,
				0.46937,
				0.5025,
				0.53563,
				0.56877,
				0.6019,
				0.63503,
			},
			{ // attack: FavoniusBladeworkRitual - 3-Hit DMG: {2}+{3}
				0.29016,
				0.31378,
				0.3374,
				0.37114,
				0.39476,
				0.42175,
				0.45886,
				0.49598,
				0.53309,
				0.57358,
				0.61407,
				0.65456,
				0.69504,
				0.73553,
				0.77602,
			},
		},
		{{ // attack: FavoniusBladeworkRitual - 4-Hit DMG: {4}
			0.65658,
			0.71002,
			0.76346,
			0.83981,
			0.89325,
			0.95433,
			1.03831,
			1.12229,
			1.20627,
			1.29788,
			1.3895,
			1.48111,
			1.57273,
			1.66434,
			1.75596,
		}},
	}
	charge = [][]float64{
		{ // attack: FavoniusBladeworkRitual - Charged Attack DMG: {5}+{6}
			0.39876,
			0.43122,
			0.46368,
			0.51005,
			0.54251,
			0.5796,
			0.6306,
			0.68161,
			0.73261,
			0.78826,
			0.8439,
			0.89954,
			0.95518,
			1.01082,
			1.06646,
		},
		{ // attack: FavoniusBladeworkRitual - Charged Attack DMG: {5}+{6}
			0.55067,
			0.5955,
			0.64032,
			0.70435,
			0.74917,
			0.8004,
			0.87084,
			0.94127,
			1.01171,
			1.08854,
			1.16538,
			1.24222,
			1.31906,
			1.3959,
			1.47274,
		},
	}
	// attack: FavoniusBladeworkRitual - Plunge DMG: {8}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: FavoniusBladeworkRitual - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: FavoniusBladeworkRitual - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: ImmersiveOrdinance - Skill DMG: {0}
	skill = []float64{
		2.328,
		2.5026,
		2.6772,
		2.91,
		3.0846,
		3.2592,
		3.492,
		3.7248,
		3.9576,
		4.1904,
		4.4232,
		4.656,
		4.947,
		5.238,
		5.529,
	}
	// burst: RadiantPsalter - Skill DMG: {0}
	burst = []float64{
		4.064,
		4.3688,
		4.6736,
		5.08,
		5.3848,
		5.6896,
		6.096,
		6.5024,
		6.9088,
		7.3152,
		7.7216,
		8.128,
		8.636,
		9.144,
		9.652,
	}
	// burst: RadiantPsalter - Shield of Sacred Favor DMG Absorption: {2} Max HP+{1}
	burstShieldFlat = []float64{
		323.5577,
		355.918,
		390.975,
		428.7286,
		469.1789,
		512.3259,
		558.1697,
		606.7101,
		657.9471,
		711.8809,
		768.5114,
		827.8386,
		889.8624,
		954.583,
		1022.0,
	}
	// burst: RadiantPsalter - Shield of Sacred Favor DMG Absorption: {2} Max HP+{1}
	burstShieldPP = []float64{
		0.0336,
		0.03612,
		0.03864,
		0.042,
		0.04452,
		0.04704,
		0.0504,
		0.05376,
		0.05712,
		0.06048,
		0.06384,
		0.0672,
		0.0714,
		0.0756,
		0.0798,
	}
)
