// Code generated by "pipeline"; DO NOT EDIT.

package hutao

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.HuTao, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.HuTao, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: SecretSpearOfWangsheng - 1-Hit DMG: {0}
			0.46886,
			0.50083,
			0.5328,
			0.57542,
			0.60739,
			0.64469,
			0.69264,
			0.74059,
			0.78854,
			0.8365,
			0.88445,
			0.9324,
			0.98035,
			1.0283,
			1.07626,
		}},
		{{ // attack: SecretSpearOfWangsheng - 2-Hit DMG: {1}
			0.48254,
			0.51544,
			0.54834,
			0.59221,
			0.62511,
			0.66349,
			0.71284,
			0.76219,
			0.81154,
			0.86089,
			0.91024,
			0.9596,
			1.00895,
			1.0583,
			1.10765,
		}},
		{{ // attack: SecretSpearOfWangsheng - 3-Hit DMG: {2}
			0.6105,
			0.65213,
			0.69375,
			0.74925,
			0.79088,
			0.83944,
			0.90188,
			0.96431,
			1.02675,
			1.08919,
			1.15163,
			1.21406,
			1.2765,
			1.33894,
			1.40138,
		}},
		{{ // attack: SecretSpearOfWangsheng - 4-Hit DMG: {3}
			0.65641,
			0.70117,
			0.74592,
			0.80559,
			0.85035,
			0.90256,
			0.9697,
			1.03683,
			1.10396,
			1.17109,
			1.23823,
			1.30536,
			1.37249,
			1.43963,
			1.50676,
		}},
		{
			{ // attack: SecretSpearOfWangsheng - 5-Hit DMG: {4}+{5}
				0.33274,
				0.35542,
				0.37811,
				0.40836,
				0.43104,
				0.45751,
				0.49154,
				0.52557,
				0.5596,
				0.59363,
				0.62766,
				0.66169,
				0.69572,
				0.72975,
				0.76378,
			},
			{ // attack: SecretSpearOfWangsheng - 5-Hit DMG: {4}+{5}
				0.352,
				0.376,
				0.4,
				0.432,
				0.456,
				0.484,
				0.52,
				0.556,
				0.592,
				0.628,
				0.664,
				0.7,
				0.736,
				0.772,
				0.808,
			},
		},
		{{ // attack: SecretSpearOfWangsheng - 6-Hit DMG: {6}
			0.85958,
			0.91819,
			0.9768,
			1.05494,
			1.11355,
			1.18193,
			1.26984,
			1.35775,
			1.44566,
			1.53358,
			1.62149,
			1.7094,
			1.79731,
			1.88522,
			1.97314,
		}},
	}
	// attack: SecretSpearOfWangsheng - Charged Attack: {7}
	charge = []float64{
		1.3596,
		1.4523,
		1.545,
		1.6686,
		1.7613,
		1.86945,
		2.0085,
		2.14755,
		2.2866,
		2.42565,
		2.5647,
		2.70375,
		2.8428,
		2.98185,
		3.1209,
	}
	// attack: SecretSpearOfWangsheng - Plunge DMG: {9}
	collision = []float64{
		0.65419,
		0.6988,
		0.7434,
		0.80287,
		0.84748,
		0.89951,
		0.96642,
		1.03333,
		1.10023,
		1.16714,
		1.23404,
		1.30095,
		1.36786,
		1.43476,
		1.50167,
	}
	// attack: SecretSpearOfWangsheng - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.30811,
		1.3973,
		1.48649,
		1.6054,
		1.69459,
		1.79865,
		1.93243,
		2.06621,
		2.2,
		2.33378,
		2.46757,
		2.60135,
		2.73513,
		2.86892,
		3.0027,
	}
	// attack: SecretSpearOfWangsheng - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.6339,
		1.7453,
		1.8567,
		2.00524,
		2.11664,
		2.24661,
		2.41371,
		2.58081,
		2.74792,
		2.91502,
		3.08212,
		3.24922,
		3.41633,
		3.58343,
		3.75053,
	}
	// skill: GuideToAfterlife - ATK Increase: {1} Max HP
	ppatk = []float64{
		0.03841,
		0.04071,
		0.04301,
		0.046,
		0.0483,
		0.0506,
		0.05359,
		0.05658,
		0.05957,
		0.06256,
		0.06555,
		0.06854,
		0.07153,
		0.07452,
		0.07751,
	}
	// skill: GuideToAfterlife - Blood Blossom DMG: {2}
	bb = []float64{
		0.64,
		0.688,
		0.736,
		0.8,
		0.848,
		0.896,
		0.96,
		1.024,
		1.088,
		1.152,
		1.216,
		1.28,
		1.36,
		1.44,
		1.52,
	}
	// burst: SpiritSoother - Skill DMG: {0}
	burst = []float64{
		3.03272,
		3.21432,
		3.39592,
		3.632,
		3.8136,
		3.9952,
		4.23128,
		4.46736,
		4.70344,
		4.93952,
		5.1756,
		5.41168,
		5.64776,
		5.88384,
		6.11992,
	}
	// burst: SpiritSoother - Low HP Skill DMG: {1}
	burstLow = []float64{
		3.7909,
		4.0179,
		4.2449,
		4.54,
		4.767,
		4.994,
		5.2891,
		5.5842,
		5.8793,
		6.1744,
		6.4695,
		6.7646,
		7.0597,
		7.3548,
		7.6499,
	}
	// burst: SpiritSoother - Skill HP Regeneration: {2} Max HP
	regen = []float64{
		0.06262,
		0.06638,
		0.07012,
		0.075,
		0.07875,
		0.0825,
		0.08738,
		0.09225,
		0.09713,
		0.102,
		0.10688,
		0.11175,
		0.11663,
		0.1215,
		0.12638,
	}
	// burst: SpiritSoother - Low HP Skill Regeneration: {3} Max HP
	regenLow = []float64{
		0.0835,
		0.0885,
		0.0935,
		0.1,
		0.105,
		0.11,
		0.1165,
		0.123,
		0.1295,
		0.136,
		0.1425,
		0.149,
		0.1555,
		0.162,
		0.1685,
	}
)
