// Code generated by "pipeline"; DO NOT EDIT.

package sandrone

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Sandrone, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionCharge: {"frames"},
		action.ActionSkill:  {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Sandrone, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: FormulePhenomenaleSelfEvidentProposition - 1-Hit DMG: {0}
			0.76286,
			0.82496,
			0.88705,
			0.97575,
			1.03785,
			1.10881,
			1.20639,
			1.30396,
			1.40154,
			1.50798,
			1.61443,
			1.72088,
			1.82732,
			1.93377,
			2.04022,
		},
		{ // attack: FormulePhenomenaleSelfEvidentProposition - 2-Hit DMG: {1}
			0.67197,
			0.72667,
			0.78136,
			0.8595,
			0.91419,
			0.9767,
			1.06265,
			1.1486,
			1.23455,
			1.32831,
			1.42208,
			1.51584,
			1.6096,
			1.70336,
			1.79713,
		},
		{ // attack: FormulePhenomenaleSelfEvidentProposition - 3-Hit DMG: {2}
			1.02804,
			1.11171,
			1.19539,
			1.31493,
			1.39861,
			1.49424,
			1.62573,
			1.75722,
			1.88872,
			2.03216,
			2.17561,
			2.31906,
			2.4625,
			2.60595,
			2.7494,
		},
	}
	// attack: FormulePhenomenaleSelfEvidentProposition - Charged Attack Sweeping Fire DMG: {3}
	chargeSweep = []float64{
		0.43,
		0.465,
		0.5,
		0.55,
		0.585,
		0.625,
		0.68,
		0.735,
		0.79,
		0.85,
		0.91,
		0.97,
		1.03,
		1.09,
		1.15,
	}
	// attack: FormulePhenomenaleSelfEvidentProposition - Charged Attack Condensed Beam DMG: {4}
	chargeBeam = []float64{
		1.2255,
		1.32525,
		1.425,
		1.5675,
		1.66725,
		1.78125,
		1.938,
		2.09475,
		2.2515,
		2.4225,
		2.5935,
		2.7645,
		2.9355,
		3.1065,
		3.2775,
	}
	// attack: FormulePhenomenaleSelfEvidentProposition - Charged Attack Condensed Beam Stellar-Conduct DMG: {5}
	chargeBeamSSC = []float64{
		0.817,
		0.8835,
		0.95,
		1.045,
		1.1115,
		1.1875,
		1.292,
		1.3965,
		1.501,
		1.615,
		1.729,
		1.843,
		1.957,
		2.071,
		2.185,
	}
	// attack: FormulePhenomenaleSelfEvidentProposition - Charged Attack Condensed Beam Stellar Swirl DMG: {10}
	chargeBeamSSw = []float64{
		1.2255,
		1.32525,
		1.425,
		1.5675,
		1.66725,
		1.78125,
		1.938,
		2.09475,
		2.2515,
		2.4225,
		2.5935,
		2.7645,
		2.9355,
		3.1065,
		3.2775,
	}
	// attack: FormulePhenomenaleSelfEvidentProposition - DMG When in Power Overdrive: {6}
	chargeOverdrive = []float64{
		0.43,
		0.465,
		0.5,
		0.55,
		0.585,
		0.625,
		0.68,
		0.735,
		0.79,
		0.85,
		0.91,
		0.97,
		1.03,
		1.09,
		1.15,
	}
	// skill: FormulePhenomenaleDifferentialAnalysis - Prism Shot DMG: {0}
	skill = []float64{
		0.324,
		0.3483,
		0.3726,
		0.405,
		0.4293,
		0.4536,
		0.486,
		0.5184,
		0.5508,
		0.5832,
		0.6156,
		0.648,
		0.6885,
		0.729,
		0.7695,
	}
	// skill: FormulePhenomenaleDifferentialAnalysis - Prism Shot Stellar-Conduct DMG: {1}
	skillSSC = []float64{
		0.216,
		0.2322,
		0.2484,
		0.27,
		0.2862,
		0.3024,
		0.324,
		0.3456,
		0.3672,
		0.3888,
		0.4104,
		0.432,
		0.459,
		0.486,
		0.513,
	}
	// skill: FormulePhenomenaleDifferentialAnalysis - Prism Shot Stellar Swirl DMG: {3}
	skillSSw = []float64{
		0.324,
		0.3483,
		0.3726,
		0.405,
		0.4293,
		0.4536,
		0.486,
		0.5184,
		0.5508,
		0.5832,
		0.6156,
		0.648,
		0.6885,
		0.729,
		0.7695,
	}
	// burst: FormulePhenomenaleQED - Bombardment DMG: {0} ×3
	burst = []float64{
		0.88216,
		0.94832,
		1.01448,
		1.1027,
		1.16886,
		1.23502,
		1.32324,
		1.41146,
		1.49967,
		1.58789,
		1.6761,
		1.76432,
		1.87459,
		1.98486,
		2.09513,
	}
	// burst: FormulePhenomenaleQED - Convective Inhibition Ray DMG: {1}
	burstRay = []float64{
		3.308,
		3.5561,
		3.8042,
		4.135,
		4.3831,
		4.6312,
		4.962,
		5.2928,
		5.6236,
		5.9544,
		6.2852,
		6.616,
		7.0295,
		7.443,
		7.8565,
	}
	// burst: FormulePhenomenaleQED - Convective Inhibition Ray Stellar-Conduct DMG: {2}
	burstRaySSC = []float64{
		2.20533,
		2.37073,
		2.53613,
		2.75667,
		2.92207,
		3.08747,
		3.308,
		3.52853,
		3.74907,
		3.9696,
		4.19013,
		4.41067,
		4.68633,
		4.962,
		5.23767,
	}
	// burst: FormulePhenomenaleQED - Convective Inhibition Ray Stellar Swirl DMG: {5}
	burstRaySSw = []float64{
		3.308,
		3.5561,
		3.8042,
		4.135,
		4.3831,
		4.6312,
		4.962,
		5.2928,
		5.6236,
		5.9544,
		6.2852,
		6.616,
		7.0295,
		7.443,
		7.8565,
	}
)
