// Code generated by "pipeline"; DO NOT EDIT.

package ineffa

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Ineffa, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Ineffa, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: CyclonicDuster - 1-Hit DMG: {0}
			0.34835,
			0.37671,
			0.40506,
			0.44557,
			0.47392,
			0.50633,
			0.55088,
			0.59544,
			0.63999,
			0.6886,
			0.73721,
			0.78582,
			0.83442,
			0.88303,
			0.93164,
		}},
		{{ // attack: CyclonicDuster - 2-Hit DMG: {1}
			0.34221,
			0.37007,
			0.39792,
			0.43771,
			0.46557,
			0.4974,
			0.54117,
			0.58494,
			0.62871,
			0.67646,
			0.72421,
			0.77197,
			0.81972,
			0.86747,
			0.91522,
		}},
		{
			{ // attack: CyclonicDuster - 3-Hit DMG: {2}+{3}
				0.22756,
				0.24608,
				0.2646,
				0.29106,
				0.30958,
				0.33075,
				0.35986,
				0.38896,
				0.41807,
				0.44982,
				0.48157,
				0.51332,
				0.54508,
				0.57683,
				0.60858,
			},
			{ // attack: CyclonicDuster - 3-Hit DMG: {2}+{3}
				0.22756,
				0.24608,
				0.2646,
				0.29106,
				0.30958,
				0.33075,
				0.35986,
				0.38896,
				0.41807,
				0.44982,
				0.48157,
				0.51332,
				0.54508,
				0.57683,
				0.60858,
			},
		},
		{{ // attack: CyclonicDuster - 4-Hit DMG: {4}
			0.56068,
			0.60631,
			0.65195,
			0.71715,
			0.76278,
			0.81494,
			0.88665,
			0.95837,
			1.03008,
			1.10831,
			1.18655,
			1.26478,
			1.34302,
			1.42125,
			1.49949,
		}},
	}
	// attack: CyclonicDuster - Charged Attack DMG: {5}
	charge = []float64{
		0.94944,
		1.02672,
		1.104,
		1.2144,
		1.29168,
		1.38,
		1.50144,
		1.62288,
		1.74432,
		1.8768,
		2.00928,
		2.14176,
		2.27424,
		2.40672,
		2.5392,
	}
	// attack: CyclonicDuster - Plunge DMG: {7}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: CyclonicDuster - Low/High Plunge DMG: {8}/{9}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: CyclonicDuster - Low/High Plunge DMG: {8}/{9}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: CleaningModeCarrierFrequency - Skill DMG: {0}
	skillInitial = []float64{
		0.864,
		0.9288,
		0.9936,
		1.08,
		1.1448,
		1.2096,
		1.296,
		1.3824,
		1.4688,
		1.5552,
		1.6416,
		1.728,
		1.836,
		1.944,
		2.052,
	}
	// skill: CleaningModeCarrierFrequency - Shield DMG Absorption: {1} ATK+{2}
	shieldAtk = []float64{
		2.21184,
		2.37773,
		2.54362,
		2.7648,
		2.93069,
		3.09658,
		3.31776,
		3.53894,
		3.76013,
		3.98131,
		4.2025,
		4.42368,
		4.70016,
		4.97664,
		5.25312,
	}
	// skill: CleaningModeCarrierFrequency - Shield DMG Absorption: {1} ATK+{2}
	shieldFlat = []float64{
		1386.676,
		1525.363,
		1675.607,
		1837.408,
		2010.767,
		2195.683,
		2392.156,
		2600.186,
		2819.773,
		3050.918,
		3293.62,
		3547.88,
		3813.696,
		4091.07,
		4380.0,
	}
	// skill: CleaningModeCarrierFrequency - Birgitta Discharge DMG: {3}
	skillDoT = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
	// burst: SupremeInstructionCyclonicExterminator - Skill DMG: {0}
	burst = []float64{
		6.768,
		7.2756,
		7.7832,
		8.46,
		8.9676,
		9.4752,
		10.152,
		10.8288,
		11.5056,
		12.1824,
		12.8592,
		13.536,
		14.382,
		15.228,
		16.074,
	}
)
