// Code generated by "pipeline"; DO NOT EDIT.

package sayu

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Sayu, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold", "short_hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Sayu, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: ShuumatsubanNinjaBlade - 1-Hit DMG: {0}
			0.7224,
			0.7812,
			0.84,
			0.924,
			0.9828,
			1.05,
			1.1424,
			1.2348,
			1.3272,
			1.428,
			1.5435,
			1.67933,
			1.81516,
			1.95098,
			2.09916,
		}},
		{{ // attack: ShuumatsubanNinjaBlade - 2-Hit DMG: {1}
			0.7138,
			0.7719,
			0.83,
			0.913,
			0.9711,
			1.0375,
			1.1288,
			1.2201,
			1.3114,
			1.411,
			1.52513,
			1.65934,
			1.79355,
			1.92776,
			2.07417,
		}},
		{
			{ // attack: ShuumatsubanNinjaBlade - 3-Hit DMG: {2}+{3}
				0.4343,
				0.46965,
				0.505,
				0.5555,
				0.59085,
				0.63125,
				0.6868,
				0.74235,
				0.7979,
				0.8585,
				0.92794,
				1.0096,
				1.09125,
				1.17291,
				1.26199,
			},
			{ // attack: ShuumatsubanNinjaBlade - 3-Hit DMG: {2}+{3}
				0.4343,
				0.46965,
				0.505,
				0.5555,
				0.59085,
				0.63125,
				0.6868,
				0.74235,
				0.7979,
				0.8585,
				0.92794,
				1.0096,
				1.09125,
				1.17291,
				1.26199,
			},
		},
		{{ // attack: ShuumatsubanNinjaBlade - 4-Hit DMG: {4}
			0.98126,
			1.06113,
			1.141,
			1.2551,
			1.33497,
			1.42625,
			1.55176,
			1.67727,
			1.80278,
			1.9397,
			2.09659,
			2.28109,
			2.46559,
			2.65009,
			2.85136,
		}},
	}
	// skill: YoohooArtFuuinDash - Fuufuu Windwheel DMG: {0}
	skillPress = []float64{
		0.36,
		0.387,
		0.414,
		0.45,
		0.477,
		0.504,
		0.54,
		0.576,
		0.612,
		0.648,
		0.684,
		0.72,
		0.765,
		0.81,
		0.855,
	}
	// skill: YoohooArtFuuinDash - Fuufuu Windwheel Elemental DMG: {1}
	skillAbsorb = []float64{
		0.168,
		0.1806,
		0.1932,
		0.21,
		0.2226,
		0.2352,
		0.252,
		0.2688,
		0.2856,
		0.3024,
		0.3192,
		0.336,
		0.357,
		0.378,
		0.399,
	}
	// skill: YoohooArtFuuinDash - Fuufuu Whirlwind Kick Press DMG: {2}
	skillPressEnd = []float64{
		1.584,
		1.7028,
		1.8216,
		1.98,
		2.0988,
		2.2176,
		2.376,
		2.5344,
		2.6928,
		2.8512,
		3.0096,
		3.168,
		3.366,
		3.564,
		3.762,
	}
	// skill: YoohooArtFuuinDash - Fuufuu Whirlwind Kick Hold DMG: {3}
	skillHoldEnd = []float64{
		2.176,
		2.3392,
		2.5024,
		2.72,
		2.8832,
		3.0464,
		3.264,
		3.4816,
		3.6992,
		3.9168,
		4.1344,
		4.352,
		4.624,
		4.896,
		5.168,
	}
	// skill: YoohooArtFuuinDash - Fuufuu Whirlwind Kick Elemental DMG: {4}
	skillAbsorbEnd = []float64{
		0.7616,
		0.81872,
		0.87584,
		0.952,
		1.00912,
		1.06624,
		1.1424,
		1.21856,
		1.29472,
		1.37088,
		1.44704,
		1.5232,
		1.6184,
		1.7136,
		1.8088,
	}
	// burst: YoohooArtMujinaFlurry - Skill Activation DMG: {0}
	burst = []float64{
		1.168,
		1.2556,
		1.3432,
		1.46,
		1.5476,
		1.6352,
		1.752,
		1.8688,
		1.9856,
		2.1024,
		2.2192,
		2.336,
		2.482,
		2.628,
		2.774,
	}
	// burst: YoohooArtMujinaFlurry - Skill Activation Healing: {2} ATK+{1}
	initHealFlat = []float64{
		577.3388,
		635.0807,
		697.6345,
		765.0,
		837.1774,
		914.1666,
		995.9677,
		1082.58,
		1174.005,
		1270.242,
		1371.29,
		1477.15,
		1587.822,
		1703.306,
		1823.602,
	}
	// burst: YoohooArtMujinaFlurry - Skill Activation Healing: {2} ATK+{1}
	initHealPP = []float64{
		0.9216,
		0.99072,
		1.05984,
		1.152,
		1.22112,
		1.29024,
		1.3824,
		1.47456,
		1.56672,
		1.65888,
		1.75104,
		1.8432,
		1.9584,
		2.0736,
		2.1888,
	}
	// burst: YoohooArtMujinaFlurry - Muji-Muji Daruma DMG: {3}
	burstSkill = []float64{
		0.52,
		0.559,
		0.598,
		0.65,
		0.689,
		0.728,
		0.78,
		0.832,
		0.884,
		0.936,
		0.988,
		1.04,
		1.105,
		1.17,
		1.235,
	}
	// burst: YoohooArtMujinaFlurry - Muji-Muji Daruma Healing: {5} ATK+{4}
	burstHealFlat = []float64{
		500.3603,
		550.4033,
		604.6165,
		663.0,
		725.5537,
		792.2777,
		863.1719,
		938.2364,
		1017.471,
		1100.876,
		1188.451,
		1280.197,
		1376.113,
		1476.198,
		1580.455,
	}
	// burst: YoohooArtMujinaFlurry - Muji-Muji Daruma Healing: {5} ATK+{4}
	burstHealPP = []float64{
		0.79872,
		0.85862,
		0.91853,
		0.9984,
		1.0583,
		1.11821,
		1.19808,
		1.27795,
		1.35782,
		1.4377,
		1.51757,
		1.59744,
		1.69728,
		1.79712,
		1.89696,
	}
)
