// Code generated by "pipeline"; DO NOT EDIT.

package xinyan

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Xinyan, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Xinyan, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: DanceOnFire - 1-Hit DMG: {0}
			0.7654,
			0.8277,
			0.89,
			0.979,
			1.0413,
			1.1125,
			1.2104,
			1.3083,
			1.4062,
			1.513,
			1.6198,
			1.7266,
			1.8334,
			1.9402,
			2.047,
		},
		{ // attack: DanceOnFire - 2-Hit DMG: {1}
			0.7396,
			0.7998,
			0.86,
			0.946,
			1.0062,
			1.075,
			1.1696,
			1.2642,
			1.3588,
			1.462,
			1.5652,
			1.6684,
			1.7716,
			1.8748,
			1.978,
		},
		{ // attack: DanceOnFire - 3-Hit DMG: {2}
			0.9546,
			1.0323,
			1.11,
			1.221,
			1.2987,
			1.3875,
			1.5096,
			1.6317,
			1.7538,
			1.887,
			2.0202,
			2.1534,
			2.2866,
			2.4198,
			2.553,
		},
		{ // attack: DanceOnFire - 4-Hit DMG: {3}
			1.15842,
			1.25271,
			1.347,
			1.4817,
			1.57599,
			1.68375,
			1.83192,
			1.98009,
			2.12826,
			2.2899,
			2.45154,
			2.61318,
			2.77482,
			2.93646,
			3.0981,
		},
	}
	// attack: DanceOnFire - Plunge DMG: {8}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: DanceOnFire - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: DanceOnFire - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: SweepingFervor - Swing DMG: {0}
	skill = []float64{
		1.696,
		1.8232,
		1.9504,
		2.12,
		2.2472,
		2.3744,
		2.544,
		2.7136,
		2.8832,
		3.0528,
		3.2224,
		3.392,
		3.604,
		3.816,
		4.028,
	}
	// skill: SweepingFervor - Shield Level 1 DMG Absorption: {1} DEF+{2}
	shieldLevel1 = []float64{
		1.0404,
		1.11843,
		1.19646,
		1.3005,
		1.37853,
		1.45656,
		1.5606,
		1.66464,
		1.76868,
		1.87272,
		1.97676,
		2.0808,
		2.21085,
		2.3409,
		2.47095,
	}
	// skill: SweepingFervor - Shield Level 1 DMG Absorption: {1} DEF+{2}
	shieldLevel1Flat = []float64{
		500.5527,
		550.615,
		604.8491,
		663.255,
		725.8328,
		792.5825,
		863.5039,
		938.5973,
		1017.862,
		1101.3,
		1188.908,
		1280.689,
		1376.642,
		1476.766,
		1581.063,
	}
	// skill: SweepingFervor - Shield Level 2 DMG Absorption: {3} DEF+{4}
	shieldLevel2 = []float64{
		1.224,
		1.3158,
		1.4076,
		1.53,
		1.6218,
		1.7136,
		1.836,
		1.9584,
		2.0808,
		2.2032,
		2.3256,
		2.448,
		2.601,
		2.754,
		2.907,
	}
	// skill: SweepingFervor - Shield Level 2 DMG Absorption: {3} DEF+{4}
	shieldLevel2Flat = []float64{
		588.8856,
		647.7823,
		711.5872,
		780.3,
		853.921,
		932.45,
		1015.887,
		1104.232,
		1197.485,
		1295.646,
		1398.716,
		1506.693,
		1619.579,
		1737.372,
		1860.074,
	}
	// skill: SweepingFervor - Shield Level 3 DMG Absorption: {5} DEF+{6}
	shieldLevel3 = []float64{
		1.44,
		1.548,
		1.656,
		1.8,
		1.908,
		2.016,
		2.16,
		2.304,
		2.448,
		2.592,
		2.736,
		2.88,
		3.06,
		3.24,
		3.42,
	}
	// skill: SweepingFervor - Shield Level 3 DMG Absorption: {5} DEF+{6}
	shieldLevel3Flat = []float64{
		692.8066,
		762.0969,
		837.1613,
		918.0,
		1004.613,
		1097.0,
		1195.161,
		1299.097,
		1408.806,
		1524.29,
		1645.548,
		1772.58,
		1905.387,
		2043.967,
		2188.322,
	}
	// skill: SweepingFervor - DoT: {7}
	skillDot = []float64{
		0.336,
		0.3612,
		0.3864,
		0.42,
		0.4452,
		0.4704,
		0.504,
		0.5376,
		0.5712,
		0.6048,
		0.6384,
		0.672,
		0.714,
		0.756,
		0.798,
	}
	// burst: RiffRevolution - Skill DMG: {0}
	burstDmg = []float64{
		3.408,
		3.6636,
		3.9192,
		4.26,
		4.5156,
		4.7712,
		5.112,
		5.4528,
		5.7936,
		6.1344,
		6.4752,
		6.816,
		7.242,
		7.668,
		8.094,
	}
	// burst: RiffRevolution - Pyro DoT: {1}
	burstDot = []float64{
		0.4,
		0.43,
		0.46,
		0.5,
		0.53,
		0.56,
		0.6,
		0.64,
		0.68,
		0.72,
		0.76,
		0.8,
		0.85,
		0.9,
		0.95,
	}
)
