// Code generated by "pipeline"; DO NOT EDIT.

package keqing

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Keqing, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Keqing, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: YunlaiSwordsmanship - 1-Hit DMG: {0}
			0.41022,
			0.44361,
			0.477,
			0.5247,
			0.55809,
			0.59625,
			0.64872,
			0.70119,
			0.75366,
			0.8109,
			0.86814,
			0.92538,
			0.98262,
			1.03986,
			1.0971,
		}},
		{{ // attack: YunlaiSwordsmanship - 2-Hit DMG: {1}
			0.41022,
			0.44361,
			0.477,
			0.5247,
			0.55809,
			0.59625,
			0.64872,
			0.70119,
			0.75366,
			0.8109,
			0.86814,
			0.92538,
			0.98262,
			1.03986,
			1.0971,
		}},
		{{ // attack: YunlaiSwordsmanship - 3-Hit DMG: {2}
			0.54438,
			0.58869,
			0.633,
			0.6963,
			0.74061,
			0.79125,
			0.86088,
			0.93051,
			1.00014,
			1.0761,
			1.15206,
			1.22802,
			1.30398,
			1.37994,
			1.4559,
		}},
		{
			{ // attack: YunlaiSwordsmanship - 4-Hit DMG: {3}+{4}
				0.31476,
				0.34038,
				0.366,
				0.4026,
				0.42822,
				0.4575,
				0.49776,
				0.53802,
				0.57828,
				0.6222,
				0.66612,
				0.71004,
				0.75396,
				0.79788,
				0.8418,
			},
			{ // attack: YunlaiSwordsmanship - 4-Hit DMG: {3}+{4}
				0.344,
				0.372,
				0.4,
				0.44,
				0.468,
				0.5,
				0.544,
				0.588,
				0.632,
				0.68,
				0.728,
				0.776,
				0.824,
				0.872,
				0.92,
			},
		},
		{{ // attack: YunlaiSwordsmanship - 5-Hit DMG: {5}
			0.66994,
			0.72447,
			0.779,
			0.8569,
			0.91143,
			0.97375,
			1.05944,
			1.14513,
			1.23082,
			1.3243,
			1.41778,
			1.51126,
			1.60474,
			1.69822,
			1.7917,
		}},
	}
	charge = [][]float64{
		{ // attack: YunlaiSwordsmanship - Charged Attack DMG: {6}+{7}
			0.76798,
			0.83049,
			0.893,
			0.9823,
			1.04481,
			1.11625,
			1.21448,
			1.31271,
			1.41094,
			1.5181,
			1.62526,
			1.73242,
			1.83958,
			1.94674,
			2.0539,
		},
		{ // attack: YunlaiSwordsmanship - Charged Attack DMG: {6}+{7}
			0.86,
			0.93,
			1.0,
			1.1,
			1.17,
			1.25,
			1.36,
			1.47,
			1.58,
			1.7,
			1.82,
			1.94,
			2.06,
			2.18,
			2.3,
		},
	}
	// attack: YunlaiSwordsmanship - Plunge DMG: {9}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: YunlaiSwordsmanship - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: YunlaiSwordsmanship - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: StellarRestoration - Lightning Stiletto DMG: {0}
	skill = []float64{
		0.504,
		0.5418,
		0.5796,
		0.63,
		0.6678,
		0.7056,
		0.756,
		0.8064,
		0.8568,
		0.9072,
		0.9576,
		1.008,
		1.071,
		1.134,
		1.197,
	}
	// skill: StellarRestoration - Slashing DMG: {1}
	skillPress = []float64{
		1.68,
		1.806,
		1.932,
		2.1,
		2.226,
		2.352,
		2.52,
		2.688,
		2.856,
		3.024,
		3.192,
		3.36,
		3.57,
		3.78,
		3.99,
	}
	// skill: StellarRestoration - Thunderclap Slash DMG: {2}×2
	skillCA = []float64{
		0.84,
		0.903,
		0.966,
		1.05,
		1.113,
		1.176,
		1.26,
		1.344,
		1.428,
		1.512,
		1.596,
		1.68,
		1.785,
		1.89,
		1.995,
	}
	// burst: StarwardSword - Skill DMG: {0}
	burstInitial = []float64{
		0.88,
		0.946,
		1.012,
		1.1,
		1.166,
		1.232,
		1.32,
		1.408,
		1.496,
		1.584,
		1.672,
		1.76,
		1.87,
		1.98,
		2.09,
	}
	// burst: StarwardSword - Consecutive Slash DMG: {1}×8
	burstDot = []float64{
		0.24,
		0.258,
		0.276,
		0.3,
		0.318,
		0.336,
		0.36,
		0.384,
		0.408,
		0.432,
		0.456,
		0.48,
		0.51,
		0.54,
		0.57,
	}
	// burst: StarwardSword - Last Attack DMG: {2}
	burstFinal = []float64{
		1.888,
		2.0296,
		2.1712,
		2.36,
		2.5016,
		2.6432,
		2.832,
		3.0208,
		3.2096,
		3.3984,
		3.5872,
		3.776,
		4.012,
		4.248,
		4.484,
	}
)
