// Code generated by "pipeline"; DO NOT EDIT.

package iansan

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Iansan, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Iansan, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	highATK = 0.27  // burst: TheThreePrinciplesOfPower - High Nightsoul Points ATK Conversion Rate: {1} ATK
	lowATK  = 0.005 // burst: TheThreePrinciplesOfPower - Low Nightsoul Points ATK Conversion Rate: {2} ATK / Nightsoul Point
)

var (
	attack = [][]float64{
		{ // attack: WeightedSpike - 1-Hit DMG: {0}
			0.46976,
			0.50799,
			0.54623,
			0.60085,
			0.63909,
			0.68279,
			0.74287,
			0.80296,
			0.86304,
			0.92859,
			0.99414,
			1.05969,
			1.12523,
			1.19078,
			1.25633,
		},
		{ // attack: WeightedSpike - 2-Hit DMG: {1}
			0.42764,
			0.46245,
			0.49726,
			0.54699,
			0.58179,
			0.62157,
			0.67627,
			0.73097,
			0.78567,
			0.84534,
			0.90501,
			0.96468,
			1.02436,
			1.08403,
			1.1437,
		},
		{ // attack: WeightedSpike - 3-Hit DMG: {2}
			0.64388,
			0.69629,
			0.7487,
			0.82357,
			0.87598,
			0.93587,
			1.01823,
			1.10059,
			1.18295,
			1.27279,
			1.36263,
			1.45248,
			1.54232,
			1.63217,
			1.72201,
		},
	}
	// attack: WeightedSpike - Charged Attack DMG: {3}
	charge = []float64{
		1.00276,
		1.08438,
		1.166,
		1.2826,
		1.36422,
		1.4575,
		1.58576,
		1.71402,
		1.84228,
		1.9822,
		2.12212,
		2.26204,
		2.40196,
		2.54188,
		2.6818,
	}
	// attack: WeightedSpike - Swift Stormflight DMG: {4}
	swift = []float64{
		0.84194,
		0.91047,
		0.979,
		1.0769,
		1.14543,
		1.22375,
		1.33144,
		1.43913,
		1.54682,
		1.6643,
		1.78178,
		1.89926,
		2.01674,
		2.13422,
		2.2517,
	}
	// skill: ThunderboltRush - Skill DMG: {0}
	skill = []float64{
		2.864,
		3.0788,
		3.2936,
		3.58,
		3.7948,
		4.0096,
		4.296,
		4.5824,
		4.8688,
		5.1552,
		5.4416,
		5.728,
		6.086,
		6.444,
		6.802,
	}
	// burst: TheThreePrinciplesOfPower - Skill DMG: {0}
	burst = []float64{
		4.304,
		4.6268,
		4.9496,
		5.38,
		5.7028,
		6.0256,
		6.456,
		6.8864,
		7.3168,
		7.7472,
		8.1776,
		8.608,
		9.146,
		9.684,
		10.222,
	}
	// burst: TheThreePrinciplesOfPower - Max ATK Bonus: {3}
	maxATK = []float64{
		330.0,
		370.0,
		410.0,
		450.0,
		490.0,
		530.0,
		570.0,
		610.0,
		650.0,
		690.0,
		730.0,
		770.0,
		810.0,
		850.0,
		890.0,
	}
)
