// Code generated by "pipeline"; DO NOT EDIT.

package mavuika

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Mavuika, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionCharge:     {"buffered", "final", "hold"},
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold", "recast"},
		action.ActionDash:       {"charge_cancel", "collision", "travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Mavuika, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: FlamesWeaveLife - 1-Hit DMG: {0}
			0.80035,
			0.8655,
			0.93064,
			1.0237,
			1.08885,
			1.1633,
			1.26567,
			1.36804,
			1.47041,
			1.58209,
			1.69377,
			1.80544,
			1.91712,
			2.0288,
			2.14047,
		},
		{ // attack: FlamesWeaveLife - 2-Hit DMG: {1}×2
			0.3648,
			0.39449,
			0.42419,
			0.4666,
			0.4963,
			0.53023,
			0.57689,
			0.62355,
			0.67021,
			0.72111,
			0.77202,
			0.82292,
			0.87382,
			0.92472,
			0.97562,
		},
		{ // attack: FlamesWeaveLife - 3-Hit DMG: {2}×3
			0.33223,
			0.35927,
			0.38632,
			0.42495,
			0.45199,
			0.4829,
			0.52539,
			0.56788,
			0.61038,
			0.65674,
			0.7031,
			0.74945,
			0.79581,
			0.84217,
			0.88853,
		},
		{ // attack: FlamesWeaveLife - 4-Hit DMG: {3}
			1.16193,
			1.2565,
			1.35108,
			1.48619,
			1.58076,
			1.68885,
			1.83747,
			1.98609,
			2.13471,
			2.29684,
			2.45897,
			2.62109,
			2.78323,
			2.94535,
			3.10748,
		},
	}
	// attack: FlamesWeaveLife - Charged Attack DMG: {4}
	charge = []float64{
		1.93844,
		2.09622,
		2.254,
		2.4794,
		2.63718,
		2.8175,
		3.06544,
		3.31338,
		3.56132,
		3.8318,
		4.10228,
		4.37276,
		4.64324,
		4.91372,
		5.1842,
	}
	// attack: FlamesWeaveLife - Plunge DMG: {6}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: FlamesWeaveLife - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: FlamesWeaveLife - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: TheNamedMoment - Skill DMG: {0}
	skill = []float64{
		0.744,
		0.7998,
		0.8556,
		0.93,
		0.9858,
		1.0416,
		1.116,
		1.1904,
		1.2648,
		1.3392,
		1.4136,
		1.488,
		1.581,
		1.674,
		1.767,
	}
	// skill: TheNamedMoment - Ring of Searing Radiance DMG: {1}
	skillRing = []float64{
		1.28,
		1.376,
		1.472,
		1.6,
		1.696,
		1.792,
		1.92,
		2.048,
		2.176,
		2.304,
		2.432,
		2.56,
		2.72,
		2.88,
		3.04,
	}
	skillAttack = [][]float64{
		{ // skill: TheNamedMoment - Flamestrider Normal Attack 1-Hit DMG: {3}
			0.57265,
			0.61926,
			0.66587,
			0.73246,
			0.77907,
			0.83234,
			0.90558,
			0.97883,
			1.05208,
			1.13198,
			1.21188,
			1.29179,
			1.37169,
			1.4516,
			1.5315,
		},
		{ // skill: TheNamedMoment - Flamestrider Normal Attack 2-Hit DMG: {4}
			0.59133,
			0.63946,
			0.68759,
			0.75635,
			0.80448,
			0.85949,
			0.93512,
			1.01076,
			1.08639,
			1.1689,
			1.25141,
			1.33393,
			1.41644,
			1.49895,
			1.58146,
		},
		{ // skill: TheNamedMoment - Flamestrider Normal Attack 3-Hit DMG: {5}
			0.69987,
			0.75683,
			0.8138,
			0.89518,
			0.95215,
			1.01725,
			1.10677,
			1.19629,
			1.2858,
			1.38346,
			1.48112,
			1.57877,
			1.67643,
			1.77408,
			1.87174,
		},
		{ // skill: TheNamedMoment - Flamestrider Normal Attack 4-Hit DMG: {6}
			0.69705,
			0.75378,
			0.81052,
			0.89157,
			0.94831,
			1.01315,
			1.10231,
			1.19146,
			1.28062,
			1.37788,
			1.47515,
			1.57241,
			1.66967,
			1.76693,
			1.8642,
		},
		{ // skill: TheNamedMoment - Flamestrider Normal Attack 5-Hit DMG: {7}
			0.91004,
			0.98411,
			1.05818,
			1.164,
			1.23807,
			1.32273,
			1.43912,
			1.55552,
			1.67192,
			1.79891,
			1.92589,
			2.05287,
			2.17985,
			2.30683,
			2.43381,
		},
	}
	// skill: TheNamedMoment - Flamestrider Sprint DMG: {8}
	skillDash = []float64{
		0.8084,
		0.8742,
		0.94,
		1.034,
		1.0998,
		1.175,
		1.2784,
		1.3818,
		1.4852,
		1.598,
		1.7108,
		1.8236,
		1.9364,
		2.0492,
		2.162,
	}
	// skill: TheNamedMoment - Flamestrider Charged Attack Cyclic DMG: {9}
	skillCharge = []float64{
		0.989,
		1.0695,
		1.15,
		1.265,
		1.3455,
		1.4375,
		1.564,
		1.6905,
		1.817,
		1.955,
		2.093,
		2.231,
		2.369,
		2.507,
		2.645,
	}
	// skill: TheNamedMoment - Flamestrider Charged Attack Final DMG: {10}
	skillChargeFinal = []float64{
		1.376,
		1.488,
		1.6,
		1.76,
		1.872,
		2.0,
		2.176,
		2.352,
		2.528,
		2.72,
		2.912,
		3.104,
		3.296,
		3.488,
		3.68,
	}
	// skill: TheNamedMoment - Flamestrider Plunge DMG: {11}
	skillPlunge = []float64{
		1.5996,
		1.7298,
		1.86,
		2.046,
		2.1762,
		2.325,
		2.5296,
		2.7342,
		2.9388,
		3.162,
		3.3852,
		3.6084,
		3.8316,
		4.0548,
		4.278,
	}
	// burst: HourOfBurningSkies - Skill DMG: {0}
	burst = []float64{
		4.448,
		4.7816,
		5.1152,
		5.56,
		5.8936,
		6.2272,
		6.672,
		7.1168,
		7.5616,
		8.0064,
		8.4512,
		8.896,
		9.452,
		10.008,
		10.564,
	}
	// burst: HourOfBurningSkies - Sunfell Slice DMG Bonus: {2} ATK per Fighting Spirit
	burstQBonus = []float64{
		0.016,
		0.0172,
		0.0184,
		0.02,
		0.0212,
		0.0224,
		0.024,
		0.0256,
		0.0272,
		0.0288,
		0.0304,
		0.032,
		0.034,
		0.036,
		0.038,
	}
	// burst: HourOfBurningSkies - Flamestrider Normal Attack DMG Bonus: {3} ATK per Fighting Spirit
	burstNABonus = []float64{
		0.00258,
		0.00279,
		0.003,
		0.0033,
		0.00351,
		0.00375,
		0.00408,
		0.00441,
		0.00474,
		0.0051,
		0.00546,
		0.00582,
		0.00618,
		0.00654,
		0.0069,
	}
	// burst: HourOfBurningSkies - Flamestrider Charged Attack DMG Bonus: {4} ATK per Fighting Spirit
	burstCABonus = []float64{
		0.00516,
		0.00558,
		0.006,
		0.0066,
		0.00702,
		0.0075,
		0.00816,
		0.00882,
		0.00948,
		0.0102,
		0.01092,
		0.01164,
		0.01236,
		0.01308,
		0.0138,
	}
)
