// Code generated by "pipeline"; DO NOT EDIT.

package ayato

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.KamisatoAyato, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"illusion_delay"},
	}
	validation.RegisterCharParamValidationFunc(keys.KamisatoAyato, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: KamisatoArtMarobashi - 1-Hit DMG: {0}
			0.44962,
			0.48621,
			0.52281,
			0.57509,
			0.61169,
			0.65351,
			0.71102,
			0.76853,
			0.82604,
			0.88878,
			0.95151,
			1.01425,
			1.07699,
			1.13973,
			1.20246,
		}},
		{{ // attack: KamisatoArtMarobashi - 2-Hit DMG: {1}
			0.47157,
			0.50996,
			0.54834,
			0.60317,
			0.64156,
			0.68542,
			0.74574,
			0.80606,
			0.86638,
			0.93218,
			0.99798,
			1.06378,
			1.12958,
			1.19538,
			1.26118,
		}},
		{{ // attack: KamisatoArtMarobashi - 3-Hit DMG: {2}
			0.58612,
			0.63383,
			0.68154,
			0.74969,
			0.7974,
			0.85193,
			0.92689,
			1.00186,
			1.07683,
			1.15862,
			1.2404,
			1.32219,
			1.40397,
			1.48576,
			1.56754,
		}},
		{
			{ // attack: KamisatoArtMarobashi - 4-Hit DMG: {3}×2
				0.29449,
				0.31846,
				0.34242,
				0.37667,
				0.40064,
				0.42803,
				0.4657,
				0.50336,
				0.54103,
				0.58212,
				0.62321,
				0.6643,
				0.70539,
				0.74649,
				0.78758,
			},
			{ // attack: KamisatoArtMarobashi - 4-Hit DMG: {3}×2
				0.29449,
				0.31846,
				0.34242,
				0.37667,
				0.40064,
				0.42803,
				0.4657,
				0.50336,
				0.54103,
				0.58212,
				0.62321,
				0.6643,
				0.70539,
				0.74649,
				0.78758,
			},
		},
		{{ // attack: KamisatoArtMarobashi - 5-Hit DMG: {4}
			0.75604,
			0.81758,
			0.87912,
			0.96703,
			1.02857,
			1.0989,
			1.1956,
			1.29231,
			1.38901,
			1.4945,
			1.6,
			1.70549,
			1.81099,
			1.91648,
			2.02198,
		}},
	}
	// attack: KamisatoArtMarobashi - Charged Attack DMG: {5}
	ca = []float64{
		1.2953,
		1.40073,
		1.50616,
		1.65677,
		1.76221,
		1.8827,
		2.04838,
		2.21405,
		2.37973,
		2.56047,
		2.74121,
		2.92195,
		3.10269,
		3.28343,
		3.46417,
	}
	// attack: KamisatoArtMarobashi - Plunge DMG: {7}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: KamisatoArtMarobashi - Low/High Plunge DMG: {8}/{9}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: KamisatoArtMarobashi - Low/High Plunge DMG: {8}/{9}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	shunsuiken = [][]float64{
		{ // skill: KamisatoArtKyouka - Shunsuiken 1-Hit DMG: {0}
			0.5289,
			0.57195,
			0.615,
			0.6765,
			0.71955,
			0.76875,
			0.8364,
			0.90405,
			0.9717,
			1.0455,
			1.1193,
			1.1931,
			1.2669,
			1.3407,
			1.4145,
		},
		{ // skill: KamisatoArtKyouka - Shunsuiken 2-Hit DMG: {1}
			0.5891,
			0.63705,
			0.685,
			0.7535,
			0.80145,
			0.85625,
			0.9316,
			1.00695,
			1.0823,
			1.1645,
			1.2467,
			1.3289,
			1.4111,
			1.4933,
			1.5755,
		},
		{ // skill: KamisatoArtKyouka - Shunsuiken 3-Hit DMG: {2}
			0.6493,
			0.70215,
			0.755,
			0.8305,
			0.88335,
			0.94375,
			1.0268,
			1.10985,
			1.1929,
			1.2835,
			1.3741,
			1.4647,
			1.5553,
			1.6459,
			1.7365,
		},
	}
	// skill: KamisatoArtKyouka - Namisen DMG Bonus: {4}Max HP/Stack
	skillpp = []float64{
		0.00561,
		0.00607,
		0.00652,
		0.00718,
		0.00763,
		0.00816,
		0.00887,
		0.00959,
		0.01031,
		0.01109,
		0.01187,
		0.01266,
		0.01344,
		0.01422,
		0.015,
	}
	// skill: KamisatoArtKyouka - Water Illusion DMG: {5}
	skill = []float64{
		1.0148,
		1.0974,
		1.18,
		1.298,
		1.3806,
		1.475,
		1.6048,
		1.7346,
		1.8644,
		2.006,
		2.1476,
		2.2892,
		2.4308,
		2.5724,
		2.714,
	}
	// burst: KamisatoArtSuiyuu - Bloomwater Blade DMG: {0}
	burst = []float64{
		0.66456,
		0.7144,
		0.76424,
		0.8307,
		0.88054,
		0.93038,
		0.99684,
		1.0633,
		1.12975,
		1.19621,
		1.26266,
		1.32912,
		1.41219,
		1.49526,
		1.57833,
	}
	// burst: KamisatoArtSuiyuu - Normal Attack DMG Bonus: {1}
	burstatkp = []float64{
		0.11,
		0.12,
		0.13,
		0.14,
		0.15,
		0.16,
		0.17,
		0.18,
		0.19,
		0.2,
		0.2,
		0.2,
		0.2,
		0.2,
		0.2,
	}
)
