// Code generated by "pipeline"; DO NOT EDIT.

package xingqiu

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Xingqiu, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Xingqiu, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: GuhuaStyle - 1-Hit DMG: {0}
			0.46612,
			0.50406,
			0.542,
			0.5962,
			0.63414,
			0.6775,
			0.73712,
			0.79674,
			0.85636,
			0.9214,
			0.99593,
			1.08357,
			1.17121,
			1.25885,
			1.35446,
		}},
		{{ // attack: GuhuaStyle - 2-Hit DMG: {1}
			0.47644,
			0.51522,
			0.554,
			0.6094,
			0.64818,
			0.6925,
			0.75344,
			0.81438,
			0.87532,
			0.9418,
			1.01797,
			1.10756,
			1.19714,
			1.28672,
			1.38445,
		}},
		{
			{ // attack: GuhuaStyle - 3-Hit DMG: {2}+{3}
				0.28552,
				0.30876,
				0.332,
				0.3652,
				0.38844,
				0.415,
				0.45152,
				0.48804,
				0.52456,
				0.5644,
				0.61005,
				0.66373,
				0.71742,
				0.7711,
				0.82967,
			},
			{ // attack: GuhuaStyle - 3-Hit DMG: {2}+{3}
				0.28552,
				0.30876,
				0.332,
				0.3652,
				0.38844,
				0.415,
				0.45152,
				0.48804,
				0.52456,
				0.5644,
				0.61005,
				0.66373,
				0.71742,
				0.7711,
				0.82967,
			},
		},
		{{ // attack: GuhuaStyle - 4-Hit DMG: {4}
			0.55986,
			0.60543,
			0.651,
			0.7161,
			0.76167,
			0.81375,
			0.88536,
			0.95697,
			1.02858,
			1.1067,
			1.19621,
			1.30148,
			1.40675,
			1.51201,
			1.62685,
		}},
		{
			{ // attack: GuhuaStyle - 5-Hit DMG: {5}+{6}
				0.35862,
				0.38781,
				0.417,
				0.4587,
				0.48789,
				0.52125,
				0.56712,
				0.61299,
				0.65886,
				0.7089,
				0.76624,
				0.83367,
				0.90109,
				0.96852,
				1.04208,
			},
			{ // attack: GuhuaStyle - 5-Hit DMG: {5}+{6}
				0.35862,
				0.38781,
				0.417,
				0.4587,
				0.48789,
				0.52125,
				0.56712,
				0.61299,
				0.65886,
				0.7089,
				0.76624,
				0.83367,
				0.90109,
				0.96852,
				1.04208,
			},
		},
	}
	ca = [][]float64{
		{ // attack: GuhuaStyle - Charged Attack DMG: {7}+{8}
			0.473,
			0.5115,
			0.55,
			0.605,
			0.6435,
			0.6875,
			0.748,
			0.8085,
			0.869,
			0.935,
			1.01063,
			1.09956,
			1.1885,
			1.27743,
			1.37445,
		},
		{ // attack: GuhuaStyle - Charged Attack DMG: {7}+{8}
			0.56158,
			0.60729,
			0.653,
			0.7183,
			0.76401,
			0.81625,
			0.88808,
			0.95991,
			1.03174,
			1.1101,
			1.19989,
			1.30548,
			1.41107,
			1.51666,
			1.63185,
		},
	}
	rainscreen = [][]float64{
		{ // skill: GuhuaSwordFatalRainscreen - Skill DMG: {0}+{1}
			1.68,
			1.806,
			1.932,
			2.1,
			2.226,
			2.352,
			2.52,
			2.688,
			2.856,
			3.024,
			3.192,
			3.36,
			3.57,
			3.78,
			3.99,
		},
		{ // skill: GuhuaSwordFatalRainscreen - Skill DMG: {0}+{1}
			1.912,
			2.0554,
			2.1988,
			2.39,
			2.5334,
			2.6768,
			2.868,
			3.0592,
			3.2504,
			3.4416,
			3.6328,
			3.824,
			4.063,
			4.302,
			4.541,
		},
	}
	// burst: GuhuaSwordRaincutter - Sword Rain DMG: {0}
	burst = []float64{
		0.54272,
		0.58342,
		0.62413,
		0.6784,
		0.7191,
		0.75981,
		0.81408,
		0.86835,
		0.92262,
		0.9769,
		1.03117,
		1.08544,
		1.15328,
		1.22112,
		1.28896,
	}
)
