// Code generated by "pipeline"; DO NOT EDIT.

package wriothesley

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Wriothesley, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Wriothesley, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: ForcefulFistsOfFrost - 1-Hit DMG: {0}
			0.5336,
			0.57703,
			0.62046,
			0.68251,
			0.72594,
			0.77557,
			0.84383,
			0.91208,
			0.98033,
			1.05478,
			1.12924,
			1.20369,
			1.27815,
			1.3526,
			1.42706,
		}},
		{{ // attack: ForcefulFistsOfFrost - 2-Hit DMG: {1}
			0.51799,
			0.56015,
			0.60231,
			0.66254,
			0.7047,
			0.75289,
			0.81914,
			0.8854,
			0.95165,
			1.02393,
			1.0962,
			1.16848,
			1.24076,
			1.31304,
			1.38531,
		}},
		{{ // attack: ForcefulFistsOfFrost - 3-Hit DMG: {2}
			0.67223,
			0.72694,
			0.78166,
			0.85983,
			0.91454,
			0.97707,
			1.06306,
			1.14904,
			1.23502,
			1.32882,
			1.42262,
			1.51642,
			1.61022,
			1.70402,
			1.79782,
		}},
		{
			{ // attack: ForcefulFistsOfFrost - 4-Hit DMG: {3}+{4}
				0.37904,
				0.40989,
				0.44074,
				0.48482,
				0.51567,
				0.55093,
				0.59941,
				0.64789,
				0.69638,
				0.74927,
				0.80216,
				0.85505,
				0.90794,
				0.96082,
				1.01371,
			},
			{ // attack: ForcefulFistsOfFrost - 4-Hit DMG: {3}+{4}
				0.37904,
				0.40989,
				0.44074,
				0.48482,
				0.51567,
				0.55093,
				0.59941,
				0.64789,
				0.69638,
				0.74927,
				0.80216,
				0.85505,
				0.90794,
				0.96082,
				1.01371,
			},
		},
		{{ // attack: ForcefulFistsOfFrost - 5-Hit DMG: {5}
			0.90742,
			0.98128,
			1.05514,
			1.16065,
			1.23451,
			1.31893,
			1.43499,
			1.55106,
			1.66712,
			1.79374,
			1.92035,
			2.04697,
			2.17359,
			2.3002,
			2.42682,
		}},
	}
	// attack: ForcefulFistsOfFrost - Charged Attack DMG: {6}
	charge = []float64{
		1.5296,
		1.64432,
		1.75904,
		1.912,
		2.02672,
		2.14144,
		2.2944,
		2.44736,
		2.60032,
		2.75328,
		2.90624,
		3.0592,
		3.2504,
		3.4416,
		3.6328,
	}
	// attack: ForcefulFistsOfFrost - Plunge DMG: {8}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: ForcefulFistsOfFrost - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: ForcefulFistsOfFrost - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: IcefangRush - Enhanced Repelling Fist DMG: {0} Normal Attack DMG
	skill = []float64{
		1.43169,
		1.45755,
		1.48339,
		1.517,
		1.54285,
		1.5687,
		1.60231,
		1.63591,
		1.66952,
		1.70312,
		1.73672,
		1.77033,
		1.80394,
		1.83754,
		1.87115,
	}
	// burst: DarkgoldWolfbite - Skill DMG: {0}×5
	burst = []float64{
		1.272,
		1.3674,
		1.4628,
		1.59,
		1.6854,
		1.7808,
		1.908,
		2.0352,
		2.1624,
		2.2896,
		2.4168,
		2.544,
		2.703,
		2.862,
		3.021,
	}
	// burst: DarkgoldWolfbite - Surging Blade DMG: {1}
	burstOusia = []float64{
		0.424,
		0.4558,
		0.4876,
		0.53,
		0.5618,
		0.5936,
		0.636,
		0.6784,
		0.7208,
		0.7632,
		0.8056,
		0.848,
		0.901,
		0.954,
		1.007,
	}
)
