// Code generated by "pipeline"; DO NOT EDIT.

package barbara

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Barbara, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Barbara, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: WhisperOfWater - 1-Hit DMG: {0}
			0.3784,
			0.40678,
			0.43516,
			0.473,
			0.50138,
			0.52976,
			0.5676,
			0.60544,
			0.64328,
			0.68112,
			0.72047,
			0.77194,
			0.8234,
			0.87486,
			0.92632,
		},
		{ // attack: WhisperOfWater - 2-Hit DMG: {1}
			0.3552,
			0.38184,
			0.40848,
			0.444,
			0.47064,
			0.49728,
			0.5328,
			0.56832,
			0.60384,
			0.63936,
			0.6763,
			0.72461,
			0.77292,
			0.82122,
			0.86953,
		},
		{ // attack: WhisperOfWater - 3-Hit DMG: {2}
			0.4104,
			0.44118,
			0.47196,
			0.513,
			0.54378,
			0.57456,
			0.6156,
			0.65664,
			0.69768,
			0.73872,
			0.7814,
			0.83722,
			0.89303,
			0.94885,
			1.00466,
		},
		{ // attack: WhisperOfWater - 4-Hit DMG: {3}
			0.552,
			0.5934,
			0.6348,
			0.69,
			0.7314,
			0.7728,
			0.828,
			0.8832,
			0.9384,
			0.9936,
			1.05101,
			1.12608,
			1.20115,
			1.27622,
			1.3513,
		},
	}
	// attack: WhisperOfWater - Charged Attack DMG: {4}
	charge = []float64{
		1.6624,
		1.78708,
		1.91176,
		2.078,
		2.20268,
		2.32736,
		2.4936,
		2.65984,
		2.82608,
		2.99232,
		3.16521,
		3.3913,
		3.61738,
		3.84347,
		4.06955,
	}
	// attack: WhisperOfWater - Plunge DMG: {6}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: WhisperOfWater - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: WhisperOfWater - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: LetTheShowBegin - Continuous Regeneration: {0} Max HP+{1}
	skillhpp = []float64{
		0.04,
		0.043,
		0.046,
		0.05,
		0.053,
		0.056,
		0.06,
		0.064,
		0.068,
		0.072,
		0.076,
		0.08,
		0.085,
		0.09,
		0.095,
	}
	// skill: LetTheShowBegin - Continuous Regeneration: {0} Max HP+{1}
	skillhp = []float64{
		385.1877,
		423.7119,
		465.4464,
		510.3912,
		558.5463,
		609.9118,
		664.4877,
		722.2739,
		783.2704,
		847.4773,
		914.8945,
		985.5221,
		1059.36,
		1136.408,
		1216.667,
	}
	// skill: LetTheShowBegin - HP Regeneration Per Hit: {2} Max HP+{3}
	prochpp = []float64{
		0.0075,
		0.00806,
		0.00862,
		0.00938,
		0.00994,
		0.0105,
		0.01125,
		0.012,
		0.01275,
		0.0135,
		0.01425,
		0.015,
		0.01594,
		0.01688,
		0.01781,
	}
	// skill: LetTheShowBegin - HP Regeneration Per Hit: {2} Max HP+{3}
	prochp = []float64{
		72.2227,
		79.44598,
		87.27119,
		95.69834,
		104.7274,
		114.3585,
		124.5914,
		135.4264,
		146.8632,
		158.902,
		171.5427,
		184.7854,
		198.63,
		213.0766,
		228.125,
	}
	// skill: LetTheShowBegin - Droplet DMG: {4}
	skill = []float64{
		0.584,
		0.6278,
		0.6716,
		0.73,
		0.7738,
		0.8176,
		0.876,
		0.9344,
		0.9928,
		1.0512,
		1.1096,
		1.168,
		1.241,
		1.314,
		1.387,
	}
	// burst: ShiningMiracle - Regeneration: {0} Max HP+{1}
	bursthpp = []float64{
		0.176,
		0.1892,
		0.2024,
		0.22,
		0.2332,
		0.2464,
		0.264,
		0.2816,
		0.2992,
		0.3168,
		0.3344,
		0.352,
		0.374,
		0.396,
		0.418,
	}
	// burst: ShiningMiracle - Regeneration: {0} Max HP+{1}
	bursthp = []float64{
		1694.282,
		1863.734,
		2047.306,
		2245.0,
		2456.815,
		2682.75,
		2922.807,
		3176.985,
		3445.283,
		3727.703,
		4024.243,
		4334.905,
		4659.687,
		4998.591,
		5351.615,
	}
)
