// Code generated by "pipeline"; DO NOT EDIT.

package ayaka

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.KamisatoAyaka, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionDash:       {"f"},
	}
	validation.RegisterCharParamValidationFunc(keys.KamisatoAyaka, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: KamisatoArtKabuki - 1-Hit DMG: {0}
			0.45725,
			0.49447,
			0.53169,
			0.58486,
			0.62208,
			0.66461,
			0.7231,
			0.78158,
			0.84007,
			0.90387,
			0.96768,
			1.03148,
			1.09528,
			1.15908,
			1.22289,
		}},
		{{ // attack: KamisatoArtKabuki - 2-Hit DMG: {1}
			0.48685,
			0.52647,
			0.5661,
			0.62271,
			0.66234,
			0.70762,
			0.7699,
			0.83217,
			0.89444,
			0.96237,
			1.0303,
			1.09823,
			1.16617,
			1.2341,
			1.30203,
		}},
		{{ // attack: KamisatoArtKabuki - 3-Hit DMG: {2}
			0.62622,
			0.67719,
			0.72816,
			0.80098,
			0.85195,
			0.9102,
			0.9903,
			1.07039,
			1.15049,
			1.23787,
			1.32525,
			1.41263,
			1.50001,
			1.58739,
			1.67477,
		}},
		{
			{ // attack: KamisatoArtKabuki - 4-Hit DMG: {3}×3
				0.22646,
				0.2449,
				0.26333,
				0.28966,
				0.3081,
				0.32916,
				0.35813,
				0.3871,
				0.41606,
				0.44766,
				0.47926,
				0.51086,
				0.54246,
				0.57406,
				0.60566,
			},
			{ // attack: KamisatoArtKabuki - 4-Hit DMG: {3}×3
				0.22646,
				0.2449,
				0.26333,
				0.28966,
				0.3081,
				0.32916,
				0.35813,
				0.3871,
				0.41606,
				0.44766,
				0.47926,
				0.51086,
				0.54246,
				0.57406,
				0.60566,
			},
			{ // attack: KamisatoArtKabuki - 4-Hit DMG: {3}×3
				0.22646,
				0.2449,
				0.26333,
				0.28966,
				0.3081,
				0.32916,
				0.35813,
				0.3871,
				0.41606,
				0.44766,
				0.47926,
				0.51086,
				0.54246,
				0.57406,
				0.60566,
			},
		},
		{{ // attack: KamisatoArtKabuki - 5-Hit DMG: {6}
			0.78182,
			0.84545,
			0.90909,
			1.0,
			1.06363,
			1.13636,
			1.23636,
			1.33636,
			1.43636,
			1.54545,
			1.65454,
			1.76364,
			1.87273,
			1.98182,
			2.09091,
		}},
	}
	// attack: KamisatoArtKabuki - Charged Attack DMG: {7}×3
	ca = []float64{
		0.55126,
		0.59613,
		0.641,
		0.7051,
		0.74997,
		0.80125,
		0.87176,
		0.94227,
		1.01278,
		1.0897,
		1.16662,
		1.24354,
		1.32046,
		1.39738,
		1.4743,
	}
	// attack: KamisatoArtKabuki - Plunge DMG: {9}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: KamisatoArtKabuki - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: KamisatoArtKabuki - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: KamisatoArtHyouka - Skill DMG: {0}
	skill = []float64{
		2.392,
		2.5714,
		2.7508,
		2.99,
		3.1694,
		3.3488,
		3.588,
		3.8272,
		4.0664,
		4.3056,
		4.5448,
		4.784,
		5.083,
		5.382,
		5.681,
	}
	// burst: KamisatoArtSoumetsu - Cutting DMG: {0}
	burstCut = []float64{
		1.123,
		1.20722,
		1.29145,
		1.40375,
		1.48798,
		1.5722,
		1.6845,
		1.7968,
		1.9091,
		2.0214,
		2.1337,
		2.246,
		2.38637,
		2.52675,
		2.66712,
	}
	// burst: KamisatoArtSoumetsu - Bloom DMG: {1}
	burstBloom = []float64{
		1.6845,
		1.81084,
		1.93718,
		2.10562,
		2.23196,
		2.3583,
		2.52675,
		2.6952,
		2.86365,
		3.0321,
		3.20055,
		3.369,
		3.57956,
		3.79012,
		4.00069,
	}
)
