// Code generated by "pipeline"; DO NOT EDIT.

package qiqi

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Qiqi, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Qiqi, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: AncientSwordArt - 1-Hit DMG: {0}
			0.37754,
			0.40827,
			0.439,
			0.4829,
			0.51363,
			0.54875,
			0.59704,
			0.64533,
			0.69362,
			0.7463,
			0.79898,
			0.85166,
			0.90434,
			0.95702,
			1.0097,
		}},
		{{ // attack: AncientSwordArt - 2-Hit DMG: {1}
			0.38872,
			0.42036,
			0.452,
			0.4972,
			0.52884,
			0.565,
			0.61472,
			0.66444,
			0.71416,
			0.7684,
			0.82264,
			0.87688,
			0.93112,
			0.98536,
			1.0396,
		}},
		{
			{ // attack: AncientSwordArt - 3-Hit DMG: {2}+{2}
				0.24166,
				0.26133,
				0.281,
				0.3091,
				0.32877,
				0.35125,
				0.38216,
				0.41307,
				0.44398,
				0.4777,
				0.51142,
				0.54514,
				0.57886,
				0.61258,
				0.6463,
			},
			{ // attack: AncientSwordArt - 3-Hit DMG: {2}+{2}
				0.24166,
				0.26133,
				0.281,
				0.3091,
				0.32877,
				0.35125,
				0.38216,
				0.41307,
				0.44398,
				0.4777,
				0.51142,
				0.54514,
				0.57886,
				0.61258,
				0.6463,
			},
		},
		{
			{ // attack: AncientSwordArt - 4-Hit DMG: {3}+{3}
				0.24682,
				0.26691,
				0.287,
				0.3157,
				0.33579,
				0.35875,
				0.39032,
				0.42189,
				0.45346,
				0.4879,
				0.52234,
				0.55678,
				0.59122,
				0.62566,
				0.6601,
			},
			{ // attack: AncientSwordArt - 4-Hit DMG: {3}+{3}
				0.24682,
				0.26691,
				0.287,
				0.3157,
				0.33579,
				0.35875,
				0.39032,
				0.42189,
				0.45346,
				0.4879,
				0.52234,
				0.55678,
				0.59122,
				0.62566,
				0.6601,
			},
		},
		{{ // attack: AncientSwordArt - 5-Hit DMG: {4}
			0.63038,
			0.68169,
			0.733,
			0.8063,
			0.85761,
			0.91625,
			0.99688,
			1.07751,
			1.15814,
			1.2461,
			1.33406,
			1.42202,
			1.50998,
			1.59794,
			1.6859,
		}},
	}
	charge = [][]float64{
		{ // attack: AncientSwordArt - Charged Attack DMG: {5}+{5}
			0.64328,
			0.69564,
			0.748,
			0.8228,
			0.87516,
			0.935,
			1.01728,
			1.09956,
			1.18184,
			1.2716,
			1.36136,
			1.45112,
			1.54088,
			1.63064,
			1.7204,
		},
		{ // attack: AncientSwordArt - Charged Attack DMG: {5}+{5}
			0.64328,
			0.69564,
			0.748,
			0.8228,
			0.87516,
			0.935,
			1.01728,
			1.09956,
			1.18184,
			1.2716,
			1.36136,
			1.45112,
			1.54088,
			1.63064,
			1.7204,
		},
	}
	// attack: AncientSwordArt - Plunge DMG: {7}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: AncientSwordArt - Low/High Plunge DMG: {8}/{9}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: AncientSwordArt - Low/High Plunge DMG: {8}/{9}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: AdeptusArtHeraldOfFrost - Regeneration on Hit: {0} ATK+{1}
	skillHealOnHitPer = []float64{
		0.1056,
		0.11352,
		0.12144,
		0.132,
		0.13992,
		0.14784,
		0.1584,
		0.16896,
		0.17952,
		0.19008,
		0.20064,
		0.2112,
		0.2244,
		0.2376,
		0.2508,
	}
	// skill: AdeptusArtHeraldOfFrost - Regeneration on Hit: {0} ATK+{1}
	skillHealOnHitFlat = []float64{
		67.40786,
		74.14957,
		81.45311,
		89.31845,
		97.74561,
		106.7346,
		116.2854,
		126.3979,
		137.0723,
		148.3085,
		160.1065,
		172.4664,
		185.388,
		198.8714,
		212.9167,
	}
	// skill: AdeptusArtHeraldOfFrost - Continuous Regeneration: {2} ATK+{3}
	skillHealContPer = []float64{
		0.696,
		0.7482,
		0.8004,
		0.87,
		0.9222,
		0.9744,
		1.044,
		1.1136,
		1.1832,
		1.2528,
		1.3224,
		1.392,
		1.479,
		1.566,
		1.653,
	}
	// skill: AdeptusArtHeraldOfFrost - Continuous Regeneration: {2} ATK+{3}
	skillHealContFlat = []float64{
		450.5507,
		495.612,
		544.4285,
		597.0,
		653.3267,
		713.4085,
		777.2453,
		844.8373,
		916.1845,
		991.2866,
		1070.144,
		1152.756,
		1239.124,
		1329.247,
		1423.124,
	}
	// skill: AdeptusArtHeraldOfFrost - Herald of Frost DMG: {4}
	skillDmgCont = []float64{
		0.36,
		0.387,
		0.414,
		0.45,
		0.477,
		0.504,
		0.54,
		0.576,
		0.612,
		0.648,
		0.684,
		0.72,
		0.765,
		0.81,
		0.855,
	}
	// skill: AdeptusArtHeraldOfFrost - Herald of Frost Coordinated Attack DMG: {8}
	skillCoord = []float64{
		0.24,
		0.258,
		0.276,
		0.3,
		0.318,
		0.336,
		0.36,
		0.384,
		0.408,
		0.432,
		0.456,
		0.48,
		0.51,
		0.54,
		0.57,
	}
	// skill: AdeptusArtHeraldOfFrost - Skill DMG: {7}
	skillInitialDmg = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
	// burst: AdeptusArtPreserverOfFortune - Healing: {0} ATK+{1}
	burstHealPer = []float64{
		0.9,
		0.9675,
		1.035,
		1.125,
		1.1925,
		1.26,
		1.35,
		1.44,
		1.53,
		1.62,
		1.71,
		1.8,
		1.9125,
		2.025,
		2.1375,
	}
	// burst: AdeptusArtPreserverOfFortune - Healing: {0} ATK+{1}
	burstHealFlat = []float64{
		577.3388,
		635.0807,
		697.6345,
		765.0,
		837.1774,
		914.1666,
		995.9677,
		1082.58,
		1174.005,
		1270.242,
		1371.29,
		1477.15,
		1587.822,
		1703.306,
		1823.602,
	}
	// burst: AdeptusArtPreserverOfFortune - Skill DMG: {2}
	burstDmg = []float64{
		2.848,
		3.0616,
		3.2752,
		3.56,
		3.7736,
		3.9872,
		4.272,
		4.5568,
		4.8416,
		5.1264,
		5.4112,
		5.696,
		6.052,
		6.408,
		6.764,
	}
	// burst: AdeptusArtPreserverOfFortune - Stellar-Conduct DMG: {6}
	burstSSC = []float64{
		2.97334,
		3.19634,
		3.41934,
		3.71667,
		3.93967,
		4.16267,
		4.46,
		4.75734,
		5.05467,
		5.35201,
		5.64934,
		5.94667,
		6.31834,
		6.69001,
		7.06167,
	}
)
