// Code generated by "pipeline"; DO NOT EDIT.

package thoma

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Thoma, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Thoma, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: SwiftshatterSpear - 1-Hit DMG: {0}
			0.44393,
			0.48007,
			0.5162,
			0.56782,
			0.60395,
			0.64525,
			0.70203,
			0.75881,
			0.8156,
			0.87754,
			0.93948,
			1.00143,
			1.06337,
			1.12532,
			1.18726,
		}},
		{{ // attack: SwiftshatterSpear - 2-Hit DMG: {1}
			0.43628,
			0.47179,
			0.5073,
			0.55803,
			0.59354,
			0.63412,
			0.68993,
			0.74573,
			0.80153,
			0.86241,
			0.92329,
			0.98416,
			1.04504,
			1.10591,
			1.16679,
		}},
		{
			{ // attack: SwiftshatterSpear - 3-Hit DMG: {2}×2
				0.26789,
				0.28969,
				0.3115,
				0.34265,
				0.36446,
				0.38938,
				0.42364,
				0.4579,
				0.49217,
				0.52955,
				0.56693,
				0.60431,
				0.64169,
				0.67907,
				0.71645,
			},
			{ // attack: SwiftshatterSpear - 3-Hit DMG: {2}×2
				0.26789,
				0.28969,
				0.3115,
				0.34265,
				0.36446,
				0.38938,
				0.42364,
				0.4579,
				0.49217,
				0.52955,
				0.56693,
				0.60431,
				0.64169,
				0.67907,
				0.71645,
			},
		},
		{{ // attack: SwiftshatterSpear - 4-Hit DMG: {3}
			0.67355,
			0.72838,
			0.7832,
			0.86152,
			0.91634,
			0.979,
			1.06515,
			1.1513,
			1.23746,
			1.33144,
			1.42542,
			1.51941,
			1.61339,
			1.70738,
			1.80136,
		}},
	}
	// attack: SwiftshatterSpear - Charged Attack DMG: {4}
	charged = []float64{
		1.12746,
		1.21923,
		1.311,
		1.4421,
		1.53387,
		1.63875,
		1.78296,
		1.92717,
		2.07138,
		2.2287,
		2.38602,
		2.54334,
		2.70066,
		2.85798,
		3.0153,
	}
	// skill: BlazingBlessing - Skill DMG: {0}
	skill = []float64{
		1.464,
		1.5738,
		1.6836,
		1.83,
		1.9398,
		2.0496,
		2.196,
		2.3424,
		2.4888,
		2.6352,
		2.7816,
		2.928,
		3.111,
		3.294,
		3.477,
	}
	// skill: BlazingBlessing - Shield DMG Absorption: {1} Max HP+{2}
	shieldpp = []float64{
		0.072,
		0.0774,
		0.0828,
		0.09,
		0.0954,
		0.1008,
		0.108,
		0.1152,
		0.1224,
		0.1296,
		0.1368,
		0.144,
		0.153,
		0.162,
		0.171,
	}
	// skill: BlazingBlessing - Shield DMG Absorption: {1} Max HP+{2}
	shieldflat = []float64{
		693.3348,
		762.678,
		837.7997,
		918.7,
		1005.379,
		1097.836,
		1196.073,
		1300.087,
		1409.88,
		1525.452,
		1646.803,
		1773.932,
		1906.839,
		2045.526,
		2189.99,
	}
	// skill: BlazingBlessing - Max Shield DMG Absorption: {4} Max HP+{5}
	shieldppmax = []float64{
		0.196,
		0.2107,
		0.2254,
		0.245,
		0.2597,
		0.2744,
		0.294,
		0.3136,
		0.3332,
		0.3528,
		0.3724,
		0.392,
		0.4165,
		0.441,
		0.4655,
	}
	// skill: BlazingBlessing - Max Shield DMG Absorption: {4} Max HP+{5}
	shieldflatmax = []float64{
		1887.42,
		2076.188,
		2280.687,
		2500.917,
		2736.877,
		2988.568,
		3255.99,
		3539.142,
		3838.025,
		4152.639,
		4482.983,
		4829.058,
		5190.864,
		5568.4,
		5961.667,
	}
	// burst: CrimsonOoyoroi - Skill DMG: {0}
	burst = []float64{
		0.88,
		0.946,
		1.012,
		1.1,
		1.166,
		1.232,
		1.32,
		1.408,
		1.496,
		1.584,
		1.672,
		1.76,
		1.87,
		1.98,
		2.09,
	}
	// burst: CrimsonOoyoroi - Fiery Collapse DMG: {1}
	burstproc = []float64{
		0.58,
		0.6235,
		0.667,
		0.725,
		0.7685,
		0.812,
		0.87,
		0.928,
		0.986,
		1.044,
		1.102,
		1.16,
		1.2325,
		1.305,
		1.3775,
	}
	// burst: CrimsonOoyoroi - Shield DMG Absorption: {2} Max HP+{3}
	burstshieldpp = []float64{
		0.01144,
		0.0123,
		0.01316,
		0.0143,
		0.01516,
		0.01602,
		0.01716,
		0.0183,
		0.01945,
		0.02059,
		0.02174,
		0.02288,
		0.02431,
		0.02574,
		0.02717,
	}
	// burst: CrimsonOoyoroi - Shield DMG Absorption: {2} Max HP+{3}
	burstshieldflat = []float64{
		110.034,
		121.0389,
		132.9609,
		145.8,
		159.5562,
		174.2294,
		189.8197,
		206.3271,
		223.7516,
		242.0931,
		261.3518,
		281.5274,
		302.6202,
		324.6301,
		347.557,
	}
)
