// Code generated by "pipeline"; DO NOT EDIT.

package faruzan

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Faruzan, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionAim:    {"hold", "travel", "weakspot"},
	}
	validation.RegisterCharParamValidationFunc(keys.Faruzan, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: ParthianShot - 1-Hit DMG: {0}
			0.4473,
			0.4837,
			0.52011,
			0.57212,
			0.60853,
			0.65014,
			0.70735,
			0.76456,
			0.82177,
			0.88419,
			0.9466,
			1.00901,
			1.07143,
			1.13384,
			1.19625,
		},
		{ // attack: ParthianShot - 2-Hit DMG: {1}
			0.42186,
			0.4562,
			0.49054,
			0.53959,
			0.57393,
			0.61317,
			0.66713,
			0.72109,
			0.77505,
			0.83392,
			0.89278,
			0.95165,
			1.01051,
			1.06938,
			1.12824,
		},
		{ // attack: ParthianShot - 3-Hit DMG: {2}
			0.53163,
			0.57491,
			0.61818,
			0.68,
			0.72327,
			0.77272,
			0.84073,
			0.90873,
			0.97672,
			1.05091,
			1.12509,
			1.19927,
			1.27345,
			1.34763,
			1.42181,
		},
		{ // attack: ParthianShot - 4-Hit DMG: {3}
			0.70621,
			0.76369,
			0.82117,
			0.90329,
			0.96077,
			1.02646,
			1.11679,
			1.20712,
			1.29745,
			1.39599,
			1.49453,
			1.59307,
			1.69161,
			1.79015,
			1.88869,
		},
	}
	// attack: ParthianShot - Aimed Shot: {4}
	aim = []float64{
		0.4386,
		0.4743,
		0.51,
		0.561,
		0.5967,
		0.6375,
		0.6936,
		0.7497,
		0.8058,
		0.867,
		0.9282,
		0.9894,
		1.0506,
		1.1118,
		1.173,
	}
	// attack: ParthianShot - Fully-Charged Aimed Shot: {5}
	fullaim = []float64{
		1.24,
		1.333,
		1.426,
		1.55,
		1.643,
		1.736,
		1.86,
		1.984,
		2.108,
		2.232,
		2.356,
		2.48,
		2.635,
		2.79,
		2.945,
	}
	// skill: WindRealmOfNasamjnin - Skill DMG: {0}
	skill = []float64{
		1.488,
		1.5996,
		1.7112,
		1.86,
		1.9716,
		2.0832,
		2.232,
		2.3808,
		2.5296,
		2.6784,
		2.8272,
		2.976,
		3.162,
		3.348,
		3.534,
	}
	// skill: WindRealmOfNasamjnin - Pressurized Collapse Vortex DMG: {1}
	vortexDmg = []float64{
		1.08,
		1.161,
		1.242,
		1.35,
		1.431,
		1.512,
		1.62,
		1.728,
		1.836,
		1.944,
		2.052,
		2.16,
		2.295,
		2.43,
		2.565,
	}
	// burst: TheWindsSecretWays - Skill DMG: {0}
	burst = []float64{
		3.776,
		4.0592,
		4.3424,
		4.72,
		5.0032,
		5.2864,
		5.664,
		6.0416,
		6.4192,
		6.7968,
		7.1744,
		7.552,
		8.024,
		8.496,
		8.968,
	}
	// burst: TheWindsSecretWays - Anemo DMG Bonus: {1}
	burstBuff = []float64{
		0.18,
		0.1935,
		0.207,
		0.225,
		0.2385,
		0.252,
		0.27,
		0.288,
		0.306,
		0.324,
		0.342,
		0.36,
		0.3825,
		0.405,
		0.4275,
	}
)
