// Code generated by "pipeline"; DO NOT EDIT.

package kokomi

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.SangonomiyaKokomi, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.SangonomiyaKokomi, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: TheShapeOfWater - 1-Hit DMG: {0}
			0.68376,
			0.73504,
			0.78632,
			0.8547,
			0.90598,
			0.95726,
			1.02564,
			1.09402,
			1.16239,
			1.23077,
			1.29914,
			1.36752,
			1.45299,
			1.53846,
			1.62393,
		},
		{ // attack: TheShapeOfWater - 2-Hit DMG: {1}
			0.61538,
			0.66154,
			0.70769,
			0.76923,
			0.81538,
			0.86154,
			0.92308,
			0.98461,
			1.04615,
			1.10769,
			1.16923,
			1.23077,
			1.30769,
			1.38461,
			1.46154,
		},
		{ // attack: TheShapeOfWater - 3-Hit DMG: {2}
			0.94306,
			1.01379,
			1.08451,
			1.17882,
			1.24955,
			1.32028,
			1.41458,
			1.50889,
			1.60319,
			1.6975,
			1.79181,
			1.88611,
			2.00399,
			2.12188,
			2.23976,
		},
	}
	// attack: TheShapeOfWater - Charged Attack DMG: {3}
	charge = []float64{
		1.4832,
		1.59444,
		1.70568,
		1.854,
		1.96524,
		2.07648,
		2.2248,
		2.37312,
		2.52144,
		2.66976,
		2.81808,
		2.9664,
		3.1518,
		3.3372,
		3.5226,
	}
	// skill: KuragesOath - Regeneration: {0} Max HP+{1}
	skillHealPct = []float64{
		0.044,
		0.0473,
		0.0506,
		0.055,
		0.0583,
		0.0616,
		0.066,
		0.0704,
		0.0748,
		0.0792,
		0.0836,
		0.088,
		0.0935,
		0.099,
		0.1045,
	}
	// skill: KuragesOath - Regeneration: {0} Max HP+{1}
	skillHealFlat = []float64{
		423.7063,
		466.0828,
		511.9907,
		561.43,
		614.4006,
		670.9027,
		730.9361,
		794.5009,
		861.5971,
		932.2246,
		1006.383,
		1084.074,
		1165.295,
		1250.048,
		1338.333,
	}
	// skill: KuragesOath - Ripple DMG: {2}
	skillDmg = []float64{
		1.0919,
		1.1738,
		1.25569,
		1.36488,
		1.44677,
		1.52867,
		1.63786,
		1.74705,
		1.85624,
		1.96543,
		2.07462,
		2.18381,
		2.3203,
		2.45678,
		2.59327,
	}
	// burst: NereidsAscension - Skill DMG: {0} Max HP
	burstDmg = []float64{
		0.10416,
		0.11197,
		0.11978,
		0.1302,
		0.13801,
		0.14582,
		0.15624,
		0.16666,
		0.17707,
		0.18749,
		0.1979,
		0.20832,
		0.22134,
		0.23436,
		0.24738,
	}
	// burst: NereidsAscension - HP Regeneration Per Hit: {1} Max HP+{2}
	burstHealPct = []float64{
		0.00808,
		0.00869,
		0.00929,
		0.0101,
		0.01071,
		0.01131,
		0.01212,
		0.01293,
		0.01374,
		0.01454,
		0.01535,
		0.01616,
		0.01717,
		0.01818,
		0.01919,
	}
	// burst: NereidsAscension - HP Regeneration Per Hit: {1} Max HP+{2}
	burstHealFlat = []float64{
		77.03738,
		84.74218,
		93.08906,
		102.078,
		111.709,
		121.9821,
		132.8972,
		144.4545,
		156.6537,
		169.4951,
		182.9785,
		197.104,
		211.8715,
		227.2811,
		243.3328,
	}
	// burst: NereidsAscension - Normal Attack DMG Bonus: {3} Max HP
	burstBonusNormal = []float64{
		0.0484,
		0.05203,
		0.05566,
		0.0605,
		0.06413,
		0.06776,
		0.0726,
		0.07744,
		0.08228,
		0.08712,
		0.09196,
		0.0968,
		0.10285,
		0.1089,
		0.11495,
	}
	// burst: NereidsAscension - Charged Attack DMG Bonus: {4} Max HP
	burstBonusCharge = []float64{
		0.06776,
		0.07284,
		0.07792,
		0.0847,
		0.08978,
		0.09486,
		0.10164,
		0.10842,
		0.11519,
		0.12197,
		0.12874,
		0.13552,
		0.14399,
		0.15246,
		0.16093,
	}
	// burst: NereidsAscension - Bake-Kurage DMG Bonus: {8} Max HP
	burstBonusSkill = []float64{
		0.07096,
		0.07628,
		0.08161,
		0.0887,
		0.09403,
		0.09935,
		0.10644,
		0.11354,
		0.12064,
		0.12773,
		0.13483,
		0.14193,
		0.1508,
		0.15967,
		0.16854,
	}
)
