// Code generated by "pipeline"; DO NOT EDIT.

package baizhu

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Baizhu, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Baizhu, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: TheClassicsOfAcupuncture - 1-Hit DMG: {0}
			0.3737,
			0.40173,
			0.42976,
			0.46713,
			0.49516,
			0.52319,
			0.56056,
			0.59793,
			0.6353,
			0.67267,
			0.71004,
			0.74741,
			0.79412,
			0.84083,
			0.88755,
		}},
		{{ // attack: TheClassicsOfAcupuncture - 2-Hit DMG: {1}
			0.36425,
			0.39157,
			0.41888,
			0.45531,
			0.48263,
			0.50995,
			0.54637,
			0.5828,
			0.61922,
			0.65565,
			0.69207,
			0.7285,
			0.77403,
			0.81956,
			0.86509,
		}},
		{
			{ // attack: TheClassicsOfAcupuncture - 3-Hit DMG: {2}×2
				0.22542,
				0.24232,
				0.25923,
				0.28177,
				0.29868,
				0.31558,
				0.33812,
				0.36067,
				0.38321,
				0.40575,
				0.42829,
				0.45083,
				0.47901,
				0.50719,
				0.53536,
			},
			{ // attack: TheClassicsOfAcupuncture - 3-Hit DMG: {2}×2
				0.22542,
				0.24232,
				0.25923,
				0.28177,
				0.29868,
				0.31558,
				0.33812,
				0.36067,
				0.38321,
				0.40575,
				0.42829,
				0.45083,
				0.47901,
				0.50719,
				0.53536,
			},
		},
		{{ // attack: TheClassicsOfAcupuncture - 4-Hit DMG: {3}
			0.54138,
			0.58198,
			0.62258,
			0.67672,
			0.71732,
			0.75793,
			0.81206,
			0.8662,
			0.92034,
			0.97448,
			1.02861,
			1.08275,
			1.15042,
			1.2181,
			1.28577,
		}},
	}
	// attack: TheClassicsOfAcupuncture - Charged Attack DMG: {4}
	charge = []float64{
		1.2104,
		1.30118,
		1.39196,
		1.513,
		1.60378,
		1.69456,
		1.8156,
		1.93664,
		2.05768,
		2.17872,
		2.29976,
		2.4208,
		2.5721,
		2.7234,
		2.8747,
	}
	// skill: UniversalDiagnosis - Skill DMG: {0}
	skillDamage = []float64{
		0.792,
		0.8514,
		0.9108,
		0.99,
		1.0494,
		1.1088,
		1.188,
		1.2672,
		1.3464,
		1.4256,
		1.5048,
		1.584,
		1.683,
		1.782,
		1.881,
	}
	// skill: UniversalDiagnosis - Healing: {1} Max HP+{2}
	skillHealPP = []float64{
		0.08,
		0.086,
		0.092,
		0.1,
		0.106,
		0.112,
		0.12,
		0.128,
		0.136,
		0.144,
		0.152,
		0.16,
		0.17,
		0.18,
		0.19,
	}
	// skill: UniversalDiagnosis - Healing: {1} Max HP+{2}
	skillHealFlat = []float64{
		770.3755,
		847.4238,
		930.8927,
		1020.782,
		1117.093,
		1219.824,
		1328.975,
		1444.548,
		1566.541,
		1694.955,
		1829.789,
		1971.044,
		2118.72,
		2272.816,
		2433.334,
	}
	// burst: HolisticRevivification - Seamless Shield DMG Absorption: {0} Max HP+{1}
	burstShieldPP = []float64{
		0.008,
		0.0086,
		0.0092,
		0.01,
		0.0106,
		0.0112,
		0.012,
		0.0128,
		0.0136,
		0.0144,
		0.0152,
		0.016,
		0.017,
		0.018,
		0.019,
	}
	// burst: HolisticRevivification - Seamless Shield DMG Absorption: {0} Max HP+{1}
	burstShieldFlat = []float64{
		77.03752,
		84.74235,
		93.08924,
		102.0782,
		111.7092,
		121.9823,
		132.8975,
		144.4547,
		156.654,
		169.4954,
		182.9789,
		197.1044,
		211.8719,
		227.2816,
		243.3333,
	}
	// burst: HolisticRevivification - Seamless Shield Healing: {4} Max HP+{5}
	burstHealPP = []float64{
		0.052,
		0.0559,
		0.0598,
		0.065,
		0.0689,
		0.0728,
		0.078,
		0.0832,
		0.0884,
		0.0936,
		0.0988,
		0.104,
		0.1105,
		0.117,
		0.1235,
	}
	// burst: HolisticRevivification - Seamless Shield Healing: {4} Max HP+{5}
	burstHealFlat = []float64{
		500.7441,
		550.8254,
		605.0803,
		663.5085,
		726.1102,
		792.8854,
		863.834,
		938.9561,
		1018.252,
		1101.72,
		1189.363,
		1281.179,
		1377.168,
		1477.331,
		1581.667,
	}
	// burst: HolisticRevivification - Spiritvein DMG: {6}
	burstAtk = []float64{
		0.97064,
		1.04344,
		1.11624,
		1.2133,
		1.2861,
		1.3589,
		1.45596,
		1.55302,
		1.65009,
		1.74715,
		1.84422,
		1.94128,
		2.06261,
		2.18394,
		2.30527,
	}
)
