// Code generated by "pipeline"; DO NOT EDIT.

package lohen

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Lohen, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Lohen, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: SpearOfFavoniusBrokenOath - 1-Hit DMG: {0}
			0.53992,
			0.58386,
			0.62781,
			0.69059,
			0.73454,
			0.78476,
			0.85382,
			0.92288,
			0.99194,
			1.06728,
			1.14261,
			1.21795,
			1.29329,
			1.36863,
			1.44396,
		}},
		{{ // attack: SpearOfFavoniusBrokenOath - 2-Hit DMG: {1}
			0.56443,
			0.61037,
			0.65631,
			0.72194,
			0.76788,
			0.82039,
			0.89258,
			0.96478,
			1.03697,
			1.11573,
			1.19448,
			1.27324,
			1.352,
			1.43076,
			1.50951,
		}},
		{{ // attack: SpearOfFavoniusBrokenOath - 3-Hit DMG: {2}×3
			0.2542,
			0.27489,
			0.29558,
			0.32514,
			0.34583,
			0.36948,
			0.40199,
			0.4345,
			0.46702,
			0.50249,
			0.53796,
			0.57342,
			0.6089,
			0.64436,
			0.67983,
		}},
		{{ // attack: SpearOfFavoniusBrokenOath - 4-Hit DMG: {3}
			0.75226,
			0.81349,
			0.87472,
			0.96219,
			1.02342,
			1.0934,
			1.18962,
			1.28584,
			1.38206,
			1.48702,
			1.59199,
			1.69696,
			1.80192,
			1.90689,
			2.01186,
		}},
		{
			{ // attack: SpearOfFavoniusBrokenOath - 5-Hit DMG: {4}+{5}
				0.36858,
				0.39858,
				0.42858,
				0.47144,
				0.50144,
				0.53572,
				0.58287,
				0.63001,
				0.67716,
				0.72859,
				0.78002,
				0.83144,
				0.88288,
				0.9343,
				0.98573,
			},
			{ // attack: SpearOfFavoniusBrokenOath - 5-Hit DMG: {4}+{5}
				0.55287,
				0.59787,
				0.64287,
				0.70716,
				0.75216,
				0.80359,
				0.8743,
				0.94502,
				1.01574,
				1.09288,
				1.17002,
				1.24717,
				1.32431,
				1.40146,
				1.4786,
			},
		},
	}
	// attack: SpearOfFavoniusBrokenOath - Charged Attack DMG: {6}×2
	charge = []float64{
		0.65876,
		0.71238,
		0.766,
		0.8426,
		0.89622,
		0.9575,
		1.04176,
		1.12602,
		1.21028,
		1.3022,
		1.39412,
		1.48604,
		1.57796,
		1.66988,
		1.7618,
	}
	skillAttack = [][][]float64{
		{{ // skill: UnforeseenStrike - 1-Hit DMG: {0}
			0.80988,
			0.8758,
			0.94172,
			1.03589,
			1.10181,
			1.17714,
			1.28073,
			1.38432,
			1.48791,
			1.60091,
			1.71392,
			1.82693,
			1.93993,
			2.05294,
			2.16594,
		}},
		{{ // skill: UnforeseenStrike - 2-Hit DMG: {1}
			0.84664,
			0.91555,
			0.98447,
			1.08291,
			1.15182,
			1.23058,
			1.33887,
			1.44716,
			1.55545,
			1.67359,
			1.79173,
			1.90986,
			2.028,
			2.14613,
			2.26427,
		}},
		{{ // skill: UnforeseenStrike - 3-Hit DMG: {2}×3
			0.3813,
			0.41233,
			0.44337,
			0.48771,
			0.51874,
			0.55421,
			0.60298,
			0.65175,
			0.70052,
			0.75373,
			0.80693,
			0.86014,
			0.91334,
			0.96655,
			1.01975,
		}},
		{{ // skill: UnforeseenStrike - 4-Hit DMG: {3}
			1.12839,
			1.22023,
			1.31208,
			1.44329,
			1.53513,
			1.6401,
			1.78443,
			1.92876,
			2.07309,
			2.23054,
			2.38799,
			2.54543,
			2.70288,
			2.86033,
			3.01778,
		}},
		{
			{ // skill: UnforeseenStrike - 5-Hit DMG: {4}+{5}
				0.55287,
				0.59787,
				0.64287,
				0.70716,
				0.75216,
				0.80359,
				0.8743,
				0.94502,
				1.01574,
				1.09288,
				1.17002,
				1.24717,
				1.32431,
				1.40146,
				1.4786,
			},
			{ // skill: UnforeseenStrike - 5-Hit DMG: {4}+{5}
				0.8293,
				0.8968,
				0.9643,
				1.06074,
				1.12824,
				1.20538,
				1.31146,
				1.41753,
				1.5236,
				1.63932,
				1.75504,
				1.87075,
				1.98647,
				2.10219,
				2.2179,
			},
		},
	}
	// skill: UnforeseenStrike - Charged Attack DMG: {6}×2
	skillCharge = []float64{
		0.98814,
		1.06857,
		1.149,
		1.2639,
		1.34433,
		1.43625,
		1.56264,
		1.68903,
		1.81542,
		1.9533,
		2.09118,
		2.22906,
		2.36694,
		2.50482,
		2.6427,
	}
	// skill: UnforeseenStrike - Etched Into Bone and Soul DMG: {16}×4
	skillPierce = []float64{
		0.6,
		0.645,
		0.69,
		0.75,
		0.795,
		0.84,
		0.9,
		0.96,
		1.02,
		1.08,
		1.14,
		1.2,
		1.275,
		1.35,
		1.425,
	}
	// burst: ManifestJudgment - Skill DMG: {0}×6
	burst = []float64{
		1.188,
		1.2771,
		1.3662,
		1.485,
		1.5741,
		1.6632,
		1.782,
		1.9008,
		2.0196,
		2.1384,
		2.2572,
		2.376,
		2.5245,
		2.673,
		2.8215,
	}
)
