// Code generated by "pipeline"; DO NOT EDIT.

package layla

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Layla, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionBurst: {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Layla, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][]float64{
		{ // attack: SwordOfTheRadiantPath - 1-Hit DMG: {0}
			0.51217,
			0.55386,
			0.59555,
			0.6551,
			0.69679,
			0.74444,
			0.80995,
			0.87546,
			0.94097,
			1.01243,
			1.0839,
			1.15537,
			1.22683,
			1.2983,
			1.36977,
		},
		{ // attack: SwordOfTheRadiantPath - 2-Hit DMG: {1}
			0.48483,
			0.5243,
			0.56376,
			0.62014,
			0.6596,
			0.7047,
			0.76671,
			0.82873,
			0.89074,
			0.95839,
			1.02604,
			1.09369,
			1.16135,
			1.229,
			1.29665,
		},
		{ // attack: SwordOfTheRadiantPath - 3-Hit DMG: {2}
			0.72974,
			0.78913,
			0.84853,
			0.93338,
			0.99278,
			1.06066,
			1.154,
			1.24734,
			1.34068,
			1.4425,
			1.54432,
			1.64615,
			1.74797,
			1.84979,
			1.95162,
		},
	}
	charge = [][]float64{
		{ // attack: SwordOfTheRadiantPath - Charged Attack DMG: {3}+{4}
			0.4773,
			0.51615,
			0.555,
			0.6105,
			0.64935,
			0.69375,
			0.7548,
			0.81585,
			0.8769,
			0.9435,
			1.0101,
			1.0767,
			1.1433,
			1.2099,
			1.2765,
		},
		{ // attack: SwordOfTheRadiantPath - Charged Attack DMG: {3}+{4}
			0.52546,
			0.56823,
			0.611,
			0.6721,
			0.71487,
			0.76375,
			0.83096,
			0.89817,
			0.96538,
			1.0387,
			1.11202,
			1.18534,
			1.25866,
			1.33198,
			1.4053,
		},
	}
	// skill: NightsOfFormalFocus - Skill DMG: {0}
	skill = []float64{
		0.128,
		0.1376,
		0.1472,
		0.16,
		0.1696,
		0.1792,
		0.192,
		0.2048,
		0.2176,
		0.2304,
		0.2432,
		0.256,
		0.272,
		0.288,
		0.304,
	}
	// skill: NightsOfFormalFocus - Shooting Star DMG: {1}
	starDmg = []float64{
		0.1472,
		0.15824,
		0.16928,
		0.184,
		0.19504,
		0.20608,
		0.2208,
		0.23552,
		0.25024,
		0.26496,
		0.27968,
		0.2944,
		0.3128,
		0.3312,
		0.3496,
	}
	// skill: NightsOfFormalFocus - Base Shield DMG Absorption: {2} Max HP+{3}
	shieldPer = []float64{
		0.108,
		0.1161,
		0.1242,
		0.135,
		0.1431,
		0.1512,
		0.162,
		0.1728,
		0.1836,
		0.1944,
		0.2052,
		0.216,
		0.2295,
		0.243,
		0.2565,
	}
	// skill: NightsOfFormalFocus - Base Shield DMG Absorption: {2} Max HP+{3}
	shieldBase = []float64{
		1040.007,
		1144.022,
		1256.705,
		1378.056,
		1508.075,
		1646.762,
		1794.117,
		1950.139,
		2114.83,
		2288.189,
		2470.215,
		2660.91,
		2860.272,
		3068.302,
		3285.0,
	}
	// burst: DreamOfTheStarStreamShaker - Starlight Slug DMG: {0} Max HP
	burst = []float64{
		0.04649,
		0.04998,
		0.05346,
		0.05811,
		0.0616,
		0.06508,
		0.06973,
		0.07438,
		0.07903,
		0.08368,
		0.08833,
		0.09298,
		0.09879,
		0.1046,
		0.11041,
	}
)
