// Code generated by "pipeline"; DO NOT EDIT.

package odette

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Odette, NewChar)
	paramsFor := map[action.Action][]string{}
	validation.RegisterCharParamValidationFunc(keys.Odette, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: SnowSwanVariation - 1-Hit DMG: {0}
			0.51857,
			0.56078,
			0.60299,
			0.66329,
			0.7055,
			0.75374,
			0.82007,
			0.88639,
			0.95272,
			1.02508,
			1.09744,
			1.1698,
			1.24216,
			1.31452,
			1.38688,
		}},
		{{ // attack: SnowSwanVariation - 2-Hit DMG: {1}
			0.51511,
			0.55703,
			0.59896,
			0.65886,
			0.70078,
			0.7487,
			0.81459,
			0.88047,
			0.94636,
			1.01823,
			1.09011,
			1.16198,
			1.23386,
			1.30573,
			1.37761,
		}},
		{
			{ // attack: SnowSwanVariation - 3-Hit DMG: {2}+{3}
				0.32611,
				0.35266,
				0.3792,
				0.41712,
				0.44366,
				0.474,
				0.51571,
				0.55742,
				0.59914,
				0.64464,
				0.69014,
				0.73565,
				0.78115,
				0.82666,
				0.87216,
			},
			{ // attack: SnowSwanVariation - 3-Hit DMG: {2}+{3}
				0.38279,
				0.41394,
				0.4451,
				0.48961,
				0.52077,
				0.55638,
				0.60534,
				0.6543,
				0.70326,
				0.75667,
				0.81008,
				0.86349,
				0.91691,
				0.97032,
				1.02373,
			},
		},
		{{ // attack: SnowSwanVariation - 4-Hit DMG: {4}
			0.74573,
			0.80643,
			0.86713,
			0.95384,
			1.01454,
			1.08391,
			1.1793,
			1.27468,
			1.37006,
			1.47412,
			1.57818,
			1.68223,
			1.78629,
			1.89034,
			1.9944,
		}},
		{{ // attack: SnowSwanVariation - 5-Hit DMG: {5}
			0.90212,
			0.97555,
			1.04898,
			1.15388,
			1.22731,
			1.31123,
			1.42661,
			1.542,
			1.65739,
			1.78327,
			1.90914,
			2.03502,
			2.1609,
			2.28678,
			2.41265,
		}},
	}
	// attack: SnowSwanVariation - Charged Attack DMG: {6}
	charge = []float64{
		1.07414,
		1.16157,
		1.249,
		1.3739,
		1.46133,
		1.56125,
		1.69864,
		1.83603,
		1.97342,
		2.1233,
		2.27318,
		2.42306,
		2.57294,
		2.72282,
		2.8727,
	}
	// attack: SnowSwanVariation - Plunge DMG: {8}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: SnowSwanVariation - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: SnowSwanVariation - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: AdagioPhantomNightDancers - Skill DMG: {0}
	skill = []float64{
		1.0808,
		1.16186,
		1.24292,
		1.351,
		1.43206,
		1.51312,
		1.6212,
		1.72928,
		1.83736,
		1.94544,
		2.05352,
		2.1616,
		2.2967,
		2.4318,
		2.5669,
	}
	// skill: AdagioPhantomNightDancers - Coda at Dawn's Tolling DoT: {1}
	codaDoT = []float64{
		0.9584,
		1.03028,
		1.10216,
		1.198,
		1.26988,
		1.34176,
		1.4376,
		1.53344,
		1.62928,
		1.72512,
		1.82096,
		1.9168,
		2.0366,
		2.1564,
		2.2762,
	}
	// skill: AdagioPhantomNightDancers - Coda at Dawn's Tolling Stellar-Conduct/Stellar Swirl DMG: {2}/{3}
	codaSSC = []float64{
		3.0576,
		3.28692,
		3.51624,
		3.822,
		4.05132,
		4.28064,
		4.5864,
		4.89216,
		5.19792,
		5.50368,
		5.80944,
		6.1152,
		6.4974,
		6.8796,
		7.2618,
	}
	// skill: AdagioPhantomNightDancers - Coda at Dawn's Tolling Stellar-Conduct/Stellar Swirl DMG: {2}/{3}
	codaSSw = []float64{
		4.5864,
		4.93038,
		5.27436,
		5.733,
		6.07698,
		6.42096,
		6.8796,
		7.33824,
		7.79688,
		8.25552,
		8.71416,
		9.1728,
		9.7461,
		10.3194,
		10.8927,
	}
	// skill: AdagioPhantomNightDancers - "Plume" Dance Move DMG: {4}
	plume = []float64{
		0.4304,
		0.46268,
		0.49496,
		0.538,
		0.57028,
		0.60256,
		0.6456,
		0.68864,
		0.73168,
		0.77472,
		0.81776,
		0.8608,
		0.9146,
		0.9684,
		1.0222,
	}
	// skill: AdagioPhantomNightDancers - "Plume" Dance Move Stellar-Conduct/Stellar Swirl DMG: {5}/{6}
	plumeSSC = []float64{
		0.27024,
		0.29051,
		0.31078,
		0.3378,
		0.35807,
		0.37834,
		0.40536,
		0.43238,
		0.45941,
		0.48643,
		0.51346,
		0.54048,
		0.57426,
		0.60804,
		0.64182,
	}
	// skill: AdagioPhantomNightDancers - "Plume" Dance Move Stellar-Conduct/Stellar Swirl DMG: {5}/{6}
	plumeSSw = []float64{
		0.40528,
		0.43568,
		0.46607,
		0.5066,
		0.537,
		0.56739,
		0.60792,
		0.64845,
		0.68898,
		0.7295,
		0.77003,
		0.81056,
		0.86122,
		0.91188,
		0.96254,
	}
	// skill: AdagioPhantomNightDancers - "Wing" Dance Move DMG: {7}
	wing = []float64{
		0.51464,
		0.55324,
		0.59184,
		0.6433,
		0.6819,
		0.7205,
		0.77196,
		0.82342,
		0.87489,
		0.92635,
		0.97782,
		1.02928,
		1.09361,
		1.15794,
		1.22227,
	}
	// skill: AdagioPhantomNightDancers - "Wing" Dance Move Stellar-Conduct/Stellar Swirl DMG: {8}/{9}
	wingSSC = []float64{
		0.32312,
		0.34735,
		0.37159,
		0.4039,
		0.42813,
		0.45237,
		0.48468,
		0.51699,
		0.5493,
		0.58162,
		0.61393,
		0.64624,
		0.68663,
		0.72702,
		0.76741,
	}
	// skill: AdagioPhantomNightDancers - "Wing" Dance Move Stellar-Conduct/Stellar Swirl DMG: {8}/{9}
	wingSSw = []float64{
		0.48464,
		0.52099,
		0.55734,
		0.6058,
		0.64215,
		0.6785,
		0.72696,
		0.77542,
		0.82389,
		0.87235,
		0.92082,
		0.96928,
		1.02986,
		1.09044,
		1.15102,
	}
	// burst: PrestoBluebirdFinale - Slash DMG: {0} ×3
	burst = []float64{
		1.10176,
		1.18439,
		1.26702,
		1.3772,
		1.45983,
		1.54246,
		1.65264,
		1.76282,
		1.87299,
		1.98317,
		2.09334,
		2.20352,
		2.34124,
		2.47896,
		2.61668,
	}
	// burst: PrestoBluebirdFinale - Final Slash DMG: {1}
	burstFinal = []float64{
		1.70272,
		1.83042,
		1.95813,
		2.1284,
		2.2561,
		2.38381,
		2.55408,
		2.72435,
		2.89462,
		3.0649,
		3.23517,
		3.40544,
		3.61828,
		3.83112,
		4.04396,
	}
	// burst: PrestoBluebirdFinale - Snow Swan's Dream Stellar Glimmer Reaction DMG Bonus: {2}
	burstBuff = []float64{
		0.14,
		0.18,
		0.22,
		0.26,
		0.3,
		0.34,
		0.38,
		0.42,
		0.46,
		0.5,
		0.54,
		0.58,
		0.62,
		0.66,
		0.7,
	}
)
