// Code generated by "pipeline"; DO NOT EDIT.

package xianyun

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Xianyun, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack:     {"travel"},
		action.ActionCharge:     {"travel"},
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Xianyun, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: WordOfWindAndFlower - 1-Hit DMG: {0}
			0.40302,
			0.43325,
			0.46348,
			0.50378,
			0.53401,
			0.56423,
			0.60454,
			0.64484,
			0.68514,
			0.72544,
			0.76575,
			0.80605,
			0.85643,
			0.9068,
			0.95718,
		},
		{ // attack: WordOfWindAndFlower - 2-Hit DMG: {1}
			0.38855,
			0.41769,
			0.44684,
			0.48569,
			0.51483,
			0.54397,
			0.58283,
			0.62168,
			0.66054,
			0.69939,
			0.73825,
			0.7771,
			0.82567,
			0.87424,
			0.92281,
		},
		{ // attack: WordOfWindAndFlower - 3-Hit DMG: {2}
			0.48878,
			0.52543,
			0.56209,
			0.61097,
			0.64763,
			0.68429,
			0.73316,
			0.78204,
			0.83092,
			0.8798,
			0.92867,
			0.97755,
			1.03865,
			1.09975,
			1.16084,
		},
		{ // attack: WordOfWindAndFlower - 4-Hit DMG: {3}
			0.64917,
			0.69786,
			0.74654,
			0.81146,
			0.86015,
			0.90883,
			0.97375,
			1.03867,
			1.10359,
			1.1685,
			1.23342,
			1.29834,
			1.37948,
			1.46063,
			1.54177,
		},
	}
	// attack: WordOfWindAndFlower - Charged Attack DMG: {4}
	charged = []float64{
		1.2312,
		1.32354,
		1.41588,
		1.539,
		1.63134,
		1.72368,
		1.8468,
		1.96992,
		2.09304,
		2.21616,
		2.33928,
		2.4624,
		2.6163,
		2.7702,
		2.9241,
	}
	// attack: WordOfWindAndFlower - Plunge DMG: {6}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: WordOfWindAndFlower - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: WordOfWindAndFlower - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: WhiteCloudsAtDawn - Skill DMG: {0}
	skillPress = []float64{
		0.248,
		0.2666,
		0.2852,
		0.31,
		0.3286,
		0.3472,
		0.372,
		0.3968,
		0.4216,
		0.4464,
		0.4712,
		0.496,
		0.527,
		0.558,
		0.589,
	}
	leap = [][]float64{
		{ // skill: WhiteCloudsAtDawn - Driftcloud Wave DMG: {1}/{2}/{3}
			1.16,
			1.247,
			1.334,
			1.45,
			1.537,
			1.624,
			1.74,
			1.856,
			1.972,
			2.088,
			2.204,
			2.32,
			2.465,
			2.61,
			2.755,
		},
		{ // skill: WhiteCloudsAtDawn - Driftcloud Wave DMG: {1}/{2}/{3}
			1.48,
			1.591,
			1.702,
			1.85,
			1.961,
			2.072,
			2.22,
			2.368,
			2.516,
			2.664,
			2.812,
			2.96,
			3.145,
			3.33,
			3.515,
		},
		{ // skill: WhiteCloudsAtDawn - Driftcloud Wave DMG: {1}/{2}/{3}
			3.376,
			3.6292,
			3.8824,
			4.22,
			4.4732,
			4.7264,
			5.064,
			5.4016,
			5.7392,
			6.0768,
			6.4144,
			6.752,
			7.174,
			7.596,
			8.018,
		},
	}
	// burst: StarsGatherAtDusk - Skill DMG: {0}
	burst = []float64{
		1.08,
		1.161,
		1.242,
		1.35,
		1.431,
		1.512,
		1.62,
		1.728,
		1.836,
		1.944,
		2.052,
		2.16,
		2.295,
		2.43,
		2.565,
	}
	// burst: StarsGatherAtDusk - Starwicker DMG: {1}
	burstDot = []float64{
		0.392,
		0.4214,
		0.4508,
		0.49,
		0.5194,
		0.5488,
		0.588,
		0.6272,
		0.6664,
		0.7056,
		0.7448,
		0.784,
		0.833,
		0.882,
		0.931,
	}
	// burst: StarsGatherAtDusk - Healing: {3} ATK+{2}
	healInstantFlat = []float64{
		577.7816,
		635.5678,
		698.1695,
		765.5867,
		837.8195,
		914.8677,
		996.7315,
		1083.411,
		1174.906,
		1271.216,
		1372.342,
		1478.283,
		1589.04,
		1704.612,
		1825.0,
	}
	// burst: StarsGatherAtDusk - Healing: {3} ATK+{2}
	healInstantP = []float64{
		0.9216,
		0.99072,
		1.05984,
		1.152,
		1.22112,
		1.29024,
		1.3824,
		1.47456,
		1.56672,
		1.65888,
		1.75104,
		1.8432,
		1.9584,
		2.0736,
		2.1888,
	}
	// burst: StarsGatherAtDusk - Continuous Healing: {5} ATK+{4}
	healDotFlat = []float64{
		269.6314,
		296.5983,
		325.8124,
		357.2738,
		390.9824,
		426.9383,
		465.1414,
		505.5917,
		548.2893,
		593.2341,
		640.4262,
		689.8655,
		741.552,
		795.4858,
		851.6668,
	}
	// burst: StarsGatherAtDusk - Continuous Healing: {5} ATK+{4}
	healDotP = []float64{
		0.43008,
		0.46234,
		0.49459,
		0.5376,
		0.56986,
		0.60211,
		0.64512,
		0.68813,
		0.73114,
		0.77414,
		0.81715,
		0.86016,
		0.91392,
		0.96768,
		1.02144,
	}
)
