// Code generated by "pipeline"; DO NOT EDIT.

package chevreuse

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Chevreuse, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Chevreuse, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: LineBayonetThrustEX - 1-Hit DMG: {0}
			0.5313,
			0.57455,
			0.61779,
			0.67957,
			0.72281,
			0.77224,
			0.84019,
			0.90815,
			0.97611,
			1.05024,
			1.12438,
			1.19851,
			1.27265,
			1.34678,
			1.42092,
		}},
		{{ // attack: LineBayonetThrustEX - 2-Hit DMG: {1}
			0.49311,
			0.53324,
			0.57338,
			0.63072,
			0.67085,
			0.71672,
			0.7798,
			0.84287,
			0.90594,
			0.97475,
			1.04355,
			1.11236,
			1.18116,
			1.24997,
			1.31877,
		}},
		{
			{ // attack: LineBayonetThrustEX - 3-Hit DMG: {2}+{3}
				0.27645,
				0.29895,
				0.32145,
				0.3536,
				0.3761,
				0.40182,
				0.43718,
				0.47254,
				0.50789,
				0.54647,
				0.58504,
				0.62362,
				0.66219,
				0.70077,
				0.73934,
			},
			{ // attack: LineBayonetThrustEX - 3-Hit DMG: {2}+{3}
				0.32453,
				0.35094,
				0.37736,
				0.41509,
				0.44151,
				0.4717,
				0.51321,
				0.55471,
				0.59623,
				0.64151,
				0.68679,
				0.73207,
				0.77736,
				0.82264,
				0.86792,
			},
		},
		{{ // attack: LineBayonetThrustEX - 4-Hit DMG: {4}
			0.77262,
			0.8355,
			0.89839,
			0.98823,
			1.05112,
			1.12299,
			1.22181,
			1.32063,
			1.41946,
			1.52726,
			1.63507,
			1.74288,
			1.85068,
			1.95849,
			2.0663,
		}},
	}
	// attack: LineBayonetThrustEX - Charged Attack DMG: {5}
	charge = []float64{
		1.2169,
		1.31595,
		1.415,
		1.5565,
		1.65555,
		1.76875,
		1.9244,
		2.08005,
		2.2357,
		2.4055,
		2.5753,
		2.7451,
		2.9149,
		3.0847,
		3.2545,
	}
	// skill: ShortRangeRapidInterdictionFire - Press DMG: {0}
	skillPress = []float64{
		1.152,
		1.2384,
		1.3248,
		1.44,
		1.5264,
		1.6128,
		1.728,
		1.8432,
		1.9584,
		2.0736,
		2.1888,
		2.304,
		2.448,
		2.592,
		2.736,
	}
	// skill: ShortRangeRapidInterdictionFire - Hold DMG: {1}
	skillHold = []float64{
		1.728,
		1.8576,
		1.9872,
		2.16,
		2.2896,
		2.4192,
		2.592,
		2.7648,
		2.9376,
		3.1104,
		3.2832,
		3.456,
		3.672,
		3.888,
		4.104,
	}
	// skill: ShortRangeRapidInterdictionFire - Overcharged Ball DMG: {2}
	skillOvercharged = []float64{
		2.824,
		3.0358,
		3.2476,
		3.53,
		3.7418,
		3.9536,
		4.236,
		4.5184,
		4.8008,
		5.0832,
		5.3656,
		5.648,
		6.001,
		6.354,
		6.707,
	}
	// skill: ShortRangeRapidInterdictionFire - HP Regeneration Over Time: {4} Max HP+{5}
	skillHpRegen = []float64{
		0.02667,
		0.02867,
		0.03067,
		0.03333,
		0.03533,
		0.03733,
		0.04,
		0.04267,
		0.04533,
		0.048,
		0.05067,
		0.05333,
		0.05667,
		0.06,
		0.06333,
	}
	// skill: ShortRangeRapidInterdictionFire - HP Regeneration Over Time: {4} Max HP+{5}
	skillHpFlat = []float64{
		256.7918,
		282.4746,
		310.2976,
		340.2608,
		372.3642,
		406.6079,
		442.9918,
		481.5159,
		522.1803,
		564.9849,
		609.9297,
		657.0147,
		706.24,
		757.6055,
		811.1113,
	}
	// skill: ShortRangeRapidInterdictionFire - Surging Blade DMG: {6}
	arkhe = []float64{
		0.288,
		0.3096,
		0.3312,
		0.36,
		0.3816,
		0.4032,
		0.432,
		0.4608,
		0.4896,
		0.5184,
		0.5472,
		0.576,
		0.612,
		0.648,
		0.684,
	}
	// burst: RingOfBurstingGrenades - Explosive Grenade DMG: {0}
	burst = []float64{
		3.6816,
		3.95772,
		4.23384,
		4.602,
		4.87812,
		5.15424,
		5.5224,
		5.89056,
		6.25872,
		6.62688,
		6.99504,
		7.3632,
		7.8234,
		8.2836,
		8.7438,
	}
	// burst: RingOfBurstingGrenades - Secondary Explosive Shell DMG: {1}
	burstSecondary = []float64{
		0.49088,
		0.5277,
		0.56451,
		0.6136,
		0.65042,
		0.68723,
		0.73632,
		0.78541,
		0.8345,
		0.88358,
		0.93267,
		0.98176,
		1.04312,
		1.10448,
		1.16584,
	}
)
