// Code generated by "pipeline"; DO NOT EDIT.

package klee

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Klee, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack:     {"travel"},
		action.ActionCharge:     {"travel"},
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"bounce", "mine", "mine_delay", "release"},
	}
	validation.RegisterCharParamValidationFunc(keys.Klee, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: Kaboom - 1-Hit DMG: {0}
			0.7216,
			0.77572,
			0.82984,
			0.902,
			0.95612,
			1.01024,
			1.0824,
			1.15456,
			1.22672,
			1.29888,
			1.37393,
			1.47206,
			1.5702,
			1.66834,
			1.76648,
		},
		{ // attack: Kaboom - 2-Hit DMG: {1}
			0.624,
			0.6708,
			0.7176,
			0.78,
			0.8268,
			0.8736,
			0.936,
			0.9984,
			1.0608,
			1.1232,
			1.1881,
			1.27296,
			1.35782,
			1.44269,
			1.52755,
		},
		{ // attack: Kaboom - 3-Hit DMG: {2}
			0.8992,
			0.96664,
			1.03408,
			1.124,
			1.19144,
			1.25888,
			1.3488,
			1.43872,
			1.52864,
			1.61856,
			1.71208,
			1.83437,
			1.95666,
			2.07895,
			2.20124,
		},
	}
	// attack: Kaboom - Charged Attack DMG: {3}
	charge = []float64{
		1.5736,
		1.69162,
		1.80964,
		1.967,
		2.08502,
		2.20304,
		2.3604,
		2.51776,
		2.67512,
		2.83248,
		2.99613,
		3.21014,
		3.42415,
		3.63816,
		3.85217,
	}
	// attack: Kaboom - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: Kaboom - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: Kaboom - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: JumpyDumpty - Jumpy Dumpty DMG: {0}
	jumpy = []float64{
		0.952,
		1.0234,
		1.0948,
		1.19,
		1.2614,
		1.3328,
		1.428,
		1.5232,
		1.6184,
		1.7136,
		1.8088,
		1.904,
		2.023,
		2.142,
		2.261,
	}
	// skill: JumpyDumpty - Mine DMG: {3}
	mine = []float64{
		0.328,
		0.3526,
		0.3772,
		0.41,
		0.4346,
		0.4592,
		0.492,
		0.5248,
		0.5576,
		0.5904,
		0.6232,
		0.656,
		0.697,
		0.738,
		0.779,
	}
	// burst: SparksNSplash - Sparks 'n' Splash DMG: {0}
	burst = []float64{
		0.4264,
		0.45838,
		0.49036,
		0.533,
		0.56498,
		0.59696,
		0.6396,
		0.68224,
		0.72488,
		0.76752,
		0.81016,
		0.8528,
		0.9061,
		0.9594,
		1.0127,
	}
)
