// Code generated by "pipeline"; DO NOT EDIT.

package itto

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.AratakiItto, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"travel", "ushihit"},
		action.ActionBurst:      {"prestack"},
	}
	validation.RegisterCharParamValidationFunc(keys.AratakiItto, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: FightClubLegend - 1-Hit DMG: {0}
			0.79232,
			0.85681,
			0.9213,
			1.01343,
			1.07792,
			1.15163,
			1.25297,
			1.35431,
			1.45565,
			1.56621,
			1.69289,
			1.84186,
			1.99084,
			2.13981,
			2.30233,
		},
		{ // attack: FightClubLegend - 2-Hit DMG: {1}
			0.76368,
			0.82584,
			0.888,
			0.9768,
			1.03896,
			1.11,
			1.20768,
			1.30536,
			1.40304,
			1.5096,
			1.6317,
			1.77529,
			1.91888,
			2.06247,
			2.21911,
		},
		{ // attack: FightClubLegend - 3-Hit DMG: {2}
			0.91642,
			0.99101,
			1.0656,
			1.17216,
			1.24675,
			1.332,
			1.44922,
			1.56643,
			1.68365,
			1.81152,
			1.95804,
			2.13035,
			2.30265,
			2.47496,
			2.66293,
		},
		{ // attack: FightClubLegend - 4-Hit DMG: {3}
			1.17225,
			1.26766,
			1.36308,
			1.49939,
			1.5948,
			1.70385,
			1.85379,
			2.00373,
			2.15367,
			2.31724,
			2.50466,
			2.72507,
			2.94548,
			3.16589,
			3.40634,
		},
	}
	// attack: FightClubLegend - Saichimonji Slash DMG: {4}
	saichiSlash = []float64{
		0.90472,
		0.97836,
		1.052,
		1.1572,
		1.23084,
		1.315,
		1.43072,
		1.54644,
		1.66216,
		1.7884,
		1.93305,
		2.10316,
		2.27327,
		2.44338,
		2.62895,
	}
	// attack: FightClubLegend - Arataki Kesagiri Combo Slash DMG: {5}
	akCombo = []float64{
		0.9116,
		0.9858,
		1.06,
		1.166,
		1.2402,
		1.325,
		1.4416,
		1.5582,
		1.6748,
		1.802,
		1.94775,
		2.11915,
		2.29055,
		2.46196,
		2.64894,
	}
	// attack: FightClubLegend - Arataki Kesagiri Final Slash DMG: {6}
	akFinal = []float64{
		1.9092,
		2.0646,
		2.22,
		2.442,
		2.5974,
		2.775,
		3.0192,
		3.2634,
		3.5076,
		3.774,
		4.07925,
		4.43822,
		4.7972,
		5.15617,
		5.54778,
	}
	// attack: FightClubLegend - Plunge DMG: {8}
	collision = []float64{
		0.81833,
		0.88494,
		0.95155,
		1.04671,
		1.11332,
		1.18944,
		1.29411,
		1.39878,
		1.50345,
		1.61764,
		1.73182,
		1.84601,
		1.9602,
		2.07438,
		2.18857,
	}
	// attack: FightClubLegend - Low/High Plunge DMG: {9}/{10}
	lowPlunge = []float64{
		1.63632,
		1.76951,
		1.9027,
		2.09297,
		2.22616,
		2.37838,
		2.58767,
		2.79697,
		3.00627,
		3.23459,
		3.46291,
		3.69124,
		3.91956,
		4.14789,
		4.37621,
	}
	// attack: FightClubLegend - Low/High Plunge DMG: {9}/{10}
	highPlunge = []float64{
		2.04385,
		2.21022,
		2.37658,
		2.61423,
		2.78059,
		2.97072,
		3.23214,
		3.49357,
		3.75499,
		4.04018,
		4.32537,
		4.61056,
		4.89575,
		5.18094,
		5.46613,
	}
	// skill: MasatsuZetsugiAkaushiBurst - Skill DMG: {0}
	skill = []float64{
		3.072,
		3.3024,
		3.5328,
		3.84,
		4.0704,
		4.3008,
		4.608,
		4.9152,
		5.2224,
		5.5296,
		5.8368,
		6.144,
		6.528,
		6.912,
		7.296,
	}
	// burst: RoyalDescentBeholdIttoTheEvil - ATK Bonus: {1} DEF
	defconv = []float64{
		0.576,
		0.6192,
		0.6624,
		0.72,
		0.7632,
		0.8064,
		0.864,
		0.9216,
		0.9792,
		1.0368,
		1.0944,
		1.152,
		1.224,
		1.296,
		1.368,
	}
)
