// Code generated by "pipeline"; DO NOT EDIT.

package eula

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Eula, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Eula, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	auto = [][][]float64{
		{{ // attack: FavoniusBladeworkEdel - 1-Hit DMG: {0}
			0.89732,
			0.97036,
			1.0434,
			1.14774,
			1.22078,
			1.30425,
			1.41902,
			1.5338,
			1.64857,
			1.77378,
			1.91725,
			2.08596,
			2.25468,
			2.4234,
			2.60746,
		}},
		{{ // attack: FavoniusBladeworkEdel - 2-Hit DMG: {1}
			0.93551,
			1.01165,
			1.0878,
			1.19658,
			1.27273,
			1.35975,
			1.47941,
			1.59907,
			1.71872,
			1.84926,
			1.99883,
			2.17473,
			2.35063,
			2.52652,
			2.71841,
		}},
		{
			{ // attack: FavoniusBladeworkEdel - 3-Hit DMG: {2}+{2}
				0.56799,
				0.61422,
				0.66045,
				0.7265,
				0.77273,
				0.82556,
				0.89821,
				0.97086,
				1.04351,
				1.12276,
				1.21358,
				1.32037,
				1.42717,
				1.53396,
				1.65047,
			},
			{ // attack: FavoniusBladeworkEdel - 3-Hit DMG: {2}+{2}
				0.56799,
				0.61422,
				0.66045,
				0.7265,
				0.77273,
				0.82556,
				0.89821,
				0.97086,
				1.04351,
				1.12276,
				1.21358,
				1.32037,
				1.42717,
				1.53396,
				1.65047,
			},
		},
		{{ // attack: FavoniusBladeworkEdel - 4-Hit DMG: {3}
			1.12643,
			1.21811,
			1.3098,
			1.44078,
			1.53247,
			1.63725,
			1.78133,
			1.92541,
			2.06948,
			2.22666,
			2.40676,
			2.61855,
			2.83035,
			3.04214,
			3.27319,
		}},
		{
			{ // attack: FavoniusBladeworkEdel - 5-Hit DMG: {4}+{4}
				0.71834,
				0.77681,
				0.83527,
				0.9188,
				0.97727,
				1.04409,
				1.13597,
				1.22785,
				1.31974,
				1.41997,
				1.53482,
				1.66988,
				1.80495,
				1.94001,
				2.08735,
			},
			{ // attack: FavoniusBladeworkEdel - 5-Hit DMG: {4}+{4}
				0.71834,
				0.77681,
				0.83527,
				0.9188,
				0.97727,
				1.04409,
				1.13597,
				1.22785,
				1.31974,
				1.41997,
				1.53482,
				1.66988,
				1.80495,
				1.94001,
				2.08735,
			},
		},
	}
	// attack: FavoniusBladeworkEdel - Plunge DMG: {9}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.59366,
		1.73391,
		1.87415,
		2.01439,
		2.16738,
	}
	// attack: FavoniusBladeworkEdel - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.18665,
		3.46708,
		3.7475,
		4.02793,
		4.33385,
	}
	// attack: FavoniusBladeworkEdel - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.9803,
		4.33057,
		4.68083,
		5.0311,
		5.41321,
	}
	// skill: IcetideVortex - Press DMG: {0}
	skillPress = []float64{
		1.464,
		1.5738,
		1.6836,
		1.83,
		1.9398,
		2.0496,
		2.196,
		2.3424,
		2.4888,
		2.6352,
		2.7816,
		2.928,
		3.111,
		3.294,
		3.477,
	}
	// skill: IcetideVortex - Icewhirl Brand DMG: {2}
	icewhirl = []float64{
		0.96,
		1.032,
		1.104,
		1.2,
		1.272,
		1.344,
		1.44,
		1.536,
		1.632,
		1.728,
		1.824,
		1.92,
		2.04,
		2.16,
		2.28,
	}
	// skill: IcetideVortex - Physical RES Decrease: {3}
	resRed = []float64{
		0.16,
		0.17,
		0.18,
		0.19,
		0.2,
		0.21,
		0.22,
		0.23,
		0.24,
		0.25,
		0.25,
		0.25,
		0.25,
		0.25,
		0.25,
	}
	// burst: GlacialIllumination - Skill DMG: {0}
	burstInitial = []float64{
		2.456,
		2.6402,
		2.8244,
		3.07,
		3.2542,
		3.4384,
		3.684,
		3.9296,
		4.1752,
		4.4208,
		4.6664,
		4.912,
		5.219,
		5.526,
		5.833,
	}
	// burst: GlacialIllumination - Skill DMG: {0}
	skillHold = []float64{
		2.456,
		2.6402,
		2.8244,
		3.07,
		3.2542,
		3.4384,
		3.684,
		3.9296,
		4.1752,
		4.4208,
		4.6664,
		4.912,
		5.219,
		5.526,
		5.833,
	}
	// burst: GlacialIllumination - Lightfall Sword Base DMG: {1}
	burstExplodeBase = []float64{
		3.67048,
		3.96924,
		4.268,
		4.6948,
		4.99356,
		5.335,
		5.80448,
		6.27396,
		6.74344,
		7.2556,
		7.84245,
		8.53259,
		9.22272,
		9.91286,
		10.66573,
	}
	// burst: GlacialIllumination - DMG Per Stack: {2}
	burstExplodeStack = []float64{
		0.74992,
		0.81096,
		0.872,
		0.9592,
		1.02024,
		1.09,
		1.18592,
		1.28184,
		1.37776,
		1.4824,
		1.6023,
		1.7433,
		1.88431,
		2.02531,
		2.17913,
	}
)
