// Code generated by "pipeline"; DO NOT EDIT.

package neuvillette

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Neuvillette, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionCharge: {"short", "ticks"},
	}
	validation.RegisterCharParamValidationFunc(keys.Neuvillette, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: AsWaterSeeksEquilibrium - 1-Hit DMG: {0}
			0.54577,
			0.5867,
			0.62763,
			0.68221,
			0.72314,
			0.76407,
			0.81865,
			0.87323,
			0.92781,
			0.98238,
			1.03696,
			1.09154,
			1.15976,
			1.22798,
			1.2962,
		},
		{ // attack: AsWaterSeeksEquilibrium - 2-Hit DMG: {1}
			0.46246,
			0.49714,
			0.53182,
			0.57807,
			0.61275,
			0.64744,
			0.69368,
			0.73993,
			0.78618,
			0.83242,
			0.87867,
			0.92491,
			0.98272,
			1.04053,
			1.09833,
		},
		{ // attack: AsWaterSeeksEquilibrium - 3-Hit DMG: {2}
			0.72338,
			0.77763,
			0.83188,
			0.90422,
			0.95847,
			1.01273,
			1.08506,
			1.1574,
			1.22974,
			1.30208,
			1.37441,
			1.44675,
			1.53717,
			1.6276,
			1.71802,
		},
	}
	// attack: AsWaterSeeksEquilibrium - Charged Attack DMG: {3}
	charge = []float64{
		1.368,
		1.4706,
		1.5732,
		1.71,
		1.8126,
		1.9152,
		2.052,
		2.1888,
		2.3256,
		2.4624,
		2.5992,
		2.736,
		2.907,
		3.078,
		3.249,
	}
	// attack: AsWaterSeeksEquilibrium - Charged Attack: Equitable Judgment: {4} Max HP
	chargeJudgement = []float64{
		0.07319,
		0.07914,
		0.0851,
		0.09361,
		0.09957,
		0.10638,
		0.11574,
		0.1251,
		0.13446,
		0.14467,
		0.15488,
		0.16509,
		0.17531,
		0.18552,
		0.19573,
	}
	// skill: OTearsIShallRepay - Skill DMG: {0} Max HP
	skill = []float64{
		0.12864,
		0.13829,
		0.14794,
		0.1608,
		0.17045,
		0.1801,
		0.19296,
		0.20582,
		0.21869,
		0.23155,
		0.24442,
		0.25728,
		0.27336,
		0.28944,
		0.30552,
	}
	// skill: OTearsIShallRepay - Spiritbreath Thorn DMG: {1}
	thorn = []float64{
		0.208,
		0.2236,
		0.2392,
		0.26,
		0.2756,
		0.2912,
		0.312,
		0.3328,
		0.3536,
		0.3744,
		0.3952,
		0.416,
		0.442,
		0.468,
		0.494,
	}
	// burst: OTidesIHaveReturned - Skill DMG: {0} Max HP
	burst = []float64{
		0.22258,
		0.23927,
		0.25596,
		0.27822,
		0.29492,
		0.31161,
		0.33387,
		0.35612,
		0.37838,
		0.40064,
		0.4229,
		0.44516,
		0.47298,
		0.5008,
		0.52862,
	}
	// burst: OTidesIHaveReturned - Waterfall DMG: {1} Max HP
	burstWaterfall = []float64{
		0.09105,
		0.09788,
		0.10471,
		0.11382,
		0.12065,
		0.12748,
		0.13658,
		0.14569,
		0.15479,
		0.1639,
		0.173,
		0.18211,
		0.19349,
		0.20487,
		0.21625,
	}
)
