// Code generated by "pipeline"; DO NOT EDIT.

package illuga

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Illuga, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionSkill: {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Illuga, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: OathkeepersSpear - 1-Hit DMG: {0}
			0.47366,
			0.51222,
			0.55077,
			0.60585,
			0.6444,
			0.68846,
			0.74905,
			0.80963,
			0.87022,
			0.93631,
			1.0024,
			1.06849,
			1.13459,
			1.20068,
			1.26677,
		}},
		{{ // attack: OathkeepersSpear - 2-Hit DMG: {1}
			0.48526,
			0.52475,
			0.56425,
			0.62068,
			0.66017,
			0.70531,
			0.76738,
			0.82945,
			0.89152,
			0.95922,
			1.02693,
			1.09465,
			1.16235,
			1.23006,
			1.29778,
		}},
		{
			{ // attack: OathkeepersSpear - 3-Hit DMG: {2}+{3}
				0.31433,
				0.33992,
				0.3655,
				0.40205,
				0.42764,
				0.45687,
				0.49708,
				0.53728,
				0.57749,
				0.62135,
				0.66521,
				0.70907,
				0.75293,
				0.79679,
				0.84065,
			},
			{ // attack: OathkeepersSpear - 3-Hit DMG: {2}+{3}
				0.31433,
				0.33992,
				0.3655,
				0.40205,
				0.42764,
				0.45687,
				0.49708,
				0.53728,
				0.57749,
				0.62135,
				0.66521,
				0.70907,
				0.75293,
				0.79679,
				0.84065,
			},
		},
		{{ // attack: OathkeepersSpear - 4-Hit DMG: {4}
			0.76279,
			0.82487,
			0.88696,
			0.97566,
			1.03774,
			1.1087,
			1.20627,
			1.30383,
			1.4014,
			1.50783,
			1.61427,
			1.7207,
			1.82714,
			1.93357,
			2.04001,
		}},
	}
	// attack: OathkeepersSpear - Charged Attack DMG: {5}
	charge = []float64{
		1.11026,
		1.20063,
		1.291,
		1.4201,
		1.51047,
		1.61375,
		1.75576,
		1.89777,
		2.03978,
		2.1947,
		2.34962,
		2.50454,
		2.65946,
		2.81438,
		2.9693,
	}
	// attack: OathkeepersSpear - Plunge DMG: {7}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: OathkeepersSpear - Low/High Plunge DMG: {8}/{9}
	plungeLow = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: OathkeepersSpear - Low/High Plunge DMG: {8}/{9}
	plungeHigh = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: DawnbearingSongbird - Press DMG: {0} Elemental Mastery+{1} DEF
	skillTapEM = []float64{
		4.8256,
		5.18752,
		5.54944,
		6.032,
		6.39392,
		6.75584,
		7.2384,
		7.72096,
		8.20352,
		8.68608,
		9.16864,
		9.6512,
		10.2544,
		10.8576,
		11.4608,
	}
	// skill: DawnbearingSongbird - Press DMG: {0} Elemental Mastery+{1} DEF
	skillTapDef = []float64{
		2.4128,
		2.59376,
		2.77472,
		3.016,
		3.19696,
		3.37792,
		3.6192,
		3.86048,
		4.10176,
		4.34304,
		4.58432,
		4.8256,
		5.1272,
		5.4288,
		5.7304,
	}
	// skill: DawnbearingSongbird - Hold DMG: {2} Elemental Mastery+{3} DEF
	skillHoldEM = []float64{
		6.032,
		6.4844,
		6.9368,
		7.54,
		7.9924,
		8.4448,
		9.048,
		9.6512,
		10.2544,
		10.8576,
		11.4608,
		12.064,
		12.818,
		13.572,
		14.326,
	}
	// skill: DawnbearingSongbird - Hold DMG: {2} Elemental Mastery+{3} DEF
	skillHoldDef = []float64{
		3.016,
		3.2422,
		3.4684,
		3.77,
		3.9962,
		4.2224,
		4.524,
		4.8256,
		5.1272,
		5.4288,
		5.7304,
		6.032,
		6.409,
		6.786,
		7.163,
	}
	// burst: ShadowlessReflection - Skill DMG: {0} Elemental Mastery+{1} DEF
	burstEM = []float64{
		8.272,
		8.8924,
		9.5128,
		10.34,
		10.9604,
		11.5808,
		12.408,
		13.2352,
		14.0624,
		14.8896,
		15.7168,
		16.544,
		17.578,
		18.612,
		19.646,
	}
	// burst: ShadowlessReflection - Skill DMG: {0} Elemental Mastery+{1} DEF
	burstDef = []float64{
		4.136,
		4.4462,
		4.7564,
		5.17,
		5.4802,
		5.7904,
		6.204,
		6.6176,
		7.0312,
		7.4448,
		7.8584,
		8.272,
		8.789,
		9.306,
		9.823,
	}
	// burst: ShadowlessReflection - Geo DMG Bonus: {2} Elemental Mastery
	burstBuffGeo = []float64{
		0.336,
		0.3612,
		0.3864,
		0.42,
		0.4452,
		0.4704,
		0.504,
		0.5376,
		0.5712,
		0.6048,
		0.6384,
		0.672,
		0.714,
		0.756,
		0.798,
	}
	// burst: ShadowlessReflection - Lunar-Crystallize Reaction DMG Bonus: {3} Elemental Mastery
	burstBuffLcr = []float64{
		2.2592,
		2.42864,
		2.59808,
		2.824,
		2.99344,
		3.16288,
		3.3888,
		3.61472,
		3.84064,
		4.06656,
		4.29248,
		4.5184,
		4.8008,
		5.0832,
		5.3656,
	}
)
