// Code generated by "pipeline"; DO NOT EDIT.

package kinich

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Kinich, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"direction"},
		action.ActionSkill:  {"c6-travel", "hold", "travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Kinich, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: NightsunStyle - 1-Hit DMG: {0}
			0.98986,
			1.07043,
			1.151,
			1.2661,
			1.34667,
			1.43875,
			1.56536,
			1.69197,
			1.81858,
			1.9567,
			2.09482,
			2.23294,
			2.37106,
			2.50918,
			2.6473,
		},
		{ // attack: NightsunStyle - 2-Hit DMG: {1}
			0.82904,
			0.89652,
			0.964,
			1.0604,
			1.12788,
			1.205,
			1.31104,
			1.41708,
			1.52312,
			1.6388,
			1.75448,
			1.87016,
			1.98584,
			2.10152,
			2.2172,
		},
		{ // attack: NightsunStyle - 3-Hit DMG: {2}
			1.23496,
			1.33548,
			1.436,
			1.5796,
			1.68012,
			1.795,
			1.95296,
			2.11092,
			2.26888,
			2.4412,
			2.61352,
			2.78584,
			2.95816,
			3.13048,
			3.3028,
		},
	}
	// attack: NightsunStyle - Charged Attack DMG: {3}×3
	charge = []float64{
		0.48418,
		0.52359,
		0.563,
		0.6193,
		0.65871,
		0.70375,
		0.76568,
		0.82761,
		0.88954,
		0.9571,
		1.02466,
		1.09222,
		1.15978,
		1.22734,
		1.2949,
	}
	// attack: NightsunStyle - Plunge DMG: {5}
	collision = []float64{
		0.74588,
		0.80659,
		0.8673,
		0.95403,
		1.01474,
		1.08413,
		1.17953,
		1.27493,
		1.37033,
		1.47441,
		1.57849,
		1.68256,
		1.78664,
		1.89071,
		1.99479,
	}
	// attack: NightsunStyle - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.49144,
		1.61284,
		1.73423,
		1.90766,
		2.02905,
		2.16779,
		2.35856,
		2.54932,
		2.74009,
		2.94819,
		3.1563,
		3.36441,
		3.57252,
		3.78063,
		3.98873,
	}
	// attack: NightsunStyle - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.86289,
		2.01452,
		2.16615,
		2.38277,
		2.5344,
		2.70769,
		2.94596,
		3.18424,
		3.42252,
		3.68246,
		3.94239,
		4.20233,
		4.46227,
		4.72221,
		4.98214,
	}
	// skill: CanopyHunterRidingHigh - Loop Shot DMG: {0}×2
	loopShot = []float64{
		0.5728,
		0.61576,
		0.65872,
		0.716,
		0.75896,
		0.80192,
		0.8592,
		0.91648,
		0.97376,
		1.03104,
		1.08832,
		1.1456,
		1.2172,
		1.2888,
		1.3604,
	}
	// skill: CanopyHunterRidingHigh - Scalespiker Cannon DMG: {1}
	scalespikerCannon = []float64{
		6.8744,
		7.38998,
		7.90556,
		8.593,
		9.10858,
		9.62416,
		10.3116,
		10.99904,
		11.68648,
		12.37392,
		13.06136,
		13.7488,
		14.6081,
		15.4674,
		16.3267,
	}
	// burst: HailToTheAlmightyDragonlord - Skill DMG: {0}
	burst = []float64{
		1.34,
		1.4405,
		1.541,
		1.675,
		1.7755,
		1.876,
		2.01,
		2.144,
		2.278,
		2.412,
		2.546,
		2.68,
		2.8475,
		3.015,
		3.1825,
	}
	// burst: HailToTheAlmightyDragonlord - Dragon Breath DMG: {1}
	dragonBreath = []float64{
		1.20736,
		1.29791,
		1.38846,
		1.5092,
		1.59975,
		1.6903,
		1.81104,
		1.93178,
		2.05251,
		2.17325,
		2.29398,
		2.41472,
		2.56564,
		2.71656,
		2.86748,
	}
)
