// Code generated by "pipeline"; DO NOT EDIT.

package sucrose

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Sucrose, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Sucrose, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: WindSpiritCreation - 1-Hit DMG: {0}
			0.33464,
			0.35974,
			0.38484,
			0.4183,
			0.4434,
			0.4685,
			0.50196,
			0.53542,
			0.56889,
			0.60235,
			0.63582,
			0.66928,
			0.71111,
			0.75294,
			0.79477,
		},
		{ // attack: WindSpiritCreation - 2-Hit DMG: {1}
			0.30616,
			0.32912,
			0.35208,
			0.3827,
			0.40566,
			0.42862,
			0.45924,
			0.48986,
			0.52047,
			0.55109,
			0.5817,
			0.61232,
			0.65059,
			0.68886,
			0.72713,
		},
		{ // attack: WindSpiritCreation - 3-Hit DMG: {2}
			0.38448,
			0.41332,
			0.44215,
			0.4806,
			0.50944,
			0.53827,
			0.57672,
			0.61517,
			0.65362,
			0.69206,
			0.73051,
			0.76896,
			0.81702,
			0.86508,
			0.91314,
		},
		{ // attack: WindSpiritCreation - 4-Hit DMG: {3}
			0.47918,
			0.51511,
			0.55105,
			0.59897,
			0.63491,
			0.67085,
			0.71876,
			0.76668,
			0.8146,
			0.86252,
			0.91043,
			0.95835,
			1.01825,
			1.07815,
			1.13804,
		},
	}
	// attack: WindSpiritCreation - Charged Attack DMG: {4}
	charge = []float64{
		1.2016,
		1.29172,
		1.38184,
		1.502,
		1.59212,
		1.68224,
		1.8024,
		1.92256,
		2.04272,
		2.16288,
		2.28304,
		2.4032,
		2.5534,
		2.7036,
		2.8538,
	}
	// attack: WindSpiritCreation - Plunge DMG: {6}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: WindSpiritCreation - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: WindSpiritCreation - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: AstableAnemohypostasisCreation6308 - Skill DMG: {0}
	skill = []float64{
		2.112,
		2.2704,
		2.4288,
		2.64,
		2.7984,
		2.9568,
		3.168,
		3.3792,
		3.5904,
		3.8016,
		4.0128,
		4.224,
		4.488,
		4.752,
		5.016,
	}
	// burst: ForbiddenCreationIsomer75TypeII - DoT: {0}
	burstDot = []float64{
		1.48,
		1.591,
		1.702,
		1.85,
		1.961,
		2.072,
		2.22,
		2.368,
		2.516,
		2.664,
		2.812,
		2.96,
		3.145,
		3.33,
		3.515,
	}
	// burst: ForbiddenCreationIsomer75TypeII - Additional Elemental DMG: {1}
	burstAbsorb = []float64{
		0.44,
		0.473,
		0.506,
		0.55,
		0.583,
		0.616,
		0.66,
		0.704,
		0.748,
		0.792,
		0.836,
		0.88,
		0.935,
		0.99,
		1.045,
	}
)
