// Code generated by "pipeline"; DO NOT EDIT.

package mualani

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Mualani, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionBurst:  {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Mualani, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: CoolingTreatment - 1-Hit DMG: {0}
			0.51396,
			0.55251,
			0.59105,
			0.64245,
			0.681,
			0.71954,
			0.77094,
			0.82234,
			0.87373,
			0.92513,
			0.97652,
			1.02792,
			1.09216,
			1.15641,
			1.22065,
		},
		{ // attack: CoolingTreatment - 2-Hit DMG: {1}
			0.44626,
			0.47973,
			0.51319,
			0.55782,
			0.59129,
			0.62476,
			0.66938,
			0.71401,
			0.75863,
			0.80326,
			0.84789,
			0.89251,
			0.94829,
			1.00408,
			1.05986,
		},
		{ // attack: CoolingTreatment - 3-Hit DMG: {2}
			0.70034,
			0.75287,
			0.8054,
			0.87543,
			0.92796,
			0.98048,
			1.05052,
			1.12055,
			1.19059,
			1.26062,
			1.33065,
			1.40069,
			1.48823,
			1.57577,
			1.66332,
		},
	}
	// attack: CoolingTreatment - Charged Attack DMG: {3}
	charge = []float64{
		1.4288,
		1.53596,
		1.64312,
		1.786,
		1.89316,
		2.00032,
		2.1432,
		2.28608,
		2.42896,
		2.57184,
		2.71472,
		2.8576,
		3.0362,
		3.2148,
		3.3934,
	}
	// skill: SurfsharkWavebreaker - Sharky's Bite Base DMG: {0} Max HP
	bite = []float64{
		0.0868,
		0.09331,
		0.09982,
		0.1085,
		0.11501,
		0.12152,
		0.1302,
		0.13888,
		0.14756,
		0.15624,
		0.16492,
		0.1736,
		0.18445,
		0.1953,
		0.20615,
	}
	// skill: SurfsharkWavebreaker - Wave Momentum DMG Bonus: {1} Max HP/Stack
	momentumBonus = []float64{
		0.0434,
		0.04665,
		0.04991,
		0.05425,
		0.05751,
		0.06076,
		0.0651,
		0.06944,
		0.07378,
		0.07812,
		0.08246,
		0.0868,
		0.09223,
		0.09765,
		0.10307,
	}
	// skill: SurfsharkWavebreaker - Sharky's Surging Bite Additional DMG Bonus: {2} Max HP
	surgingBite = []float64{
		0.217,
		0.23327,
		0.24955,
		0.27125,
		0.28752,
		0.3038,
		0.3255,
		0.3472,
		0.3689,
		0.3906,
		0.4123,
		0.434,
		0.46112,
		0.48825,
		0.51538,
	}
	// burst: Boomsharkalaka - Skill DMG: {0} Max HP
	burst = []float64{
		0.58439,
		0.62822,
		0.67205,
		0.73049,
		0.77432,
		0.81815,
		0.87659,
		0.93503,
		0.99347,
		1.05191,
		1.11035,
		1.16878,
		1.24183,
		1.31488,
		1.38793,
	}
)
