// Code generated by "pipeline"; DO NOT EDIT.

package alhaitham

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Alhaitham, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision", "short"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"hold"},
	}
	validation.RegisterCharParamValidationFunc(keys.Alhaitham, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][][]float64{
		{{ // attack: AbductiveReasoning - 1-Hit DMG: {0}
			0.49526,
			0.53557,
			0.57588,
			0.63347,
			0.67378,
			0.71985,
			0.7832,
			0.84654,
			0.90989,
			0.979,
			1.0481,
			1.11721,
			1.18631,
			1.25542,
			1.32452,
		}},
		{{ // attack: AbductiveReasoning - 2-Hit DMG: {1}
			0.50749,
			0.5488,
			0.59011,
			0.64912,
			0.69043,
			0.73764,
			0.80255,
			0.86746,
			0.93237,
			1.00319,
			1.074,
			1.14481,
			1.21563,
			1.28644,
			1.35725,
		}},
		{
			{ // attack: AbductiveReasoning - 3-Hit DMG: {2}+{3}
				0.34179,
				0.36961,
				0.39742,
				0.43717,
				0.46499,
				0.49678,
				0.5405,
				0.58421,
				0.62793,
				0.67562,
				0.72331,
				0.771,
				0.8187,
				0.86639,
				0.91408,
			},
			{ // attack: AbductiveReasoning - 3-Hit DMG: {2}+{3}
				0.34179,
				0.36961,
				0.39742,
				0.43717,
				0.46499,
				0.49678,
				0.5405,
				0.58421,
				0.62793,
				0.67562,
				0.72331,
				0.771,
				0.8187,
				0.86639,
				0.91408,
			},
		},
		{{ // attack: AbductiveReasoning - 4-Hit DMG: {4}
			0.66768,
			0.72202,
			0.77637,
			0.85401,
			0.90835,
			0.97046,
			1.05586,
			1.14126,
			1.22667,
			1.31983,
			1.41299,
			1.50616,
			1.59932,
			1.69249,
			1.78565,
		}},
		{{ // attack: AbductiveReasoning - 5-Hit DMG: {5}
			0.83851,
			0.90676,
			0.97501,
			1.07251,
			1.14076,
			1.21876,
			1.32601,
			1.43326,
			1.54052,
			1.65752,
			1.77452,
			1.89152,
			2.00852,
			2.12552,
			2.24252,
		}},
	}
	charge = [][]float64{
		{ // attack: AbductiveReasoning - Charged Attack DMG: {6}+{7}
			0.55255,
			0.59753,
			0.6425,
			0.70675,
			0.75173,
			0.80313,
			0.8738,
			0.94447,
			1.01515,
			1.09225,
			1.16935,
			1.24645,
			1.32355,
			1.40065,
			1.47775,
		},
		{ // attack: AbductiveReasoning - Charged Attack DMG: {6}+{7}
			0.55255,
			0.59753,
			0.6425,
			0.70675,
			0.75173,
			0.80313,
			0.8738,
			0.94447,
			1.01515,
			1.09225,
			1.16935,
			1.24645,
			1.32355,
			1.40065,
			1.47775,
		},
	}
	// attack: AbductiveReasoning - Plunge DMG: {9}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: AbductiveReasoning - Low/High Plunge DMG: {10}/{11}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: AbductiveReasoning - Low/High Plunge DMG: {10}/{11}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: UniversalityAnElaborationOnForm - Rush Attack DMG: {0} ATK+{1} Elemental Mastery
	rushAtk = []float64{
		1.936,
		2.0812,
		2.2264,
		2.42,
		2.5652,
		2.7104,
		2.904,
		3.0976,
		3.2912,
		3.4848,
		3.6784,
		3.872,
		4.114,
		4.356,
		4.598,
	}
	// skill: UniversalityAnElaborationOnForm - Rush Attack DMG: {0} ATK+{1} Elemental Mastery
	rushEm = []float64{
		1.5488,
		1.66496,
		1.78112,
		1.936,
		2.05216,
		2.16832,
		2.3232,
		2.47808,
		2.63296,
		2.78784,
		2.94272,
		3.0976,
		3.2912,
		3.4848,
		3.6784,
	}
	// skill: UniversalityAnElaborationOnForm - 1-Mirror Projection Attack DMG: {3} ATK+{4} Elemental Mastery
	mirrorAtk = []float64{
		0.672,
		0.7224,
		0.7728,
		0.84,
		0.8904,
		0.9408,
		1.008,
		1.0752,
		1.1424,
		1.2096,
		1.2768,
		1.344,
		1.428,
		1.512,
		1.596,
	}
	// skill: UniversalityAnElaborationOnForm - 1-Mirror Projection Attack DMG: {3} ATK+{4} Elemental Mastery
	mirrorEm = []float64{
		1.344,
		1.4448,
		1.5456,
		1.68,
		1.7808,
		1.8816,
		2.016,
		2.1504,
		2.2848,
		2.4192,
		2.5536,
		2.688,
		2.856,
		3.024,
		3.192,
	}
	// burst: ParticularFieldFettersOfPhenomena - Single-Instance DMG: {0} ATK+{1} Elemental Mastery
	burstAtk = []float64{
		1.216,
		1.3072,
		1.3984,
		1.52,
		1.6112,
		1.7024,
		1.824,
		1.9456,
		2.0672,
		2.1888,
		2.3104,
		2.432,
		2.584,
		2.736,
		2.888,
	}
	// burst: ParticularFieldFettersOfPhenomena - Single-Instance DMG: {0} ATK+{1} Elemental Mastery
	burstEm = []float64{
		0.9728,
		1.04576,
		1.11872,
		1.216,
		1.28896,
		1.36192,
		1.4592,
		1.55648,
		1.65376,
		1.75104,
		1.84832,
		1.9456,
		2.0672,
		2.1888,
		2.3104,
	}
)
