// Code generated by "pipeline"; DO NOT EDIT.

package mizuki

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.YumemizukiMizuki, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack: {"travel"},
		action.ActionSkill:  {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.YumemizukiMizuki, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: PureHeartPureDreams - 1-Hit DMG: {0}
			0.52277,
			0.56198,
			0.60118,
			0.65346,
			0.69267,
			0.73188,
			0.78415,
			0.83643,
			0.88871,
			0.94098,
			0.99326,
			1.04554,
			1.11088,
			1.17623,
			1.24157,
		},
		{ // attack: PureHeartPureDreams - 2-Hit DMG: {1}
			0.46914,
			0.50433,
			0.53952,
			0.58643,
			0.62162,
			0.6568,
			0.70372,
			0.75063,
			0.79755,
			0.84446,
			0.89137,
			0.93829,
			0.99693,
			1.05557,
			1.11422,
		},
		{ // attack: PureHeartPureDreams - 3-Hit DMG: {2}
			0.71369,
			0.76722,
			0.82074,
			0.89211,
			0.94564,
			0.99916,
			1.07053,
			1.1419,
			1.21327,
			1.28464,
			1.35601,
			1.42738,
			1.51659,
			1.6058,
			1.69501,
		},
	}
	// attack: PureHeartPureDreams - Charged Attack DMG: {3}
	charge = []float64{
		1.3,
		1.3975,
		1.495,
		1.625,
		1.7225,
		1.82,
		1.95,
		2.08,
		2.21,
		2.34,
		2.47,
		2.6,
		2.7625,
		2.925,
		3.0875,
	}
	// attack: PureHeartPureDreams - Plunge DMG: {5}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: PureHeartPureDreams - Low/High Plunge DMG: {6}/{7}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: PureHeartPureDreams - Low/High Plunge DMG: {6}/{7}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: AisaUtamakuraPilgrimage - Continuous Attack DMG: {0}
	cloudDMG = []float64{
		0.44912,
		0.4828,
		0.51649,
		0.5614,
		0.59508,
		0.62877,
		0.67368,
		0.71859,
		0.7635,
		0.80842,
		0.85333,
		0.89824,
		0.95438,
		1.01052,
		1.06666,
	}
	// skill: AisaUtamakuraPilgrimage - Elemental Mastery-Based Swirl DMG Increase: {1} per 100 Points
	swirlDMG = []float64{
		0.18,
		0.21,
		0.24,
		0.27,
		0.3,
		0.33,
		0.36,
		0.39,
		0.42,
		0.45,
		0.48,
		0.51,
		0.54,
		0.57,
		0.6,
	}
	// skill: AisaUtamakuraPilgrimage - Elemental Mastery-Based Stellar Swirl DMG Increase: {5} per 100 Points
	stellarSwirlDMG = []float64{
		0.018,
		0.021,
		0.024,
		0.027,
		0.03,
		0.033,
		0.036,
		0.039,
		0.042,
		0.045,
		0.048,
		0.051,
		0.054,
		0.057,
		0.06,
	}
	// skill: AisaUtamakuraPilgrimage - Skill DMG: {3}
	skill = []float64{
		0.57744,
		0.62075,
		0.66406,
		0.7218,
		0.76511,
		0.80842,
		0.86616,
		0.9239,
		0.98165,
		1.03939,
		1.09714,
		1.15488,
		1.22706,
		1.29924,
		1.37142,
	}
	// burst: AnrakuSecretSpringTherapy - Skill DMG: {0}
	burstDMG = []float64{
		0.9408,
		1.01136,
		1.08192,
		1.176,
		1.24656,
		1.31712,
		1.4112,
		1.50528,
		1.59936,
		1.69344,
		1.78752,
		1.8816,
		1.9992,
		2.1168,
		2.2344,
	}
	// burst: AnrakuSecretSpringTherapy - Munen Shockwave DMG: {1}
	snackDMG = []float64{
		0.7056,
		0.75852,
		0.81144,
		0.882,
		0.93492,
		0.98784,
		1.0584,
		1.12896,
		1.19952,
		1.27008,
		1.34064,
		1.4112,
		1.4994,
		1.5876,
		1.6758,
	}
	// burst: AnrakuSecretSpringTherapy - Snack Pick-Up HP Regeneration: {2} Elemental Mastery+{6}
	snackHealEM = []float64{
		1.3056,
		1.40352,
		1.50144,
		1.632,
		1.72992,
		1.82784,
		1.9584,
		2.08896,
		2.21952,
		2.35008,
		2.48064,
		2.6112,
		2.7744,
		2.9376,
		3.1008,
	}
	// burst: AnrakuSecretSpringTherapy - Snack Pick-Up HP Regeneration: {2} Elemental Mastery+{6}
	snackHealFlat = []float64{
		314.57,
		346.0314,
		380.1145,
		416.8195,
		456.1462,
		498.0947,
		542.6649,
		589.857,
		639.6708,
		692.1065,
		747.1639,
		804.843,
		865.144,
		928.0668,
		993.6113,
	}
)
