// Code generated by "pipeline"; DO NOT EDIT.

package yanfei

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Yanfei, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionAttack:     {"travel"},
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
	}
	validation.RegisterCharParamValidationFunc(keys.Yanfei, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

var (
	attack = [][]float64{
		{ // attack: SealOfApproval - 1-Hit DMG: {0}
			0.58342,
			0.62717,
			0.67093,
			0.72927,
			0.77303,
			0.81678,
			0.87512,
			0.93347,
			0.99181,
			1.05015,
			1.10849,
			1.16683,
			1.23976,
			1.31269,
			1.38561,
		},
		{ // attack: SealOfApproval - 2-Hit DMG: {1}
			0.52126,
			0.56035,
			0.59944,
			0.65157,
			0.69066,
			0.72976,
			0.78188,
			0.83401,
			0.88613,
			0.93826,
			0.99039,
			1.04251,
			1.10767,
			1.17283,
			1.23798,
		},
		{ // attack: SealOfApproval - 3-Hit DMG: {2}
			0.76013,
			0.81714,
			0.87415,
			0.95016,
			1.00717,
			1.06418,
			1.14019,
			1.21621,
			1.29222,
			1.36823,
			1.44424,
			1.52026,
			1.61527,
			1.71029,
			1.8053,
		},
	}
	charge = [][]float64{
		{ // attack: SealOfApproval - Charged Attack: {3}/{4}/{5}/{6}/{7}
			0.98229,
			1.04111,
			1.09993,
			1.1764,
			1.23522,
			1.29404,
			1.37051,
			1.44697,
			1.52344,
			1.5999,
			1.67637,
			1.75284,
			1.8293,
			1.90577,
			1.98223,
		},
		{ // attack: SealOfApproval - Charged Attack: {3}/{4}/{5}/{6}/{7}
			1.15564,
			1.22484,
			1.29404,
			1.384,
			1.4532,
			1.5224,
			1.61236,
			1.70232,
			1.79228,
			1.88224,
			1.9722,
			2.06216,
			2.15212,
			2.24208,
			2.33204,
		},
		{ // attack: SealOfApproval - Charged Attack: {3}/{4}/{5}/{6}/{7}
			1.32899,
			1.40857,
			1.48815,
			1.5916,
			1.67118,
			1.75076,
			1.85421,
			1.95767,
			2.06112,
			2.16458,
			2.26803,
			2.37148,
			2.47494,
			2.57839,
			2.68185,
		},
		{ // attack: SealOfApproval - Charged Attack: {3}/{4}/{5}/{6}/{7}
			1.50233,
			1.59229,
			1.68225,
			1.7992,
			1.88916,
			1.97912,
			2.09607,
			2.21302,
			2.32996,
			2.44691,
			2.56386,
			2.68081,
			2.79776,
			2.9147,
			3.03165,
		},
		{ // attack: SealOfApproval - Charged Attack: {3}/{4}/{5}/{6}/{7}
			1.67568,
			1.77602,
			1.87636,
			2.0068,
			2.10714,
			2.20748,
			2.33792,
			2.46836,
			2.59881,
			2.72925,
			2.85969,
			2.99013,
			3.12057,
			3.25102,
			3.38146,
		},
	}
	// attack: SealOfApproval - Plunge DMG: {15}
	collision = []float64{
		0.56829,
		0.61454,
		0.6608,
		0.72688,
		0.77314,
		0.826,
		0.89869,
		0.97138,
		1.04406,
		1.12336,
		1.20266,
		1.28195,
		1.36125,
		1.44054,
		1.51984,
	}
	// attack: SealOfApproval - Low/High Plunge DMG: {16}/{17}
	lowPlunge = []float64{
		1.13634,
		1.22883,
		1.32132,
		1.45345,
		1.54594,
		1.65165,
		1.797,
		1.94234,
		2.08769,
		2.24624,
		2.4048,
		2.56336,
		2.72192,
		2.88048,
		3.03904,
	}
	// attack: SealOfApproval - Low/High Plunge DMG: {16}/{17}
	highPlunge = []float64{
		1.41934,
		1.53487,
		1.6504,
		1.81544,
		1.93097,
		2.063,
		2.24454,
		2.42609,
		2.60763,
		2.80568,
		3.00373,
		3.20178,
		3.39982,
		3.59787,
		3.79592,
	}
	// skill: SignedEdict - Skill DMG: {0}
	skill = []float64{
		1.696,
		1.8232,
		1.9504,
		2.12,
		2.2472,
		2.3744,
		2.544,
		2.7136,
		2.8832,
		3.0528,
		3.2224,
		3.392,
		3.604,
		3.816,
		4.028,
	}
	// burst: DoneDeal - Skill DMG: {0}
	burst = []float64{
		1.824,
		1.9608,
		2.0976,
		2.28,
		2.4168,
		2.5536,
		2.736,
		2.9184,
		3.1008,
		3.2832,
		3.4656,
		3.648,
		3.876,
		4.104,
		4.332,
	}
	// burst: DoneDeal - Charged Attack DMG Bonus: {1}
	burstBonus = []float64{
		0.334,
		0.354,
		0.374,
		0.4,
		0.42,
		0.44,
		0.466,
		0.492,
		0.518,
		0.544,
		0.57,
		0.596,
		0.622,
		0.648,
		0.674,
	}
)
