// Code generated by "pipeline"; DO NOT EDIT.

package emilie

import (
	"fmt"
	"slices"

	"github.com/genshinsim/gcsim/pkg/core"
	"github.com/genshinsim/gcsim/pkg/core/action"
	"github.com/genshinsim/gcsim/pkg/core/keys"
	"github.com/genshinsim/gcsim/pkg/gcs/validation"
)

func init() {
	core.RegisterCharFunc(keys.Emilie, NewChar)
	paramsFor := map[action.Action][]string{
		action.ActionLowPlunge:  {"collision"},
		action.ActionHighPlunge: {"collision"},
		action.ActionSkill:      {"travel"},
		action.ActionBurst:      {"travel"},
	}
	validation.RegisterCharParamValidationFunc(keys.Emilie, func(a action.Action, keys []string) error {
		valid, ok := paramsFor[a]
		if !ok {
			return nil
		}
		for _, v := range keys {
			if !slices.Contains(valid, v) {
				return fmt.Errorf("key %v is invalid for action %v", v, a)
			}
		}
		return nil
	})
}

const (
	skillDuration = 22   // skill: FragranceExtraction - Lumidouce Case Duration: {3}s
	skillArkeCD   = 10   // skill: FragranceExtraction - Spiritbreath Thorn Interval: {5}s
	skillCD       = 14   // skill: FragranceExtraction - Skill CD: {6}s
	burstDuration = 2.8  // burst: AromaticExplication - Level 3 Lumidouce Case Duration: {1}s
	burstCD       = 13.5 // burst: AromaticExplication - CD: {2}s
)

var (
	attack = [][]float64{
		{ // attack: ShadowHuntingSpearCustom - 1-Hit DMG: {0}
			0.48561,
			0.52513,
			0.56466,
			0.62113,
			0.66065,
			0.70582,
			0.76794,
			0.83005,
			0.89216,
			0.95992,
			1.02768,
			1.09544,
			1.1632,
			1.23096,
			1.29872,
		},
		{ // attack: ShadowHuntingSpearCustom - 2-Hit DMG: {1}
			0.44895,
			0.4855,
			0.52204,
			0.57424,
			0.61079,
			0.65255,
			0.70997,
			0.7674,
			0.82482,
			0.88747,
			0.95011,
			1.01276,
			1.0754,
			1.13805,
			1.20069,
		},
		{ // attack: ShadowHuntingSpearCustom - 3-Hit DMG: {2}
			0.593,
			0.64127,
			0.68954,
			0.75849,
			0.80676,
			0.86193,
			0.93777,
			1.01362,
			1.08947,
			1.17222,
			1.25496,
			1.33771,
			1.42045,
			1.5032,
			1.58594,
		},
		{ // attack: ShadowHuntingSpearCustom - 4-Hit DMG: {3}
			0.75103,
			0.81216,
			0.87329,
			0.96062,
			1.02175,
			1.09161,
			1.18767,
			1.28374,
			1.3798,
			1.48459,
			1.58939,
			1.69418,
			1.79898,
			1.90377,
			2.00857,
		},
	}
	// attack: ShadowHuntingSpearCustom - Charged Attack DMG: {4}
	charge = []float64{
		0.91332,
		0.98766,
		1.062,
		1.1682,
		1.24254,
		1.3275,
		1.44432,
		1.56114,
		1.67796,
		1.8054,
		1.93284,
		2.06028,
		2.18772,
		2.31516,
		2.4426,
	}
	// attack: ShadowHuntingSpearCustom - Plunge DMG: {6}
	collision = []float64{
		0.63932,
		0.69136,
		0.7434,
		0.81774,
		0.86978,
		0.92925,
		1.01102,
		1.0928,
		1.17457,
		1.26378,
		1.35299,
		1.4422,
		1.5314,
		1.62061,
		1.70982,
	}
	// attack: ShadowHuntingSpearCustom - Low/High Plunge DMG: {7}/{8}
	lowPlunge = []float64{
		1.27838,
		1.38243,
		1.48649,
		1.63513,
		1.73919,
		1.85811,
		2.02162,
		2.18513,
		2.34865,
		2.52702,
		2.7054,
		2.88378,
		3.06216,
		3.24054,
		3.41892,
	}
	// attack: ShadowHuntingSpearCustom - Low/High Plunge DMG: {7}/{8}
	highPlunge = []float64{
		1.59676,
		1.72673,
		1.8567,
		2.04237,
		2.17234,
		2.32087,
		2.52511,
		2.72935,
		2.93359,
		3.15639,
		3.37919,
		3.602,
		3.8248,
		4.04761,
		4.27041,
	}
	// skill: FragranceExtraction - Skill DMG: {0}
	skillDMG = []float64{
		0.4708,
		0.50611,
		0.54142,
		0.5885,
		0.62381,
		0.65912,
		0.7062,
		0.75328,
		0.80036,
		0.84744,
		0.89452,
		0.9416,
		1.00045,
		1.0593,
		1.11815,
	}
	skillLumidouce = [][]float64{
		{ // skill: FragranceExtraction - Level 1 Lumidouce Case Attack DMG: {1}
			0.396,
			0.4257,
			0.4554,
			0.495,
			0.5247,
			0.5544,
			0.594,
			0.6336,
			0.6732,
			0.7128,
			0.7524,
			0.792,
			0.8415,
			0.891,
			0.9405,
		},
		{ // skill: FragranceExtraction - Level 2 Lumidouce Case Attack DMG: {2}×2
			0.84,
			0.903,
			0.966,
			1.05,
			1.113,
			1.176,
			1.26,
			1.344,
			1.428,
			1.512,
			1.596,
			1.68,
			1.785,
			1.89,
			1.995,
		},
	}
	// skill: FragranceExtraction - Spiritbreath Thorn DMG: {4}
	skillArke = []float64{
		0.3852,
		0.41409,
		0.44298,
		0.4815,
		0.51039,
		0.53928,
		0.5778,
		0.61632,
		0.65484,
		0.69336,
		0.73188,
		0.7704,
		0.81855,
		0.8667,
		0.91485,
	}
	// burst: AromaticExplication - Level 3 Lumidouce Case Attack DMG: {0}
	burstDMG = []float64{
		2.172,
		2.3349,
		2.4978,
		2.715,
		2.8779,
		3.0408,
		3.258,
		3.4752,
		3.6924,
		3.9096,
		4.1268,
		4.344,
		4.6155,
		4.887,
		5.1585,
	}
)
